#!/usr/bin/env python3
"""Executable gate for RaspberryPi4/Lib/sha1.pi4.

WHY THIS FILE IS WRITTEN THE WAY IT IS

A hash has exactly one useful kind of test: a known-answer test against
answers somebody else computed.  A hash that agrees with itself is a
hash that agrees with its own bug, and on this target the bugs that
have actually happened - a stride of 4 on a 64-bit array, a signed
PeekB on a byte with bit 7 set - are all of the kind that produce a
deterministic, stable, repeatable, WRONG digest.  Nothing about the
output looks broken.  Only an independent oracle can tell.

  THE ORACLE IS NIST'S OWN.  Every expected digest in the main body of
  this gate is PARSED OFF THE DISK out of the NIST CAVP byte-oriented
  SHA test vectors, RaspberryPi4/Reference/cavp_SHA1ShortMsg.rsp and
  cavp_SHA1LongMsg.rsp.  Those files were generated by NIST for the
  Cryptographic Algorithm Validation Program.  Not one expected value
  in them was typed by anybody working on this project, and not one
  came from running sha1.pi4 and writing down what it said.

  THE SECOND ORACLE IS RFC 3174.  Its section 7.3 test driver carries
  four vectors from FIPS PUB 180-1, and they are parsed out of
  RaspberryPi4/Reference/rfc3174.txt - the messages out of its #define
  block and the digests out of its resultarray[] - rather than
  transcribed here.  A transcription is a chance to be wrong that the
  parse does not have.

  THE SHORT VECTORS ARE ALSO RUN SPLIT.  Every CAVP short message is
  fed in one shot and then again in 1-, 3-, 7- and 64-byte chunks.
  Streaming is the property most likely to be quietly broken by a
  partial-block bug and least likely to be caught by a one-shot test,
  because a one-shot test never exercises the partial-block path at
  all for messages under 64 bytes.

  SNAPSHOT AND RESTORE ARE PROVEN ACROSS A SEAM, and proven to be a
  real save: the harness snapshots mid-message, then deliberately
  destroys the live context by starting and running a whole other
  digest, then restores and finishes.  If Restore were a no-op the
  answer would be the wrong one, loudly.

  --mutate IS NOT OPTIONAL AND IT IS THE POINT.  This project has had
  four gates certify real bugs in one week because the model was more
  forgiving than the part.  --mutate rebuilds sha1.pi4 with one
  deliberate defect at a time - twelve of them, each a bug somebody
  could plausibly write - and requires each to behave the way the
  table says it will.  A gate nobody has watched fail is a gate nobody
  has a reason to believe.

  TEN OF THE TWELVE MUST GO RED.  TWO MUST GO GREEN, and that is
  recorded rather than hidden.  Two of the masks in Sha1Rotl turn out
  to be individually unobservable - each is redundant GIVEN THE OTHER -
  and a further mutation removes both at once and goes red, which is
  the evidence that neither is decoration.  The first sweep of this
  gate found all three, and the honest thing to do with a finding like
  that is write it down, not delete the mutation that produced it.
  The sweep fails if any mutation deviates from its expectation IN
  EITHER DIRECTION, so a mask that becomes observable later is news
  this gate will deliver.

WHAT THIS GATE DOES NOT SAY

  * That any of this runs on silicon.  tools/a64/a64_interp.py is a
    model of the instruction set, not of the BCM2711.  It has no
    caches and no real memory system.  The silicon evidence has to
    come from a board, and
    RaspberryPi4/Examples/Diagnostics/pi4WifiJoin.pi4 runs the same
    vectors there.
  * Anything about SHA-1's security.  SHA-1 is collision-broken and
    sha1.pi4's header says so at length.  This gate proves the file
    computes the function the standard defines, which is a different
    and much smaller claim.
  * The 1,000,000-byte RFC 3174 case, unless --million is passed.  It
    is 15,625 compressions against a Python model and takes minutes
    rather than seconds; it is the only vector here that reaches a
    byte count above 16 bits.

Run: python tools/a64/a64_sha1_check.py
     python tools/a64/a64_sha1_check.py --million
     python tools/a64/a64_sha1_check.py --mutate
"""

from __future__ import annotations
import os

import argparse
import pathlib
import re
import struct
import subprocess
import sys
import time

HERE = pathlib.Path(__file__).resolve().parent
# THE TREE UNDER TEST IS THE ONE THIS SCRIPT LIVES IN. A root pinned into
# the file made this gate build a DIFFERENT working copy, with that copy's
# compiler, and print the answer as this tree's. Override deliberately with
# PMF_REPO; the tree actually read is printed below so a wrong one is visible.
ROOT = pathlib.Path(__file__).resolve().parents[2]
print("[gate] tree under test: %s" % ROOT, file=sys.stderr)
sys.path.insert(0, str(HERE))
from a64_interp import A64  # noqa: E402
from a64_target import (TARGETS, apply_target,  # noqa: E402
                        patch_harness)

PMFC = os.environ.get("PMF_COMPILER") or "PureMetalForge.exe"  # rebound from --compiler
# Every compile resolves includes from THIS tree only.
BUILD_ENV = dict(os.environ, PMF_ROOT=str(ROOT))
LIB = ROOT / "RaspberryPi4" / "Lib" / "sha1.pi4"
REF = ROOT / "RaspberryPi4" / "Reference"
CAVP_SHORT = REF / "cavp_SHA1ShortMsg.rsp"
CAVP_LONG = REF / "cavp_SHA1LongMsg.rsp"
RFC3174 = REF / "rfc3174.txt"
WORK = ROOT / "_work"

LOAD = 0x00400000
LOADER_SP = 0x00100000
LOADER_LR = 0xDEADBEE0
STACK = 0x03000000

# The board this run builds for.  Rebound by apply_target() from the
# --target flag before anything else runs; see tools/a64/a64_target.py.
# Two AArch64 boards now share these libraries - the Pi 4's A72 and the
# Arduino UNO Q's A53 - and they share the FILES, not copies of them, so
# this gate grades both rather than being duplicated.
TFLAG = "pi4"
TARGET_NAME = "pi4"
TARGET_WHAT = TARGETS["pi4"]["what"]
CONSOLE_INCLUDE = TARGETS["pi4"]["console"]


UART_LO = 0xFE201000
UART_HI = 0xFE201048
UART_DR = 0xFE201000

# Far above the image at $400000 and the stack top at $3000000, and
# nowhere near anything sha1.pi4 or uart.pi4 touches.
H_SCRIPT = 0x06000000
H_RESULT = 0x0A000000

STEP_LIMIT = 4_000_000_000

OP_END = 0
OP_ONESHOT = 1
OP_CHUNKED = 2
OP_SEAM = 3
OP_REPEAT = 4


# =====================================================================
#  THE HARNESS
# =====================================================================
#  It reads a script of hash jobs out of memory at #H_SCRIPT, runs
#  them, and writes each 20-byte digest into #H_RESULT.  Every message
#  is DATA, so adding a vector never changes this file.
#
#  SCRIPT RECORD, 12 bytes then `ln` bytes of message, padded to 4:
#      +0 op   +4 arg   +8 ln   +12 message
#  op 0 ends the script.
#
#  RESULT RECORD: 20 bytes of digest, one per script record.
# =====================================================================
HARNESS = r'''
; ======================================================================
;  sha1harness.pi4 - GENERATED BY tools/a64/a64_sha1_check.py.
;  NOT A SOURCE FILE. DO NOT EDIT.
; ======================================================================
XIncludeFile "RaspberryPi4/Lib/uart.pi4"
XIncludeFile "__LIB__"

#H_SCRIPT = $06000000
#H_RESULT = $0A000000

Global Dim hSnap.a[92]
Global Dim hWaste.a[20]

Procedure.i Main()
  Define p.i
  Define q.i
  Define op.i
  Define arg.i
  Define ln.i
  Define blob.i
  Define off.i
  Define n.i
  Define r.i

  p = #H_SCRIPT
  q = #H_RESULT

  Repeat
    op  = PeekN(p)
    arg = PeekN(p + 4)
    ln  = PeekN(p + 8)
    If op = 0
      Break
    EndIf
    blob = p + 12

    If op = 1
      ; One shot.
      Sha1Of(blob, ln, q)

    ElseIf op = 2
      ; Streamed in fixed-size pieces. arg is the piece size.
      Sha1Begin()
      off = 0
      While off < ln
        n = arg
        If off + n > ln
          n = ln - off
        EndIf
        Sha1Update(blob + off, n)
        off = off + n
      Wend
      Sha1End(q)

    ElseIf op = 3
      ; Snapshot at byte arg, then DESTROY the live context with a
      ; whole other digest, then restore and finish. If Restore did
      ; nothing the answer would be the digest of the tail alone.
      Sha1Begin()
      If arg > 0
        Sha1Update(blob, arg)
      EndIf
      Sha1Snapshot(@hSnap[0])
      Sha1Begin()
      Sha1Update(blob, ln)
      Sha1End(@hWaste[0])
      Sha1Restore(@hSnap[0])
      If ln > arg
        Sha1Update(blob + arg, ln - arg)
      EndIf
      Sha1End(q)

    ElseIf op = 4
      ; The message is the blob repeated arg times. This is how the
      ; RFC 3174 cases with a repeat count are run without putting a
      ; million bytes into the model's memory.
      Sha1Begin()
      r = 0
      While r < arg
        Sha1Update(blob, ln)
        r = r + 1
      Wend
      Sha1End(q)
    EndIf

    p = p + 12 + (((ln + 3) / 4) * 4)
    q = q + 20
  ForEver

  UartWriteStr("sha1harness done")
  ProcedureReturn 0
EndProcedure
'''


class Script:
    """The byte stream the harness walks, plus a label per record so a
    failure can name itself."""

    def __init__(self) -> None:
        self.buf = bytearray()
        self.labels: list[str] = []
        self.expect: list[bytes] = []

    def add(self, op: int, label: str, expect: bytes, msg: bytes = b"",
            arg: int = 0) -> None:
        self.labels.append(label)
        self.expect.append(expect)
        self.buf += struct.pack("<III", op, arg, len(msg))
        self.buf += msg
        pad = (-len(msg)) % 4
        self.buf += b"\x00" * pad

    def done(self) -> bytes:
        return bytes(self.buf) + struct.pack("<III", OP_END, 0, 0)


# =====================================================================
#  THE ORACLES, READ OFF THE DISK
# =====================================================================
def parse_cavp(path: pathlib.Path) -> list[tuple[int, bytes, bytes]]:
    """Parse a NIST CAVP .rsp file into (bitlen, message, digest).

    The format is a run of `Len =` / `Msg =` / `MD =` triples.  The
    zero-length case writes `Msg = 00` and means the EMPTY message -
    that convention is NIST's, it is the single most commonly mis-read
    line in the file, and getting it wrong would silently drop the one
    vector that exercises the empty-message padding path.
    """
    if not path.exists():
        raise SystemExit(
            f"the oracle is missing: {path}\n"
            "It is the NIST CAVP byte-oriented SHA test vector set. Fetch\n"
            "shabytetestvectors.zip from csrc.nist.gov into "
            "RaspberryPi4/Reference/ - do not invent replacements.")
    out: list[tuple[int, bytes, bytes]] = []
    length = None
    msg = None
    for raw in path.read_text(errors="replace").splitlines():
        line = raw.strip()
        if line.startswith("Len ="):
            length = int(line.split("=", 1)[1])
            msg = None
        elif line.startswith("Msg ="):
            msg = bytes.fromhex(line.split("=", 1)[1].strip())
        elif line.startswith("MD ="):
            md = bytes.fromhex(line.split("=", 1)[1].strip())
            if length is None or msg is None:
                raise SystemExit(f"{path.name}: an MD with no Len/Msg before it")
            if length % 8:
                raise SystemExit(
                    f"{path.name}: Len={length} is not a whole number of "
                    "bytes. This is the BYTE-oriented vector set; a bit "
                    "count that is not a multiple of 8 means the wrong file "
                    "was downloaded.")
            n = length // 8
            body = b"" if n == 0 else msg
            if len(body) != n:
                raise SystemExit(
                    f"{path.name}: Len={length} but Msg is {len(body)} bytes")
            if len(md) != 20:
                raise SystemExit(f"{path.name}: an MD that is not 20 bytes")
            out.append((n, body, md))
            length = None
            msg = None
    if not out:
        raise SystemExit(f"{path.name}: no vectors parsed - has the format changed?")
    return out


def parse_rfc3174() -> list[tuple[str, bytes, int, bytes]]:
    """Parse the four FIPS 180-1 vectors out of RFC 3174 section 7.3.

    Returns (name, unit, repeat, digest).  The message is `unit`
    repeated `repeat` times - that is how the RFC's own driver states
    it, and keeping the shape means the 1,000,000-byte case does not
    have to exist as a literal anywhere.

    The messages come from the `#define TEST*` block and the digests
    from `resultarray[]`, both parsed rather than transcribed.  If the
    RFC is ever replaced by a different revision this raises instead of
    quietly testing nothing.
    """
    if not RFC3174.exists():
        raise SystemExit(
            f"the citation is missing: {RFC3174}\n"
            "sha1.pi4 cites it by line for every constant it contains.")
    text = RFC3174.read_text(errors="replace")

    defines: dict[str, str] = {}
    for name, body in re.findall(r"#define\s+(TEST\w*)\s+(.+)", text):
        body = body.strip()
        lits = re.findall(r'"((?:[^"\\]|\\.)*)"', body)
        if lits:
            defines[name] = "".join(
                l.replace("\\n", "\n").replace("\\\\", "\\") for l in lits)
        else:
            parts = body.split()
            if all(p in defines for p in parts):
                defines[name] = "".join(defines[p] for p in parts)

    m = re.search(r"repeatcount\[4\]\s*=\s*\{([^}]*)\}", text)
    if not m:
        raise SystemExit("rfc3174.txt: repeatcount[] is gone - find the new form")
    repeats = [int(x) for x in m.group(1).replace(",", " ").split()]

    m = re.search(r"resultarray\[4\]\s*=\s*\{([^}]*)\}", text, re.S)
    if not m:
        raise SystemExit("rfc3174.txt: resultarray[] is gone - find the new form")
    digests = [bytes.fromhex(s.replace(" ", ""))
               for s in re.findall(r'"([0-9A-Fa-f ]+)"', m.group(1))]

    if len(digests) != 4 or len(repeats) != 4:
        raise SystemExit("rfc3174.txt: expected four vectors, found "
                         f"{len(digests)} digests and {len(repeats)} counts")
    for d in digests:
        if len(d) != 20:
            raise SystemExit("rfc3174.txt: a resultarray entry is not 20 bytes")

    out = []
    for i in range(4):
        name = "TEST%d" % (i + 1)
        if name not in defines:
            raise SystemExit(f"rfc3174.txt: {name} is not in the #define block")
        out.append((name, defines[name].encode("latin-1"), repeats[i],
                    digests[i]))
    return out


# =====================================================================
#  BUILD AND RUN
# =====================================================================
def build(lib_include: str, harness: pathlib.Path, img: pathlib.Path) -> None:
    WORK.mkdir(exist_ok=True)
    harness.write_text(patch_harness(HARNESS.replace("__LIB__",
                                                 lib_include),
                                 globals()),
                       encoding="utf-8")
    cmd = [str(PMFC), "--compile", str(harness), "-t", TFLAG,
           "--load-addr", hex(LOAD), "--stack-addr", hex(STACK),
           "--entry-returns", "-o", str(img)]
    r = subprocess.run(cmd, cwd=ROOT, env=BUILD_ENV, text=True,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if r.returncode != 0 or "pmfc: OK" not in r.stdout:
        raise SystemExit("build failed:\n" + r.stdout)


def run(img: pathlib.Path, script: bytes, count: int):
    blob = img.read_bytes()
    cpu = A64()
    mem = cpu.memory
    for i, b in enumerate(blob):
        mem[LOAD + i] = b
    for i, b in enumerate(script):
        mem[H_SCRIPT + i] = b
    cpu.pc = LOAD
    cpu.sp = LOADER_SP
    cpu.x[30] = LOADER_LR

    uart = bytearray()

    def load(addr, size):
        if UART_LO <= addr <= UART_HI:
            return 0                       # a PL011 that is never busy
        return sum(mem.get(addr + i, 0) << (8 * i) for i in range(size))

    def store(addr, value, size):
        if UART_LO <= addr <= UART_HI:
            if addr == UART_DR:
                uart.append(value & 0xFF)
            return
        for i in range(size):
            mem[addr + i] = (value >> (8 * i)) & 0xFF

    cpu.load = load
    cpu.store = store

    steps = 0
    while cpu.pc != LOADER_LR:
        cpu.step()
        steps += 1
        if steps > STEP_LIMIT:
            raise SystemExit("the harness never returned (%d steps)\n%s"
                             % (steps, uart.decode("latin-1")))

    if b"sha1harness done" not in uart:
        raise SystemExit("the harness returned without finishing its script:\n"
                         + uart.decode("latin-1"))

    out = []
    for i in range(count):
        a = H_RESULT + i * 20
        out.append(bytes(mem.get(a + j, 0) for j in range(20)))
    return out, steps


# =====================================================================
#  THE VECTOR SET
# =====================================================================
CHUNKS = (1, 3, 7, 64)


def build_script(million: bool, subset: bool = False) -> Script:
    """The full vector set, or - for the mutation sweep - a subset.

    THE SUBSET IS A TIME DECISION AND NOTHING ELSE.  The full set is
    578 vectors and 120 million model instructions, about four minutes;
    eleven mutations of that is three quarters of an hour and a sweep
    nobody runs is a sweep that does not exist.  The subset keeps every
    CAVP SHORT vector - which is every distinct padding case, 0 to 64
    bytes - both chunkings that matter, every seam, and the four
    longest CAVP long messages, and drops the 60 long vectors that only
    repeat a code path the others already cover.  If a future mutation
    turns out to be invisible to the subset, put it back on the full
    set rather than dropping the mutation.
    """
    s = Script()

    short = parse_cavp(CAVP_SHORT)
    for n, msg, md in short:
        s.add(OP_ONESHOT, "CAVP short len=%d one shot" % n, md, msg)
    for n, msg, md in short:
        for c in ((1, 64) if subset else CHUNKS):
            s.add(OP_CHUNKED, "CAVP short len=%d in %d-byte pieces" % (n, c),
                  md, msg, arg=c)

    # The seam cases.  Split points land before, in the middle of, and
    # one byte short of the message, so a snapshot taken with a full
    # partial block and one taken with an almost-empty one are both
    # covered.
    for n, msg, md in short:
        if n >= 2:
            for cut in sorted({1, n // 2, n - 1}):
                s.add(OP_SEAM,
                      "CAVP short len=%d snapshot at %d" % (n, cut),
                      md, msg, arg=cut)

    long_v = parse_cavp(CAVP_LONG)
    if subset:
        long_v = long_v[:2] + long_v[-2:]
    for n, msg, md in long_v:
        s.add(OP_ONESHOT, "CAVP long len=%d one shot" % n, md, msg)

    for name, unit, rep, md in parse_rfc3174():
        if rep > 1000 and not million:
            continue
        s.add(OP_REPEAT, "RFC 3174 %s (%d x %d bytes)"
              % (name, rep, len(unit)), md, unit, arg=rep)

    return s


def check(img: pathlib.Path, s: Script, quiet: bool = False) -> list[str]:
    got, steps = run(img, s.done(), len(s.labels))
    bad = []
    for i, label in enumerate(s.labels):
        if got[i] != s.expect[i]:
            bad.append("  %-46s expected %s\n  %-46s got      %s"
                       % (label, s.expect[i].hex(), "", got[i].hex()))
    if not quiet:
        print("  %d vectors, %s, %d steps"
              % (len(s.labels), "ALL PASS" if not bad else
                 "%d FAILED" % len(bad), steps))
    return bad


# =====================================================================
#  MUTATIONS
# =====================================================================
#  Each entry is (name, old, new, why).  `old` must occur EXACTLY the
#  number of times given by `count`, so a mutation that silently stops
#  applying - because the file was edited - is an error rather than a
#  free pass.
#  Each entry is (name, old, new, count, expect_red, why).  `old` must
#  occur EXACTLY `count` times, so a mutation that silently stops
#  applying - because the file was edited - is an error rather than a
#  free pass.
#
#  expect_red IS NOT A CONVENIENCE.  Three of the defects below are
#  PROVABLY INVISIBLE to any known-answer test, and the first sweep of
#  this gate found all three.  Deleting them would hide a real finding;
#  pretending they should go red would leave a permanent false alarm.
#  So each mutation records what it is EXPECTED to do, and the sweep
#  fails if a mutation deviates from its expectation IN EITHER
#  DIRECTION.  A mask that is currently unobservable becoming
#  observable is news, and this is the only way to hear it.
#
#  This is the same shape as sha256.pi4's variant scoreboard, arrived
#  at independently and for the same reason: the mask invariant in
#  these files is a REVIEWABILITY property, not a correctness one, and
#  saying so with evidence is worth more than claiming otherwise.
MUTATIONS = [
    ("stride 4 instead of 8",
     "#SHA1_HWORD = 8", "#SHA1_HWORD = 4", 1, True,
     "the 32-bit families' spelling, copied across unchanged: reads the "
     "high half of H[0] as H[1]"),

    # THE FIRST SPELLING OF THIS ONE WAS A NO-OP AND THE SWEEP SAID SO.
    # Swapping PeekA for PeekB on the byte that lands at bit 24, while
    # LEAVING its "& 255" in place, changes nothing: the mask cuts the
    # sign extension off before the shift.  Even without the mask, that
    # particular byte's sign extension lands entirely above bit 31,
    # where the round's own mask removes it.  The byte that actually
    # breaks the word is the LAST one, whose sign extension fills every
    # bit above 7 - so that is the one mutated.
    ("signed byte read, unmasked, low byte",
     "| (PeekA(blk + 3) & 255)", "| (PeekB(blk + 3))", 1, True,
     "PeekB sign-extends; the low byte's extension fills the whole word"),

    ("rotate loses its output mask",
     "ProcedureReturn ((x << n) | ((x & #SHA1_W32) >> (32 - n))) & #SHA1_W32",
     "ProcedureReturn ((x << n) | ((x & #SHA1_W32) >> (32 - n)))", 1, False,
     "PROVABLY UNOBSERVABLE ALONE. The rubbish left in bits 32..62 can "
     "only move upward - additions carry up, left shifts move up - and "
     "the one operation that could drag it down, the right half of the "
     "next rotate, masks its input first. Every value that leaves the "
     "algorithm leaves through '& 255' on a bit below 32"),

    ("rotate right half goes arithmetic",
     "((x & #SHA1_W32) >> (32 - n))", "((x) >> (32 - n))", 1, False,
     "PROVABLY UNOBSERVABLE ALONE. With the output mask still in place "
     "every value reaching Sha1Rotl is clean and non-negative, so an "
     "arithmetic shift and a logical one agree"),

    ("BOTH rotate masks removed at once",
     "ProcedureReturn ((x << n) | ((x & #SHA1_W32) >> (32 - n))) & #SHA1_W32",
     "ProcedureReturn ((x << n) | (x >> (32 - n)))", 1, True,
     "THIS IS WHY BOTH MASKS ARE THERE. Each is redundant given the "
     "other; neither is redundant given nothing. Remove both and dirt "
     "from bits 32..62 is dragged back down into the digest"),

    ("one wrong round constant",
     "+ $5A827999)", "+ $5A82799A)", 1, True,
     "a single-nibble typo in K(0..19)"),

    ("wrong f() in the third quarter",
     "Sha1Maj(b, c, d)", "Sha1Par(b, c, d)", 1, True,
     "rounds 40..59 must use majority, not parity"),

    ("padding spill test off by one",
     "If ptr > 56", "If ptr > 57", 1, True,
     "a 55-byte message would then write its length over the pad"),

    ("schedule rotates by two",
     "! Sha1W[i - 16], 1)", "! Sha1W[i - 16], 2)", 1, True,
     "S^1 in the message schedule is not S^2"),

    ("digest word order",
     "PokeB(dst + i * 4,     (Sha1OutH[i] >> 24) & 255)",
     "PokeB(dst + i * 4,     (Sha1OutH[i] >> 16) & 255)", 1, True,
     "the digest is big-endian; a shift of 16 duplicates a byte"),

    ("one round short",
     """  ; t = 60..79, K = $CA62C1D6 - rfc3174.txt:311
  While i < 80""",
     """  ; t = 60..79, K = $CA62C1D6 - rfc3174.txt:311
  While i < 79""", 1, True,
     "79 rounds instead of 80"),

    ("snapshot counter at the wrong offset",
     "PokeN(dst + 84, Sha1CountLo)", "PokeN(dst + 80, Sha1CountLo)", 1, True,
     "the counter would land in the last four bytes of the block image"),
]


def mutate(args) -> int:
    src = LIB.read_text(encoding="utf-8")
    s = build_script(million=False, subset=True)
    failures = 0
    print("MUTATION TEST - each defect must do what its expectation says")
    for name, old, new, count, expect_red, why in MUTATIONS:
        n = src.count(old)
        if n != count:
            print("  %-38s CANNOT APPLY - the anchor occurs %d times, "
                  "expected %d" % (name, n, count))
            print("        anchor: %r" % (old,))
            failures += 1
            continue
        mut = WORK / "sha1_mut.pi4"
        mut.write_text(src.replace(old, new), encoding="utf-8")
        red = None
        nbad = 0
        try:
            build("_work/sha1_mut.pi4", WORK / "sha1harness_mut.pi4",
                  WORK / "sha1check_mut.img")
        except SystemExit:
            red = True
            note = "refused to build"
        if red is None:
            try:
                bad = check(WORK / "sha1check_mut.img", s, quiet=True)
                nbad = len(bad)
                red = nbad > 0
                note = "%d of %d vectors" % (nbad, len(s.labels))
            except SystemExit:
                red = True
                note = "the harness did not complete"

        if red == expect_red:
            print("  %-38s %-5s (%s)" % (name, "RED" if red else "GREEN", note))
            if not expect_red:
                print("        expected green: %s" % why)
        else:
            failures += 1
            if expect_red:
                print("  %-38s *** GREEN - THE GATE DID NOT SEE IT *** %s"
                      % (name, why))
            else:
                print("  %-38s *** RED, AND IT WAS EXPECTED GREEN ***" % name)
                print("        The reasoning recorded for this mutation no "
                      "longer holds. That is a finding, not a failure of the")
                print("        library: read it, then update the note. Was: %s"
                      % why)
    return failures


def resolve_compiler(requested):
    """Resolve the PureMetal compiler the way tools/build.py does."""
    sys.path.insert(0, str(ROOT / "tools"))
    import build as anvil_build  # noqa: E402
    return anvil_build.find_compiler(requested)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--compiler", default=os.environ.get("PMF_COMPILER"),
                    help="path of PureMetalForge.exe (or set PMF_COMPILER); "
                         "it is run with --compile")
    ap.add_argument("--target", choices=sorted(TARGETS),
                    default="pi4",
                    help="which AArch64 board's image contract "
                         "to build and grade against")
    ap.add_argument("--mutate", action="store_true",
                    help="rebuild the library broken, one defect at a time, "
                         "and require this gate to go red for each")
    ap.add_argument("--million", action="store_true",
                    help="also run RFC 3174 TEST3, one million bytes; "
                         "minutes, not seconds")
    args = ap.parse_args()
    globals()["PMFC"] = resolve_compiler(args.compiler)
    apply_target(globals(), args.target)
    # A GATE THAT DOES NOT SAY WHICH BOARD IT GRADED IS A RESULT
    # THAT CAN BE FILED AGAINST THE WRONG ONE.  Printed before any
    # work, so it is at the top of the transcript even on a failure.
    print("[gate] target %s - %s, image at $%08X, stack $%08X"
          % (TARGET_NAME, TARGET_WHAT, LOAD, STACK))

    WORK.mkdir(exist_ok=True)

    if args.mutate:
        build("RaspberryPi4/Lib/sha1.pi4", WORK / "sha1harness.pi4",
              WORK / "sha1check.img")
        s = build_script(million=False, subset=True)
        bad = check(WORK / "sha1check.img", s)
        if bad:
            print("the unmutated library is already failing; fix that first")
            print("\n".join(bad[:10]))
            return 1
        return 1 if mutate(args) else 0

    t0 = time.time()
    build("RaspberryPi4/Lib/sha1.pi4", WORK / "sha1harness.pi4",
          WORK / "sha1check.img")
    s = build_script(args.million)
    print("SHA-1 gate - oracles: NIST CAVP SHA1ShortMsg/SHA1LongMsg, RFC 3174")
    bad = check(WORK / "sha1check.img", s)
    print("  %.1f s" % (time.time() - t0))
    if bad:
        print("\nFAILURES")
        print("\n".join(bad))
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
