#!/usr/bin/env python3
"""Executable gate for RaspberryPi4/Lib/ec256.pi4 and
RaspberryPi4/Lib/x25519.pi4 - the M8 elliptic-curve primitives on AArch64.

WHY THIS FILE IS WRITTEN THE WAY IT IS

  THE VECTORS ARE THE ONES THE PICO GATES ALREADY USE.  They are not
  transcribed here and they are not generated here: this gate IMPORTS
  build_ec256() and build_x25519() out of tools/gen_ec_vectors.py, the
  file that emits ec256Vectors.pico2 and x25519Vectors.pico2 for the
  three 32-bit families.  That generator ANCHORS its own oracle first -
  it aborts unless a dependency-free Python EC implementation reproduces
  the published NIST/BearSSL P-256 generator KAT and the RFC 7748 X25519
  KAT exactly - so the expectations arrive already checked against
  published constants.  One table, four families.

  THE TWO BUILDERS ARE CALLED IN THE GENERATOR'S OWN ORDER, ec256 then
  x25519, and that is not cosmetic: they draw from one seeded
  random.Random, so calling them the other way round would produce a
  DIFFERENT, self-consistent, and quietly non-shared vector set.

  THE NEGATIVES ARE THE POINT.  Four of them, and each is a different
  way an attacker-supplied point can be wrong: off the curve (one bit
  flipped in Y), the wrong uncompressed prefix ($06 instead of $04), a
  coordinate that is not less than p (X = p exactly), and the origin
  encoded as $04 || 0 || 0.  EcP256Mul must return 0 for every one.  A
  gate with only positive vectors goes green on a decoder that never
  refuses anything, and an EC library that accepts an off-curve point is
  how a private key leaves the building.

  THE 1000-ITERATION X25519 TEST IS NOT RUN HERE, AND THAT HOLE IS
  DECLARED RATHER THAN HIDDEN.  One X25519 is about 35 million model
  instructions; a thousand of them is 35 billion, which is a day under
  this oracle for a test whose value is repetition.  The ONE-iteration
  RFC 7748 iterated case IS run, against the published
  422c8e7a... expectation.  --iter1000 runs the full one for anybody
  willing to wait, and the summary line says which of the two ran.

  IT RUNS ON ALL CORES.  The image is built ONCE and the job list is
  sharded across a process pool; every worker runs the same image over
  its own slice.  --jobs overrides.

WHAT THIS GATE DOES NOT SAY

  * That any of this runs on silicon.  The oracle is a model of the
    instruction set: no caches, no memory system, no clock.
  * That the implementation is constant time ON HARDWARE.  --timing
    checks that the MODEL executes the identical number of instructions
    for scalars of wholly different content at the same length, which
    rules out a data-dependent branch or a secret-indexed access in the
    compiled code.  It says nothing about what a real Cortex-A72 does.

Run: python tools/a64/a64_ec_check.py
     python tools/a64/a64_ec_check.py --timing
     python tools/a64/a64_ec_check.py --mutate
"""

from __future__ import annotations

import argparse
import concurrent.futures
import importlib.util
import os
import pathlib
import struct
import subprocess
import sys
import time

HERE = pathlib.Path(__file__).resolve().parent
ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(HERE))

PMFC = os.environ.get("PMF_COMPILER") or "PureMetalForge.exe"  # rebound from --compiler
# Every compile resolves includes from THIS tree only.
BUILD_ENV = dict(os.environ, PMF_ROOT=str(ROOT))
# --jobs, remembered for the pools that are not handed it directly.
JOBS_CAP = None
EC256 = ROOT / "RaspberryPi4" / "Lib" / "ec256.pi4"
X25519 = ROOT / "RaspberryPi4" / "Lib" / "x25519.pi4"
WORK = ROOT / "_work"

LOAD = 0x00400000
LOADER_SP = 0x00100000
LOADER_LR = 0xDEADBEE0
STACK = 0x03000000

UART_LO = 0xFE201000
UART_HI = 0xFE201048
UART_DR = 0xFE201000

H_SCRIPT = 0x06000000
H_RESULT = 0x0A000000
H_OUT = 0x0B000000

STEP_LIMIT = 200_000_000_000
RESULT_STRIDE = 32
SENTINEL = 0xA5

(OP_END, OP_MULGEN, OP_MUL, OP_ECDH, OP_NEG, OP_X25519,
 OP_XITER) = range(7)


# =====================================================================
#  THE HARNESS
# =====================================================================
#  SCRIPT RECORD - a 28-byte header, then blob0 || blob1, padded to 4:
#      +0 op  +4 a0  +8 a1  +12 n0  +16 n1  +20 outlen  +24 (spare)
#  RESULT RECORD - 32 bytes, FOUR 64-BIT FIELDS:
#      +0 scalar0 (the verdict)  +8 scalar1  +16 outlen  +24 spare
#
#  THE VERDICT FIELD IS 64 BITS AND THAT IS NOT DECORATION.  The A64 GCM
#  gate stored its verdicts with PokeN and the one mutation it existed
#  to catch survived, because the wrong value's set bits were all above
#  bit 31 and the low half read back clean.
# =====================================================================
HARNESS = r'''
; ======================================================================
;  echarness.pi4 - GENERATED BY tools/a64/a64_ec_check.py.
;  NOT A SOURCE FILE. DO NOT EDIT.
; ======================================================================
XIncludeFile "RaspberryPi4/Lib/uart.pi4"
XIncludeFile "RaspberryPi4/Lib/bignum.pi4"
XIncludeFile "__EC256__"
XIncludeFile "__X25519__"

#H_SCRIPT = $06000000
#H_RESULT = $0A000000
#H_OUT    = $0B000000

; The point buffer is `.a` - EcP256Mul writes 65 raw bytes into it.
Global Dim EhPt.a[80]
Global Dim EhK.a[40]
Global Dim EhOut.a[40]
Global Dim EhU.a[40]

Procedure.i Main()
  Define p.i
  Define q.i
  Define o.i
  Define op.i
  Define a0.i
  Define a1.i
  Define n0.i
  Define n1.i
  Define outlen.i
  Define b0.i
  Define b1.i
  Define s0.i
  Define s1.i
  Define i.i
  Define n.i

  EcInit()
  X25519Init()

  p = #H_SCRIPT
  q = #H_RESULT
  o = #H_OUT

  Repeat
    op     = PeekN(p)
    a0     = PeekN(p + 4)
    a1     = PeekN(p + 8)
    n0     = PeekN(p + 12)
    n1     = PeekN(p + 16)
    outlen = PeekN(p + 20)
    If op = 0
      Break
    EndIf
    b0 = p + 28
    b1 = b0 + n0

    s0 = 0
    s1 = 0

    ; The output area is pre-filled with a sentinel by the gate, so a
    ; refusal that writes anyway is as loud as a wrong byte.
    If op = 1
      ; MULGEN - dst = k * G.
      s0 = EcP256Mulgen(@EhPt[0], b0, n0)
      i = 0
      While i < outlen
        PokeB(o + i, EhPt[i])
        i = i + 1
      Wend

    ElseIf op = 2
      ; MUL - pt = k * pt, in place, 65 bytes.
      i = 0
      While i < 65
        EhPt[i] = PeekA(b0 + i) & 255
        i = i + 1
      Wend
      s0 = EcP256Mul(@EhPt[0], 65, b1, n1)
      i = 0
      While i < outlen
        PokeB(o + i, EhPt[i])
        i = i + 1
      Wend

    ElseIf op = 3
      ; ECDH - the shared secret is the X coordinate of priv * peer,
      ; which is bytes 1..32 of the multiplied point.
      i = 0
      While i < 65
        EhPt[i] = PeekA(b1 + i) & 255
        i = i + 1
      Wend
      s0 = EcP256Mul(@EhPt[0], 65, b0, n0)
      i = 0
      While i < outlen
        PokeB(o + i, EhPt[1 + i])
        i = i + 1
      Wend

    ElseIf op = 4
      ; NEG - a point that must be REFUSED. Only the verdict is read.
      i = 0
      While i < 65
        EhPt[i] = PeekA(b0 + i) & 255
        i = i + 1
      Wend
      s0 = EcP256Mul(@EhPt[0], 65, b1, n1)

    ElseIf op = 5
      ; X25519 - out = scalar * u, all 32-byte little-endian.
      s0 = X25519(@EhOut[0], b0, b1)
      i = 0
      While i < outlen
        PokeB(o + i, EhOut[i])
        i = i + 1
      Wend

    ElseIf op = 6
      ; XITER - the RFC 7748 iterated test, a0 iterations from k = u = 9.
      i = 0
      While i < 32
        EhK[i] = PeekA(b0 + i) & 255
        EhU[i] = PeekA(b0 + i) & 255
        i = i + 1
      Wend
      n = 0
      While n < a0
        X25519(@EhOut[0], @EhK[0], @EhU[0])
        i = 0
        While i < 32
          EhU[i] = EhK[i]
          EhK[i] = EhOut[i]
          i = i + 1
        Wend
        n = n + 1
      Wend
      i = 0
      While i < outlen
        PokeB(o + i, EhK[i])
        i = i + 1
      Wend
    EndIf

    PokeI(q, s0)
    PokeI(q + 8, s1)
    PokeI(q + 16, outlen)
    PokeI(q + 24, 0)

    p = p + 28 + n0 + n1
    p = ((p + 3) / 4) * 4
    q = q + 32
    o = o + (((outlen + 3) / 4) * 4)
  ForEver

  UartWriteStr("echarness done")
  ProcedureReturn 0
EndProcedure
'''


# =====================================================================
#  THE VECTOR SET, IMPORTED FROM THE GENERATOR THE PICO GATES USE
# =====================================================================
def load_tables():
    gen_path = ROOT / "tools" / "gen_ec_vectors.py"
    if not gen_path.exists():
        raise SystemExit(
            "the vector generator is missing: %s\n"
            "This gate deliberately has no vectors of its own - it reads\n"
            "the same builders that emit ec256Vectors.pico2 for the Pico\n"
            "gates." % gen_path)
    spec = importlib.util.spec_from_file_location("gen_ec_vectors", gen_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    for name in ("anchor", "build_ec256", "build_x25519", "pt_mul", "G",
                 "enc_point", "x25519"):
        if not hasattr(mod, name):
            raise SystemExit(
                "gen_ec_vectors.py no longer defines %r; this gate reads it "
                "BY NAME and must be updated WITH it, not around it" % name)
    # THE ANCHOR RUNS FIRST, exactly as the generator's main() does. It
    # aborts unless the pure-Python oracle reproduces the published
    # NIST/BearSSL P-256 KAT and the RFC 7748 X25519 KAT, so nothing
    # below can be wrong in only one place.
    mod.anchor()
    return mod


class Script:
    def __init__(self):
        self.buf = bytearray()
        self.jobs = []
        self.records = []
        self.out_off = []
        self._o = 0

    def add(self, op, label, a0=0, a1=0, b0=b"", b1=b"",
            out=None, scalars=None):
        outlen = 0 if out is None else len(out)
        rec = struct.pack("<IIIIIII", op, a0 & 0xFFFFFFFF, a1 & 0xFFFFFFFF,
                          len(b0), len(b1), outlen, 0)
        rec += b0 + b1
        rec += b"\x00" * ((-len(rec)) % 4)
        self._append(rec, label, op, scalars, out)

    def _append(self, rec, label, op, scalars, out):
        self.jobs.append((label, op, scalars, out))
        self.records.append(rec)
        self.out_off.append(self._o)
        self._o += ((0 if out is None else len(out)) + 3) // 4 * 4
        self.buf += rec

    def done(self):
        return bytes(self.buf) + struct.pack("<IIIIIII", OP_END,
                                             0, 0, 0, 0, 0, 0)

    def __len__(self):
        return len(self.jobs)


X_ITER1 = bytes.fromhex(
    "422c8e7a6227d7bca1350b3e2bb7279f7897b87bb6854b783c60e80311ae3079")
X_ITER1000 = bytes.fromhex(
    "684cf59ba83309552800ef566f2f4d3c1c3887c49360e3875f2eb94d99532c51")
X_BASE9 = bytes([9] + [0] * 31)


# =====================================================================
#  THIS GATE'S TWO DERIVED CASES, AND THE SWEEP IS WHY THEY EXIST
# =====================================================================
#  Both were added on 2026-09-05 because the mutation sweep went RED with
#  two survivors that the table said must die - M6 and M12.  Neither was
#  a hole in the library: each was a CHECK THAT NO VECTOR REACHED, which
#  is the same failure the A64 GCM sweep found four times over.  Nothing
#  below is transcribed; both are computed from the generator's own
#  constants and its own anchored oracle.
def derived_range_point(g):
    """$04 || p || sqrt(B) - the one non-canonical encoding on this curve
    whose REDUCTION is a real point, so only the range check can refuse it.

    The shared set's "X = p" negative does not reach the range check.  It
    keeps the original Y, so after the mutation deletes "coordinate < p"
    the decoder reduces X = p to 0 and asks whether (0, Y) is on the
    curve - it is not, the on-curve test refuses it anyway, and M6 lives.

    P-256's b is a QUADRATIC RESIDUE mod p, so (0, sqrt(b)) IS on the
    curve: y^2 = 0^3 - 3*0 + b.  Encoding that point's X as p instead of
    0 gives a value that is >= p and whose reduction is legitimate, so
    the range check is the ONLY thing standing between it and an accept.
    p = 3 mod 4, so the root is b^((p+1)/4).

    This is the only such encoding available.  Every other non-canonical
    X is p + x for x < 2^256 - p, which is under 2^224, and finding an
    on-curve point with an X that small is a 2^32 search.
    """
    if g.P % 4 != 3:
        return None
    y = pow(g.B, (g.P + 1) // 4, g.P)
    if (y * y - g.B) % g.P != 0 or not g.on_curve(0, y):
        return None
    return b"\x04" + g.P.to_bytes(32, "big") + y.to_bytes(32, "big")


def derived_unclamped_scalar(g, sc):
    """KAT 0's scalar with bit 254 CLEARED, which the clamp must put back.

    RFC 7748's clamp is k[0] &= 248; k[31] &= 127; k[31] |= 64.  Every
    scalar in the shared table already has bit 254 set, so the `|= 64`
    is a no-op on all of them and M12 - which deletes it - survives.

    Clearing that one bit costs NOTHING in expectations: the generator's
    own oracle clamps before it computes, so it returns the SAME answer
    for this scalar as for the original, and the case reuses KAT 0's
    published output unchanged.  A library that clamps correctly agrees;
    one that has lost the `|= 64` runs a different ladder and does not.
    """
    if not (sc[31] & 0x40):
        return None                      # already clear - nothing to prove
    out = bytearray(sc)
    out[31] &= ~0x40
    return bytes(out)


def build_script(g, level="full", iter1000=False):
    """level: "full" or "mutant" (cheap, but must still reach every line)."""
    mulgen, mul, ecdh, neg = g.build_ec256()
    kats, iters = g.build_x25519()
    s = Script()
    mutant = (level == "mutant")

    if mutant:
        # THE MUTANT SUBSET IS A TIME DECISION AND IT HAS ONE HARD
        # REQUIREMENT: every line a mutation can be planted in must still
        # be reached.  A full 32-byte scalar is 128 ladder windows and
        # about 65 million model instructions; a ONE-BYTE scalar is four
        # windows and reaches the identical code, because the ladder is a
        # fixed loop over the scalar's bytes.  The short-scalar
        # expectations come from the generator's OWN anchored oracle
        # (pt_mul), so they are not a second source of truth.
        #
        # Everything that is not the ladder is kept in full: the two
        # carry KATs already use a one-byte scalar, and all four
        # negatives run, because the decoder is where most of the
        # mutations live.
        short = bytes([0x2B])
        base = g.pt_mul(0x2B, g.G)
        s.add(OP_MULGEN, "mulgen (short scalar $2B)", b0=short,
              out=g.enc_point(base), scalars=(65, None))
        for i, (pin, k, pout, r) in enumerate(mul):
            s.add(OP_MUL, "mul KAT %d" % i, b0=pin, b1=k, out=pout,
                  scalars=(r, None))
        priv, peer, sx, r = ecdh[0]
        peer_pt = (int.from_bytes(peer[1:33], "big"),
                   int.from_bytes(peer[33:65], "big"))
        s.add(OP_ECDH, "ecdh (short private $2B)", b0=short, b1=peer,
              out=g.pt_mul(0x2B, peer_pt)[0].to_bytes(32, "big"),
              scalars=(1, None))
        for i, (pt, k, r) in enumerate(neg):
            s.add(OP_NEG, "negative %d (must be REFUSED)" % i, b0=pt,
                  b1=short, scalars=(0, None))
        sc, u, out = kats[0]
        s.add(OP_X25519, "x25519 RFC 7748 KAT 1", b0=sc, b1=u, out=out,
              scalars=(1, None))
        add_derived(s, g, kats, short)
        return s

    for i, (k, pt) in enumerate(mulgen):
        s.add(OP_MULGEN, "mulgen %d (%d-byte scalar)" % (i, len(k)),
              b0=k, out=pt, scalars=(65, None))
    for i, (pin, k, pout, r) in enumerate(mul):
        s.add(OP_MUL, "mul %d (the BearSSL P256 carry KAT)" % i,
              b0=pin, b1=k, out=pout, scalars=(r, None))
    for i, (priv, peer, sx, r) in enumerate(ecdh):
        s.add(OP_ECDH, "ecdh %d (shared X)" % i, b0=priv, b1=peer,
              out=sx, scalars=(r, None))
    for i, (pt, k, r) in enumerate(neg):
        s.add(OP_NEG, "negative %d (must be REFUSED: %s)"
              % (i, NEG_WHY[i] if i < len(NEG_WHY) else "?"),
              b0=pt, b1=k, scalars=(r, None))
    for i, (sc, u, out) in enumerate(kats):
        s.add(OP_X25519, "x25519 %d" % i, b0=sc, b1=u, out=out,
              scalars=(1, None))

    add_derived(s, g, kats, mulgen[0][0])

    # The RFC 7748 iterated tests.  One iteration always; a thousand only
    # on demand - see the module docstring.
    s.add(OP_XITER, "x25519 iterated, 1 round (RFC 7748 5.2)", a0=1,
          b0=X_BASE9, out=X_ITER1)
    if iters and iters[0][1] != X_ITER1:
        raise SystemExit("the generator's 1-iteration value is not the "
                         "published RFC 7748 one; the table changed under "
                         "this gate")
    if iter1000:
        s.add(OP_XITER, "x25519 iterated, 1000 rounds (RFC 7748 5.2)",
              a0=1000, b0=X_BASE9, out=X_ITER1000)
    return s


NEG_WHY = [
    "off the curve, one bit flipped in Y",
    "wrong uncompressed prefix $06",
    "coordinate X = p, not less than p",
    "the origin encoded as $04 || 0 || 0",
]


def add_derived(s, g, kats, scalar):
    """The two cases the 2026-09-05 sweep proved were missing.

    Both are in EVERY level, including the mutant subset, because the
    mutations they exist to kill are decoder mutations and the subset
    already keeps every negative for that reason.  Neither costs a
    ladder the subset was not already running.
    """
    pt = derived_range_point(g)
    if pt is None:
        raise SystemExit(
            "the derived range-check negative could not be built from the "
            "generator's own constants (p mod 4, or b is no longer a "
            "quadratic residue). This gate will not silently drop the only "
            "case that reaches the 'coordinate < p' test - see M6.")
    s.add(OP_NEG, "derived negative: X = p with Y = sqrt(b), the one "
                  "non-canonical encoding whose REDUCTION is on the curve "
                  "(only the range check can refuse it)",
          b0=pt, b1=scalar, scalars=(0, None))

    sc, u, out = kats[0]
    unclamped = derived_unclamped_scalar(g, sc)
    if unclamped is None:
        raise SystemExit(
            "KAT 0's scalar no longer has bit 254 set, so clearing it "
            "proves nothing about the clamp. Pick another KAT deliberately "
            "rather than letting this case become a no-op - see M12.")
    s.add(OP_X25519, "derived: RFC 7748 KAT 1 with the scalar's bit 254 "
                     "CLEARED - the clamp must put it back, so the answer "
                     "is unchanged", b0=unclamped, b1=u, out=out,
          scalars=(1, None))


# =====================================================================
#  BUILD AND RUN
# =====================================================================
def build(ec_include, x_include, harness, img):
    WORK.mkdir(exist_ok=True)
    src = HARNESS.replace("__EC256__", ec_include).replace("__X25519__",
                                                           x_include)
    harness.write_text(src, encoding="utf-8")
    cmd = [str(PMFC), "--compile", str(harness), "-t", "pi4",
           "--load-addr", hex(LOAD), "--stack-addr", hex(STACK),
           "--entry-returns", "-o", str(img)]
    r = subprocess.run(cmd, cwd=ROOT, env=BUILD_ENV, text=True,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if r.returncode != 0 or "pmfc: OK" not in r.stdout:
        raise SystemExit("build failed:\n" + r.stdout)
    return img.stat().st_size


def run_raw(img_bytes, script, count, out_bytes):
    from a64_interp import A64
    cpu = A64()
    mem = cpu.memory
    for i, b in enumerate(img_bytes):
        mem[LOAD + i] = b
    for i, b in enumerate(script):
        mem[H_SCRIPT + i] = b
    for i in range(count * RESULT_STRIDE):
        mem[H_RESULT + i] = SENTINEL
    for i in range(out_bytes):
        mem[H_OUT + i] = SENTINEL

    cpu.pc = LOAD
    cpu.sp = LOADER_SP
    cpu.x[30] = LOADER_LR
    uart = bytearray()

    def load(addr, size):
        if UART_LO <= addr <= UART_HI:
            return 0
        return sum(mem.get(addr + i, 0) << (8 * i) for i in range(size))

    def store(addr, value, size):
        if UART_LO <= addr <= UART_HI:
            if addr == UART_DR:
                uart.append(value & 0xFF)
            return
        for i in range(size):
            mem[addr + i] = (value >> (8 * i)) & 0xFF

    cpu.load = load
    cpu.store = store

    steps = 0
    while cpu.pc != LOADER_LR:
        cpu.step()
        steps += 1
        if steps > STEP_LIMIT:
            raise SystemExit("the harness never returned (%d steps)\n%s"
                             % (steps, uart.decode("latin-1")))
    if b"echarness done" not in uart:
        raise SystemExit("the harness returned without finishing its "
                         "script:\n" + uart.decode("latin-1"))

    recs = [bytes(mem.get(H_RESULT + i * RESULT_STRIDE + j, 0)
                  for j in range(RESULT_STRIDE))
            for i in range(count)]
    out = bytes(mem.get(H_OUT + i, 0) for i in range(out_bytes))
    return recs, out, steps


def check_shard(script, recs, out):
    bad = []
    for i, (label, op, scalars, expect) in enumerate(script.jobs):
        rec = recs[i]
        if rec == bytes([SENTINEL]) * RESULT_STRIDE:
            bad.append("%s: no record was written at all" % label)
            continue
        s0, s1, outlen, _ = struct.unpack("<QQQQ", rec)
        if scalars is not None:
            e0, e1 = scalars
            if e0 is not None and s0 != e0:
                extra = ""
                if op == OP_NEG:
                    extra = ("  AN INVALID POINT WAS ACCEPTED - this is the "
                             "failure that leaks a private key")
                bad.append("%s: verdict is %d (%016x at full width), want "
                           "%d%s" % (label, s0, s0, e0, extra))
            if e1 is not None and s1 != e1:
                bad.append("%s: scalar1 is %d, want %d" % (label, s1, e1))
        if expect is not None:
            off = script.out_off[i]
            got = out[off:off + len(expect)]
            if got != expect:
                bad.append("%s: %d bytes differ\n    want %s\n    got  %s"
                           % (label, len(expect), expect.hex(), got.hex()))
    return bad


def shard(script, n):
    if n <= 1 or len(script) <= 1:
        return [script]
    idxs = list(range(len(script.jobs)))
    buckets = [idxs[i::n] for i in range(n)]
    out = []
    for b in buckets:
        if not b:
            continue
        s = Script()
        for idx in b:
            label, op, scalars, expect = script.jobs[idx]
            s._append(script.records[idx], label, op, scalars, expect)
        out.append(s)
    return out


def _worker(args):
    img_bytes, blob, count, out_bytes = args
    return run_raw(img_bytes, blob, count, out_bytes)


def run_all(img, script, jobs=None, quiet=False):
    img_bytes = img.read_bytes()
    n = jobs or max(1, (os.cpu_count() or 2) - 2)
    shards = shard(script, n)
    if len(shards) == 1:
        recs, out, steps = run_raw(img_bytes, shards[0].done(),
                                   len(shards[0]), shards[0]._o)
        return check_shard(shards[0], recs, out), steps
    if not quiet:
        print("[gate] %d jobs across %d workers" % (len(script), len(shards)),
              file=sys.stderr)
    args = [(img_bytes, s.done(), len(s), s._o) for s in shards]
    bad, steps = [], 0
    with concurrent.futures.ProcessPoolExecutor(max_workers=len(shards)) as ex:
        for s, (recs, out, st) in zip(shards, ex.map(_worker, args)):
            bad += check_shard(s, recs, out)
            steps += st
    return bad, steps


# =====================================================================
#  THE CONSTANT-TIME CHECK
# =====================================================================
def timing(img, g, quiet=False):
    """A/B instruction counts at equal lengths and different scalars.

    THE SCALAR IS THE PRIVATE KEY.  Both ladders here are fixed-shape by
    construction - EcPointMul does two doublings and one addition per
    2-bit window whatever the window holds, and X25519 runs 255
    iterations whatever the scalar is - so a difference in the model's
    instruction count means a branch or an index read the key.  The
    cases hold the LENGTH fixed and make the VALUE as different as it
    can be: all-zero bits, all-one bits, one bit at the top, one at the
    bottom, and a mixed pattern.
    """
    scalars = [bytes(32),
               b"\xff" * 32,
               b"\x80" + bytes(31),
               bytes(31) + b"\x01",
               bytes((i * 37 + 11) & 0xFF for i in range(32))]
    # TEN INDEPENDENT RUNS, SO THEY GO ACROSS THE POOL.  One P-256 scalar
    # multiply is about 26 million model instructions and one X25519 is
    # about 35 million; ten of them in one process is a third of a
    # billion, which is the kind of serial gate that gets killed for
    # running for hours.  Nothing is shared between them.
    peer = g.enc_point(g.pt_mul(0x2B, g.G))
    ec_args, x_args = [], []
    for sc in scalars:
        s = Script()
        s.add(OP_NEG, "ct-ec", b0=peer, b1=sc)     # verdict only, no output
        ec_args.append((img.read_bytes(), s.done(), len(s), s._o))
        s = Script()
        s.add(OP_X25519, "ct-x", b0=sc, b1=X_BASE9, out=bytes(32))
        x_args.append((img.read_bytes(), s.done(), len(s), s._o))

    args = ec_args + x_args
    nw = max(1, min(len(args), JOBS_CAP or (os.cpu_count() or 2) - 2))
    if nw == 1:
        steps = [run_raw(*a)[2] for a in args]
    else:
        with concurrent.futures.ProcessPoolExecutor(max_workers=nw) as ex:
            steps = [r[2] for r in ex.map(_worker, args)]
    counts_ec = steps[:len(ec_args)]
    counts_x = steps[len(ec_args):]

    rc = 0
    if len(set(counts_ec)) != 1:
        rc = 1
        if not quiet:
            print("FAIL: EcP256Mul executed %s instructions for five "
                  "32-byte scalars that differ only in VALUE - the private "
                  "key is visible in the timing" % (counts_ec,))
    if len(set(counts_x)) != 1:
        rc = 1
        if not quiet:
            print("FAIL: X25519 executed %s instructions for five 32-byte "
                  "scalars that differ only in VALUE - the private key is "
                  "visible in the timing" % (counts_x,))
    if rc:
        if not quiet:
            print("CT GATE RED")
        return 1
    if not quiet:
        print("CT GATE GREEN: EcP256Mul %d instructions and X25519 %d "
              "instructions for all %d scalars at the same length"
              % (counts_ec[0], counts_x[0], len(scalars)))
    return 0


# =====================================================================
#  THE MUTATIONS
# =====================================================================
MUTATIONS = [
    ("M1  a caller declares the point buffer .i instead of .a", "harness",
     "Global Dim EhPt.a[80]",
     "Global Dim EhPt.i[80]",
     "kill"),

    ("M2  ec256 MTZ reverts to the 32-bit complement", "ec256",
     "      r = r & BnNot(BnIsZero(dp))",
     "      r = r & (BnIsZero(dp) ! $FFFFFFFF)",
     "THE 32-BIT SPELLING SURVIVES HERE, and knowing that is the point "
     "of keeping the mutation. r is 0 or 1 and only bit 0 is ever read, "
     "so leaving bits 32..63 of the complement untouched changes "
     "nothing. It is rewritten as BnNot anyway because a reader cannot "
     "tell this instance of the shape from the one that made "
     "GcmDecrypt accept a forged tag without redoing the analysis - and "
     "the thing being decided is whether an attacker's point is on the "
     "curve."),

    ("M3  ec256 on-curve verdict reverts to the 32-bit complement",
     "ec256",
     "  r = r & BnNot(RunCode(pt, @EcCheckQ, @EcCodeChk))",
     "  r = r & (RunCode(pt, @EcCheckQ, @EcCodeChk) ! $FFFFFFFF)",
     "same argument as M2, one level up."),

    ("M4  ec256 skips the on-curve check entirely", "ec256",
     "  r = r & BnNot(RunCode(pt, @EcCheckQ, @EcCodeChk))",
     "  RunCode(pt, @EcCheckQ, @EcCodeChk)",
     "kill"),

    ("M5  ec256 stops checking the uncompressed prefix", "ec256",
     "  r = r & BnEq(PeekA(src) & 255, $04)",
     "  r = r & 1",
     "kill"),

    ("M6  ec256 accepts a coordinate that is not less than p", "ec256",
     "  borrow = BnSub(@EcRaw2, @EcConstP, 0)\n"
     "  BnReduce(dst, @EcRaw, @EcConstP)\n  ProcedureReturn borrow",
     "  borrow = BnSub(@EcRaw2, @EcConstP, 0)\n"
     "  BnReduce(dst, @EcRaw, @EcConstP)\n  ProcedureReturn 1",
     "kill"),

    ("M7  ec256 reads the point prefix with PeekB, which sign-extends",
     "ec256",
     "  r = r & BnEq(PeekA(src) & 255, $04)",
     "  r = r & BnEq(PeekB(src) & 255, $04)",
     "THE `& 255` IS WHAT SAVES IT. PeekB does sign-extend on this part "
     "- that is shape 2 - but the mask throws the sign back away before "
     "the compare, so the two spellings agree for every byte. Recorded "
     "rather than deleted, because the SAME edit without the mask is "
     "fatal, and a reader needs to see which half is load-bearing."),

    ("M8  ec256's ladder drops the 2-bit window's value-3 addend",
     "ec256",
     "      EcPointCcopy(BnEq(secBits, 3), @EcTpt, @EcP3pt)",
     "      EcPointCcopy(BnEq(secBits, 1), @EcTpt, @EcP3pt)",
     "kill"),

    ("M9  ec256's ladder does one doubling per window, not two", "ec256",
     "      EcPointDouble(@EcQpt)\n      EcPointDouble(@EcQpt)",
     "      EcPointDouble(@EcQpt)",
     "kill"),

    ("M10 ec256's opcode dispatch loses the MMUL b operand", "ec256",
     "    b = op & $0F",
     "    b = (op & $0F) & $0E",
     "kill"),

    ("M11 x25519 loses the RFC 7748 scalar clamp's low bits", "x25519",
     "  PokeB(@SecK + 31, PeekA(@SecK + 31) & $F8)",
     "  PokeB(@SecK + 31, PeekA(@SecK + 31))",
     "kill"),

    ("M12 x25519 loses the clamp's high bit set", "x25519",
     "  PokeB(@SecK + 0, PeekA(@SecK + 0) | $40)",
     "  PokeB(@SecK + 0, PeekA(@SecK + 0))",
     "kill"),

    ("M13 x25519's conditional swap uses the bit, not its mask",
     "x25519",
     "  mask = 0 - ctl",
     "  mask = ctl",
     "kill"),

    ("M14 x25519 does not clear the u coordinate's high bit", "x25519",
     "  PokeB(@XWG + 31, PeekA(@XWG + 31) & $7F)",
     "  PokeB(@XWG + 31, PeekA(@XWG + 31))",
     "NO VECTOR IN THE SHARED SET REACHES IT. RFC 7748 says to mask bit "
     "255 of the u coordinate, and every u in the KAT table and every "
     "random case the generator draws already has that bit clear - the "
     "published KAT u values are canonical. The mask is a conformance "
     "requirement for inputs a PEER can choose, which is exactly the "
     "input a known-answer table does not contain. Reasoning, not a "
     "reproduction, and labelled as such."),

    ("M15 x25519's ladder runs 254 iterations, not 255", "x25519",
     "  i = 254\n  While i >= 0",
     "  i = 253\n  While i >= 0",
     "kill"),

    ("M16 x25519's byteswap stops one byte short", "x25519",
     "  While i < 16\n    t = PeekA(g + i) & 255",
     "  While i < 15\n    t = PeekA(g + i) & 255",
     "kill"),
]


def mutate_source(idx, which, find, replace, harness_text):
    WORK.mkdir(exist_ok=True)
    inc_ec = "RaspberryPi4/Lib/ec256.pi4"
    inc_x = "RaspberryPi4/Lib/x25519.pi4"
    if which == "harness":
        if harness_text.count(find) != 1:
            raise SystemExit("mutation anchor not unique in the harness:\n%r"
                             % find)
        return inc_ec, inc_x, harness_text.replace(find, replace, 1)
    src = EC256 if which == "ec256" else X25519
    text = src.read_text(encoding="utf-8")
    if text.count(find) != 1:
        raise SystemExit("mutation anchor found %d times in %s (want 1):\n%r"
                         % (text.count(find), src.name, find))
    # ONE FILE PER MUTATION.  When the A64 GCM sweep let every mutant of
    # one file share a name, four of them raced, the compiler read a
    # half-written file, and the pool reported four survivors that were
    # nothing of the kind.
    out = WORK / ("ecmut%02d_%s" % (idx, src.name))
    out.write_text(text.replace(find, replace, 1), encoding="utf-8")
    if which == "ec256":
        return "_work/" + out.name, inc_x, harness_text
    return inc_ec, "_work/" + out.name, harness_text


def build_mutant(idx, inc_ec, inc_x, harness_text, img):
    WORK.mkdir(exist_ok=True)
    src = harness_text.replace("__EC256__", inc_ec).replace("__X25519__",
                                                            inc_x)
    hp = WORK / ("echarness_mut%02d.pi4" % idx)
    hp.write_text(src, encoding="utf-8")
    cmd = [str(PMFC), "--compile", str(hp), "-t", "pi4",
           "--load-addr", hex(LOAD), "--stack-addr", hex(STACK),
           "--entry-returns", "-o", str(img)]
    r = subprocess.run(cmd, cwd=ROOT, env=BUILD_ENV, text=True,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if r.returncode != 0 or "pmfc: OK" not in r.stdout:
        raise SystemExit("build failed:\n" + r.stdout)
    return img.stat().st_size


# =====================================================================
#  MAIN
# =====================================================================
def resolve_compiler(requested):
    """Resolve the PureMetal compiler the way tools/build.py does."""
    sys.path.insert(0, str(ROOT / "tools"))
    import build as anvil_build  # noqa: E402
    return anvil_build.find_compiler(requested)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--compiler", default=os.environ.get("PMF_COMPILER"),
                    help="path of PureMetalForge.exe (or set PMF_COMPILER); "
                         "it is run with --compile")
    ap.add_argument("--timing", action="store_true")
    ap.add_argument("--mutate", action="store_true")
    ap.add_argument("--mutation", type=int, default=None)
    ap.add_argument("--iter1000", action="store_true",
                    help="also run the 1000-round RFC 7748 iterated test "
                         "(about 35 billion model instructions)")
    ap.add_argument("--jobs", type=int, default=None)
    args = ap.parse_args(argv)
    globals()["PMFC"] = resolve_compiler(args.compiler)
    globals()["JOBS_CAP"] = args.jobs

    print("[gate] tree under test: %s" % ROOT, file=sys.stderr)
    g = load_tables()
    print("[gate] the vector oracle is anchored to the published "
          "NIST/BearSSL P-256 and RFC 7748 KATs", file=sys.stderr)

    if args.mutation is not None:
        i = args.mutation
        label, which, find, repl, verdict = MUTATIONS[i]
        inc_ec, inc_x, ht = mutate_source(i, which, find, repl, HARNESS)
        img = WORK / ("ec_mut%02d.img" % i)
        try:
            build_mutant(i, inc_ec, inc_x, ht, img)
        except SystemExit as e:
            print("NOBUILD  %s\n         %s" % (label, str(e).splitlines()[0]))
            return 0
        s = build_script(g, level="mutant")
        bad, _ = run_all(img, s, jobs=args.jobs, quiet=True)

        if verdict == "timing":
            if bad:
                print("MISLABELLED %s\n         the vector set caught a "
                      "mutation marked 'timing'" % label)
                return 1
            if timing(img, g, quiet=True) != 0:
                print("KILLED   %s  (by the constant-time check)" % label)
                return 0
            print("SURVIVED %s\n         (a timing-only mutation the "
                  "constant-time check did not see)" % label)
            return 1
        if verdict == "kill":
            if bad:
                print("KILLED   %s\n         first: %s"
                      % (label, bad[0].splitlines()[0]))
                return 0
            print("SURVIVED %s\n         (the vector set was expected to "
                  "catch this one)" % label)
            return 1
        if bad:
            print("UNEXPECTED-KILL %s\n         the vector set now catches "
                  "this, so the recorded argument is stale:\n         %s"
                  % (label, verdict))
            return 1
        print("EXPECTED-SURVIVOR %s" % label)
        return 0

    if args.mutate:
        n = args.jobs or max(1, (os.cpu_count() or 2) - 2)
        print("[gate] %d mutations across %d workers" % (len(MUTATIONS), n))
        t0 = time.time()
        survivors = []
        with concurrent.futures.ThreadPoolExecutor(max_workers=n) as ex:
            futs = {ex.submit(subprocess.run,
                              [sys.executable, __file__, "--mutation",
                               str(i), "--jobs", "1",
                               "--compiler", str(PMFC)],
                              cwd=ROOT, env=BUILD_ENV,
                              capture_output=True, text=True): i
                    for i in range(len(MUTATIONS))}
            for f in concurrent.futures.as_completed(futs):
                i = futs[f]
                r = f.result()
                sys.stdout.write(r.stdout)
                if r.returncode != 0:
                    sys.stdout.write(r.stderr)
                    survivors.append(MUTATIONS[i][0])
        expected = sum(1 for m in MUTATIONS if m[4] not in ("kill", "timing"))
        print("[gate] sweep took %.0f s" % (time.time() - t0))
        if survivors:
            print("MUTATION SWEEP RED: %d unexpected outcome(s):\n  %s"
                  % (len(survivors), "\n  ".join(survivors)))
            return 1
        print("MUTATION SWEEP GREEN: 0 unexpected outcomes of %d "
              "(%d of them are EXPECTED survivors, each with its recorded "
              "argument in the table)" % (len(MUTATIONS), expected))
        return 0

    s = build_script(g, iter1000=args.iter1000)
    img = WORK / "echarness.img"
    size = build("RaspberryPi4/Lib/ec256.pi4", "RaspberryPi4/Lib/x25519.pi4",
                 WORK / "echarness.pi4", img)
    print("[gate] image %d bytes, %d jobs" % (size, len(s)))
    t0 = time.time()
    bad, steps = run_all(img, s, jobs=args.jobs)
    for b in bad:
        print("FAIL: " + b)
    nneg = sum(1 for j in s.jobs if j[1] == OP_NEG)
    print("[gate] %d jobs (%d of them invalid points that must be refused), "
          "%d model instructions, %.0f s"
          % (len(s), nneg, steps, time.time() - t0))
    if bad:
        print("EC GATE RED: %d of %d jobs wrong" % (len(bad), len(s)))
        return 1
    if args.timing:
        rc = timing(img, g)
        if rc:
            return rc
    print("EC GATE GREEN: %d jobs on the shared P-256 and X25519 vector "
          "set, %d invalid points refused, the %s-round RFC 7748 iterated "
          "test passed, %d model instructions"
          % (len(s), nneg, "1000" if args.iter1000 else "1", steps))
    return 0


if __name__ == "__main__":
    sys.exit(main())
