; ======================================================================
;  crypto - the known-answer self-test for every crypto module, ON THE
;           BOARD, at the monitor's own prompt
; ======================================================================
;
;  WHY THIS EXISTS AT ALL, when the desktop gates are more thorough and
;  always will be.
;
;  Every crypto module in this tree is gated hard by tools/a64/*, and
;  every one of those runs happened inside tools/a64/a64_interp.py,
;  WHICH IS A MODEL. The standing rule is that if the board is attached,
;  the gate runs on the board - and the reason is not speed. An emulator
;  agrees with itself. On the day that rule was written, a silicon run
;  of the Pico's own self-test found FOUR failures that had passed under
;  emulation, two of them the exact reverse of what the author predicted.
;
;  What the model cannot have is the part: a real memory system with the
;  MMU off, where every access is Device-nGnRnE and an unaligned wide
;  one is a silent runaway; real caches, real timing, a real branch
;  predictor; and a compiler bug that the emulator and the code
;  generator SHARE, which no amount of emulator running can find.
;
;  THE ONE VERDICT THAT ONLY SILICON CAN SETTLE is the GCM forgery.
;  The 32-bit families end GcmDecrypt with `>> 31` to smear a sign bit
;  into a mask. On this target the sign bit is bit 63, and that spelling
;  returns $FFFFFFFF00000000 for a BAD tag - which is not zero, so every
;  caller that asks "is the verdict non-zero" accepts a forged tag,
;  while a caller that truncates to 32 bits sees a clean refusal. Both
;  spellings exist in this tree. This file tests the verdict AT FULL
;  WIDTH, against the exact mask, on both a good tag and a forged one,
;  and the forgery must come back exactly zero.
;
; ======================================================================
;  NOT ONE VECTOR HERE IS TYPED
; ======================================================================
;
;  Anvil/Core/cryptotest_vectors.pbi is GENERATED by
;  tools/gen_pi4_crypto_selftest.py, which reads every byte out of a
;  published document or out of a generator that already gates this tree
;  on the desktop - RFC 3174, RFC 2202, RFC 4231, RFC 5869, RFC 6070,
;  RFC 3394, FIPS-197 appendix C, the NIST CAVP KAT files, and the
;  NIST/McGrew GCM table that tools/a64/a64_gcm_check.py imports.
;
;  That is the whole point of the file. The board diagnostic this one
;  supersedes, RaspberryPi4/Examples/Diagnostics/pi4AesSelfTest.pi4,
;  says out loud that its vectors are TRANSCRIBED - "exactly the failure
;  mode the desktop gates avoid by construction" - and
;  tools/a64/a64_keywrap_check.py grew a whole extra pass whose only job
;  is to catch a mistyped digit in it. A mistyped digit on a board fails
;  on silicon, looks like a silicon problem, and is not one.
;
; ======================================================================
;  WHAT IT PRINTS
; ======================================================================
;
;    module   id  verdict                         ticks
;    sha256    0  PASS                                61
;    gcm      11  PASS  forged tag REFUSED          4,912
;
;  ONE LINE PER VECTOR, always, pass or fail, because a self-test that
;  prints only failures cannot be distinguished from one that did not
;  run. The tick column is CNTPCT_EL0, the architectural counter, read
;  either side of the module call and nothing else - 54 MHz on this
;  part, so one tick is 18.5 ns.
;
;  A FAILURE IS A FULL SENTENCE WITH ITS CODE, never a bare number, and
;  it names the first thing to check. That is the house rule and it is
;  worth more here than anywhere: a crypto failure on a board is a thing
;  somebody will read six months later with no context at all.
;
;  THE THROUGHPUT LINES ARE A SEPARATE JOB from the vectors and are
;  reported as such. They are the number the model literally cannot
;  produce: bytes per second of AES-CTR, AES-GCM and SHA-256 over a
;  64 KB buffer on a real Cortex-A72.
;
; ======================================================================
;  WHAT IT IS GATED ON: NOTHING
; ======================================================================
;
;  No clock, no display, no storage, no radio, no interrupt. Every
;  module here is pure computation over buffers in .bss. The command
;  cannot hang a bus, cannot leave a peripheral in a state, and works on
;  a board with nothing attached but the serial console. The only board
;  facility it touches besides the console is CNTPCT_EL0, and a stopped
;  counter costs it the tick column and nothing else - see CryTicksOk.
;
;  It is, like Anvil/Core/hash_cmd.pbi, a Core command file that only
;  the Pi 4 board includes today, because the modules it drives live
;  under RaspberryPi4/Lib. A second AArch64 board that grows those
;  libraries includes this file and gets the command with no edit here.
;
;  IT ALLOCATES NO MEMORY AND TOUCHES NO ADDRESS THE OPERATOR TYPED, so
;  there is no AddrAllowed call in this file and that is not an
;  oversight - the address-safety seam exists for commands that take an
;  address from the operator, and this one takes none.
;
;  ANY KEYSTROKE STOPS IT, between vectors, and a stopped run says so
;  and prints no verdict line - the same ruling crc32 and sha256sum
;  follow, for the same reason: a partial sweep that looks like a whole
;  one is the failure this project refuses hardest.
;
; ======================================================================
;  WHY EVERY FIELD IS COPIED INTO A BUFFER FIRST
; ======================================================================
;
;  The vectors could be read straight out of the image by address, and
;  that would be faster. They are copied into .bss arrays instead
;  because with the MMU off every data access on this part is
;  Device-nGnRnE and an unaligned wide one is a SILENT RUNAWAY, not a
;  fault - and a DataSection byte stream puts a field at whatever offset
;  the field before it ended at. A global array is aligned. The copy is
;  a few thousand byte moves per vector and buys the whole class of
;  problem away.
;
;  The buffer sizes come from the generator - #CRY_MAX_A .. #CRY_MAX_F
;  are the largest field of each slot over the whole table - so a vector
;  that outgrows a buffer cannot be added by regenerating: the buffer
;  grows with it, in the same edit, and CryLoad's size check is a second
;  belt that can only fire if the generated file and this one were built
;  from different trees.
; ======================================================================

; ----------------------------------------------------------------------
;  The failure codes. Each is printed WITH its sentence, never alone,
;  so that an old transcript still matches a search for the number.
; ----------------------------------------------------------------------
#CRY_E_SIZE    = 1     ; a field is bigger than the buffer sized for it
#CRY_E_MODULE  = 2     ; a module id no version of this file knows
#CRY_E_REFUSED = 3     ; the module refused a vector it must accept
#CRY_E_BYTES   = 4     ; the output differs from the published answer
#CRY_E_SPLIT   = 5     ; one shot and byte-at-a-time disagree
#CRY_E_ROUND   = 6     ; the inverse did not recover the input
#CRY_E_VERDICT = 7     ; a GOOD tag was not accepted at full width
#CRY_E_FORGED  = 8     ; a FORGED tag was accepted - the 64-bit trap
#CRY_E_TAG     = 9     ; the tag differs from the published answer
; ---- part two, the public-key half. Four of its seven modules answer
; with a VERDICT rather than with bytes, so they need codes of their own:
; "the answer is wrong" and "the answer is the OTHER answer" are not the
; same failure and must not print the same sentence.
#CRY_E_ACCEPT  = 10    ; an input that MUST be refused was ACCEPTED
#CRY_E_REJECT  = 11    ; a published, valid input was refused
#CRY_E_CANNOT  = 12    ; a curve the module cannot compute answered a
                       ; verdict instead of -1
#CRY_E_LASTERR = 13    ; the verdict is right and the diagnostic code is not
#CRY_E_CODE    = 14    ; the refusal is real but it is the WRONG refusal
#CRY_E_SENT    = 15    ; a refusal returned 0 and wrote to the buffer anyway
#CRY_E_STEP    = 16    ; a bounds-guard step answered wrong
#CRY_E_NOKEY   = 17    ; the chain validated and handed back no key

; The three verdict conventions that now live in one crypto family on
; this part. THEY ARE NOT INTERCHANGEABLE AND THIS IS THE FILE THAT SAYS
; SO IN CODE: GcmDecrypt returns a MASK, the signature modules return a
; FLAG, the certificate seam returns a flag PLUS -1, and X509 returns a
; CODE in which 62 and 32 are both non-zero. A caller that tests any of
; them for "non-zero" is wrong in a different way each time.
#CRY_V_ZERO    = 0     ; must be exactly 0
#CRY_V_ONE     = 1     ; must be exactly 1
#CRY_V_MINUS1  = 2     ; must be exactly -1, at FULL 64-bit width

; The good-tag verdict GcmDecrypt returns. A MASK, not a boolean, and
; it is tested at FULL WIDTH - see the header. $FFFFFFFF is positive on
; a 64-bit .i, so this compares as an ordinary number.
#CRY_GOOD_TAG  = $FFFFFFFF

; The throughput buffer. 64 KB is 1024 SHA-256 blocks and 4096 AES
; blocks - long enough that the per-call setup is noise and short enough
; that the run is instant on the part and merely slow in the model.
#CRY_SPEED_MAX = 65536

; ----------------------------------------------------------------------
;  The buffers. Every one is .bss, so none of this is in the image.
; ----------------------------------------------------------------------
Global Dim cryA.a[#CRY_MAX_A]        ; key / message / salt / seed / kek
Global Dim cryB.a[#CRY_MAX_B]        ; message / iv / key data / reseed
Global Dim cryC.a[#CRY_MAX_C]        ; info / aad / plaintext
Global Dim cryD.a[#CRY_MAX_D]        ; prk / plaintext
Global Dim cryE.a[#CRY_MAX_E]        ; THE EXPECTED OUTPUT, always
Global Dim cryF.a[#CRY_MAX_F]        ; the expected tag
Global Dim cryOut.a[#CRY_MAX_E]      ; what the board computed
Global Dim cryTmp.a[#CRY_MAX_E]      ; discard / recovered plaintext
Global Dim cryTag.a[16]              ; the tag the board computed
Global Dim cryTagF.a[16]             ; that tag with one bit flipped
Global Dim crySpeedA.a[#CRY_SPEED_MAX]
Global Dim crySpeedB.a[#CRY_SPEED_MAX]
; A key and an IV of their own for the throughput run. They could be the
; first bytes of the buffer and the first draft did exactly that, which
; works and reads like a mistake - a reader has to stop and work out
; whether the plaintext is being used as its own key.
Global Dim crySpeedKey.a[32]
Global Dim crySpeedIv.a[16]

; ---- part two's working buffers, all .bss, none of it in the image ---
; The i15 arrays are declared .u BECAUSE THAT DECLARATION IS LOAD-BEARING
; - a big-integer buffer is an array of 16-bit words on every family and
; a .i buffer is mutation M1 in the desktop gate. The word counts come
; from the generator (#CRY_BN_MWORDS / #CRY_BN_XWORDS) for the same
; reason #CRY_MAX_A..F do: a vector that outgrows a buffer cannot be
; added by regenerating, because the buffer grows with it in that edit.
Global Dim cryBnM.u[#CRY_BN_MWORDS]    ; the modulus
Global Dim cryBnX.u[#CRY_BN_XWORDS]
Global Dim cryBnY.u[#CRY_BN_XWORDS]
Global Dim cryBnD.u[#CRY_BN_XWORDS]
Global Dim cryBnT1.u[#CRY_BN_XWORDS]
Global Dim cryBnT2.u[#CRY_BN_XWORDS]
Global Dim cryHash.a[32]               ; SHA-256 of an RSA record's message
; THE CALLER'S ARRAY-OF-CELLS CONTRACT, in the one place on this board
; that exercises it. X509ValidateChain walks these with #X_CELL, which
; is 8 here; a .l or .n array compiles and is wrong, and that is exactly
; the defect the port found in x509.pi4 - element 0 came back right and
; element 1 straddled two cells. Declared .i, and passed by address.
Global Dim cryX5Certs.i[8]
Global Dim cryX5Lens.i[8]

Global cryMod.i                      ; the record now loaded
Global cryVid.i
Global cryLA.i
Global cryLB.i
Global cryLC.i
Global cryLD.i
Global cryLE.i
Global cryLF.i
Global cryParam.i

Global cryChecks.i                   ; the running totals for one sweep
Global cryPasses.i
Global cryFails.i
Global cryForgeries.i                ; forged tags refused, counted apart
Global cryRefusals.i                 ; every negative refused, ditto
Global cryTicksOk.i                  ; 0 if CNTPCT_EL0 is not moving

; ----------------------------------------------------------------------
;  CryMeta(i, k) - field k of meta record i.
;
;  PeekL SIGN-EXTENDS since the unsigned-ladder ruling. Every field here
;  is a length, an id or an offset and none can reach bit 31, so the
;  extension cannot bite - but the masking is written anyway because
;  "cannot reach bit 31" is a property of today's table and the mask
;  costs one instruction.
; ----------------------------------------------------------------------
Procedure.i CryMeta(i.i, k.i)
  ProcedureReturn PeekL(?CryVecMeta + i * #CRY_META_STRIDE + k * 4) & $FFFFFFFF
EndProcedure

; ----------------------------------------------------------------------
;  CryCopy(dst, src, n) - n bytes, byte at a time. No wide moves, for
;  the alignment reason in the header: src is inside the image at
;  whatever offset the previous field ended at.
; ----------------------------------------------------------------------
Procedure CryCopy(dst.i, src.i, n.i)
  Define i.i
  i = 0
  While i < n
    PokeB(dst + i, PeekA(src + i) & 255)
    i = i + 1
  Wend
EndProcedure

; ----------------------------------------------------------------------
;  CryDiff(got, want, n) - 0 if the n bytes match, else 1 + the index of
;  the FIRST byte that differs, so the caller can name it.
;
;  NOT constant time and it does not need to be: both sides are public
;  test data. The constant-time compare that matters is CtEqual in
;  hmac.pi4 and the tag compare inside GcmDecrypt, and those are gated
;  by tools/ct_ab.py on the desktop, where the model is deterministic
;  and a part with caches is not.
; ----------------------------------------------------------------------
Procedure.i CryDiff(got.i, want.i, n.i)
  Define i.i
  i = 0
  While i < n
    If (PeekA(got + i) & 255) <> (PeekA(want + i) & 255)
      ProcedureReturn i + 1
    EndIf
    i = i + 1
  Wend
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  CryLE16 / CryLE32 / CryLE32s / CryLE64 - read a little-endian field
;  out of a loaded slot, ONE BYTE AT A TIME.
;
;  Never a wide load. The field starts wherever the previous field
;  ended, so its address is arbitrary, and with the MMU off an unaligned
;  wide access on this part is a SILENT RUNAWAY rather than a fault -
;  the same reason CryCopy exists. The cost is a few instructions in a
;  path that then runs a scalar multiply.
; ----------------------------------------------------------------------
Procedure.i CryLE16(p.i, off.i)
  ProcedureReturn (PeekA(p + off) & 255) | ((PeekA(p + off + 1) & 255) << 8)
EndProcedure

Procedure.i CryLE32(p.i, off.i)
  ProcedureReturn (PeekA(p + off) & 255) | ((PeekA(p + off + 1) & 255) << 8) | ((PeekA(p + off + 2) & 255) << 16) | ((PeekA(p + off + 3) & 255) << 24)
EndProcedure

Procedure.i CryLE32s(p.i, off.i)
  ; Sign-extended from bit 31, spelled as the mask-and-subtract rather
  ; than as a shift, because on a 64-bit .i the sign bit is bit 63 and
  ; `>> 31` is the shape that made GcmDecrypt accept a forged tag.
  ProcedureReturn (CryLE32(p, off) ! $80000000) - $80000000
EndProcedure

Procedure.i CryLE64(p.i, off.i)
  Define v.i
  Define i.i
  v = 0
  i = 7
  While i >= 0
    v = (v << 8) | (PeekA(p + off + i) & 255)
    i = i - 1
  Wend
  ProcedureReturn v
EndProcedure

; ----------------------------------------------------------------------
;  CryModName(m) - the module's name, printed directly.
;
;  Printed rather than held as a pointer for the same reason
;  hash_cmd.pi4's PutAlgoName is: a pointer to a string LITERAL is not
;  something @ can take in this language.
; ----------------------------------------------------------------------
Procedure CryModName(m.i)
  If m = #CRY_MOD_SHA256
    Print("sha256  ")
  ElseIf m = #CRY_MOD_SHA1
    Print("sha1    ")
  ElseIf m = #CRY_MOD_HMAC
    Print("hmac    ")
  ElseIf m = #CRY_MOD_HMACSHA1
    Print("hmacsha1")
  ElseIf m = #CRY_MOD_HKDF
    Print("hkdf    ")
  ElseIf m = #CRY_MOD_PBKDF2
    Print("pbkdf2  ")
  ElseIf m = #CRY_MOD_DRBG
    Print("drbg    ")
  ElseIf m = #CRY_MOD_AES
    Print("aes     ")
  ElseIf m = #CRY_MOD_AESCTR
    Print("aes-ctr ")
  ElseIf m = #CRY_MOD_GCM
    Print("gcm     ")
  ElseIf m = #CRY_MOD_KEYWRAP
    Print("keywrap ")
  ElseIf m = #CRY_MOD_BIGNUM
    Print("bignum  ")
  ElseIf m = #CRY_MOD_P256
    Print("p256    ")
  ElseIf m = #CRY_MOD_X25519
    Print("x25519  ")
  ElseIf m = #CRY_MOD_ECDSA
    Print("ecdsa   ")
  ElseIf m = #CRY_MOD_RSA
    Print("rsa     ")
  ElseIf m = #CRY_MOD_T0VM
    Print("t0vm    ")
  ElseIf m = #CRY_MOD_X509
    Print("x509    ")
  Else
    Print("?       ")
  EndIf
EndProcedure

; ----------------------------------------------------------------------
;  CryFail(code, at) - the failure sentence.
;
;  THE SHAPE IS THE HOUSE SHAPE: what failed, at what code, what the
;  code means in one clause, the raw value, and the first thing to
;  check. `at` is the byte index the comparison stopped at, or a raw
;  return value, depending on the code; every branch says which.
; ----------------------------------------------------------------------
Procedure CryFail(code.i, at.i)
  cryFails = cryFails + 1
  PrintN("FAIL")
  Print("     !! ")
  If code = #CRY_E_SIZE
    Print("this vector does not fit at code 1 (SIZE): a field of ")
    PrintDec(at)
    PrintN(" bytes")
    PrintN("        is larger than the buffer this image sized for that slot.")
    PrintN("        Check that Anvil/Core/cryptotest_vectors.pbi and this image were")
    PrintN("        built from the same tree - #CRY_MAX_A..F come from the generator")
    PrintN("        and the buffers are declared from them, so they can only differ")
    PrintN("        if the two files came from different checkouts.")
  ElseIf code = #CRY_E_MODULE
    Print("the vector table names module ")
    PrintDec(at)
    PrintN(" at code 2 (MODULE), which")
    PrintN("        no branch in this image knows how to run. Check that")
    PrintN("        Anvil/Core/cryptotest_vectors.pbi was regenerated by a newer")
    PrintN("        tools/gen_pi4_crypto_selftest.py than the crypto_cmd.pi4 beside it.")
  ElseIf code = #CRY_E_REFUSED
    PrintN("the module REFUSED a published vector at code 3 (REFUSED): it")
    Print("        returned ")
    PrintDec(at)
    PrintN(" where a success is required. Nothing was compared.")
    PrintN("        Check the key or output length this vector uses against the")
    PrintN("        refusal rules in the module's header - a legal length the module")
    PrintN("        rejects is a defect in the module, not in the vector.")
  ElseIf code = #CRY_E_BYTES
    Print("the answer is WRONG at code 4 (BYTES): byte ")
    PrintDec(at - 1)
    PrintN(" of the output")
    PrintN("        differs from the published one. The vector came out of a document")
    PrintN("        or a second implementation, so suspect the module first. Run the")
    PrintN("        desktop gate for it and compare: if the model agrees with the")
    PrintN("        document and the board does not, that is a SILICON result and it")
    PrintN("        is the headline - do not change the vector.")
  ElseIf code = #CRY_E_SPLIT
    Print("streaming disagrees with one shot at code 5 (SPLIT): byte ")
    PrintDec(at - 1)
    PrintN("")
    PrintN("        differs when the same message is fed one byte at a time. The")
    PrintN("        one-shot answer was right, so the digest itself is fine and the")
    PrintN("        BUFFERING is not. Check the partial-block tail in the module's")
    PrintN("        Update, and its byte counter.")
  ElseIf code = #CRY_E_ROUND
    Print("the inverse did not recover the input at code 6 (ROUND): byte ")
    PrintDec(at - 1)
    PrintN("")
    PrintN("        of the recovered value differs from what went in, while the")
    PrintN("        forward direction was byte-exact. Check the decrypt or unwrap")
    PrintN("        half of the module; the encrypt half is proven by the line above.")
  ElseIf code = #CRY_E_VERDICT
    PrintN("a GOOD tag was NOT accepted at code 7 (VERDICT): the verdict is")
    Print("        $")
    PutHex16(at)
    PrintN(" and the whole 64-bit value must be $00000000FFFFFFFF.")
    PrintN("        Read that value at full width before anything else: if its low 32")
    PrintN("        bits look right, the verdict line is smearing bit 63 instead of")

    ; THE NEXT LINE NAMES A PROCEDURE AND NOT A FILE, AND IT IS FORUM 575.
    ; It read "see the danger note in RaspberryPi4/Lib/gcm.pi4" until
    ; 2026-09-05. This file is in the SHARED CORE - only the Pi 4 includes
    ; it today, which is exactly why the line survived - so on the second
    ; board to grow a GCM library the monitor would have sent whoever was
    ; standing at the prompt off to read another computer's source tree.
    ; GcmDecrypt is what the note is about and every board's copy has one.
    PrintN("        bit 31. See the danger note above GcmDecrypt in the GCM library.")
  ElseIf code = #CRY_E_FORGED
    PrintN("A FORGED TAG WAS ACCEPTED at code 8 (FORGED): one bit of the tag")
    Print("        was flipped and the verdict came back $")
    PutHex16(at)
    PrintN(" instead of 0.")
    PrintN("        THIS IS THE FAILURE THIS COMMAND EXISTS FOR. Any caller that tests")
    PrintN("        the verdict for non-zero now accepts forged ciphertext. Check")
    PrintN("        GcmDecrypt's last two lines: on a 64-bit .i the sign bit is bit 63,")
    PrintN("        so the 32-bit families' `>> 31` returns $FFFFFFFF00000000 here.")
  ElseIf code = #CRY_E_TAG
    Print("the tag is WRONG at code 9 (TAG): byte ")
    PrintDec(at - 1)
    PrintN(" of the authentication")
    PrintN("        tag differs from the published one, although the ciphertext may")
    PrintN("        not. Check GHASH - the cipher and the MAC are separate here, and a")
    PrintN("        right ciphertext with a wrong tag points at GhBmul32 or the length")
    PrintN("        block, not at AES.")
  ElseIf code = #CRY_E_ACCEPT
    PrintN("AN INPUT THAT MUST BE REFUSED WAS ACCEPTED at code 10 (ACCEPT):")
    Print("        the verdict came back ")
    PrintDec(at)
    PrintN(" where 0 was required. This vector is")
    PrintN("        a NEGATIVE - an off-curve point, a coordinate that is not less")
    PrintN("        than p, a forged signature, a malformed encoding - and accepting")
    PrintN("        it is the failure that leaks a key or trusts a forgery. Check the")
    PrintN("        refusal the vector's note names; do not change the vector.")
  ElseIf code = #CRY_E_REJECT
    PrintN("A PUBLISHED, VALID INPUT WAS REFUSED at code 11 (REJECT): the")
    Print("        verdict came back ")
    PrintDec(at)
    PrintN(" where 1 was required. The vector came")
    PrintN("        out of a document or a second implementation, so suspect the")
    PrintN("        module. If the desktop gate for it is green, the disagreement is")
    PrintN("        between the model and the part and THAT is the result.")
  ElseIf code = #CRY_E_CANNOT
    PrintN("A CURVE THIS MODULE CANNOT COMPUTE ANSWERED A VERDICT at code 12")
    Print("        (CANNOT): it returned ")
    PrintDec(at)
    PrintN(" where -1 was required. Zero means")
    PrintN("        THIS SIGNATURE IS BAD, and saying that about a curve the module")
    PrintN("        does not implement is a wrong answer wearing a verdict's clothes.")
    PrintN("        Check EcdsaVrfy's curve gate and EcdsaLastErr = 2.")
  ElseIf code = #CRY_E_LASTERR
    Print("the verdict is right and the diagnostic code is not, at code 13")
    PrintN("")
    Print("        (LASTERR): EcdsaLastErr came back ")
    PrintDec(at)
    PrintN(". 0 is valid, 1 rejected,")
    PrintN("        2 curve unsupported, 3 encoding malformed. A malformed encoding")
    PrintN("        must be refused BY THE ENCODING WALK and not stumbled over by the")
    PrintN("        arithmetic afterwards, and those two are identical in the return")
    PrintN("        value - this code is the only thing that tells them apart.")
  ElseIf code = #CRY_E_CODE
    Print("the WRONG refusal at code 14 (CODE): the chain was refused with ")
    PrintDec(at)
    PrintN("")
    PrintN("        and the vector requires a different one. A validator that answers")
    PrintN("        the wrong non-OK code still looks like a working validator to a")
    PrintN("        caller that only asks whether it failed, which is why the NAME of")
    PrintN("        every refusal is checked here and not merely that one happened.")
    PrintN("        32 OK, 35 empty chain, 49 unsupported, 51 wrong key type,")
    PrintN("        52 bad signature, 53 time unknown, 54 expired, 55 DN mismatch,")
    PrintN("        56 bad server name, 58 not CA, 60 weak key, 62 not trusted,")
    PrintN("        199 run guard, 200 the signature seam is not linked.")
  ElseIf code = #CRY_E_SENT
    Print("a refusal returned 0 and WROTE ANYWAY at code 15 (SENTINEL): byte ")
    PrintDec(at - 1)
    PrintN("")
    PrintN("        of the recovery buffer is no longer the $A5 it was filled with.")
    PrintN("        With no public key installed every entry point must refuse AND")
    PrintN("        leave the caller's buffer alone; a refusal that scribbles is a")
    PrintN("        different defect from a wrong verdict and it hides behind one.")
    PrintN("        Check RsaPublic's length refusal, which must come first.")
  ElseIf code = #CRY_E_STEP
    Print("the bounds guard answered wrong at code 16 (STEP): step ")
    PrintDec(at)
    PrintN(" of the")
    PrintN("        table disagrees. Every step's legality is decided by one line in")
    PrintN("        this board's t0vm library - an access of n bytes at addr is legal")
    PrintN("        exactly when 0 <= addr <= #T0_RAM_SIZE - n - and the expectations")
    PrintN("        were computed from that line, not from a run. A refused write")
    PrintN("        must not land, a refused read must answer 0, and t0_err must be")
    PrintN("        #T0ERR_RAM_BOUNDS. This is forum 517.")
  ElseIf code = #CRY_E_NOKEY
    PrintN("the chain validated and handed back NO KEY at code 17 (NOKEY):")
    PrintN("        X509ValidateChain answered #X509ERR_OK and X509EePkeyType is 0.")
    PrintN("        OK with no end-entity key is not a validated chain - the caller")
    PrintN("        would go on to use a key that was never decoded. Check the")
    PrintN("        X509EePkey* globals at the end of the walk.")
  Else
    Print("the self-test failed at code ")
    PrintDec(code)
    Print(", value ")
    PrintDec(at)
    PrintN(", and this image has no")
    PrintN("        sentence for that code, which is itself a defect in crypto_cmd.pi4.")
  EndIf
EndProcedure

; ----------------------------------------------------------------------
;  CryLoad(i) - copy record i's fields into the aligned buffers.
;  Returns 0 if a field does not fit, having printed nothing.
; ----------------------------------------------------------------------
Procedure.i CryLoad(i.i)
  Define p.i

  cryMod   = CryMeta(i, 0)
  cryVid   = CryMeta(i, 1)
  cryLA    = CryMeta(i, 2)
  cryLB    = CryMeta(i, 3)
  cryLC    = CryMeta(i, 4)
  cryLD    = CryMeta(i, 5)
  cryLE    = CryMeta(i, 6)
  cryLF    = CryMeta(i, 7)
  cryParam = CryMeta(i, 8)
  p        = ?CryVecData + CryMeta(i, 9)

  If cryLA > #CRY_MAX_A : ProcedureReturn 0 - cryLA : EndIf
  If cryLB > #CRY_MAX_B : ProcedureReturn 0 - cryLB : EndIf
  If cryLC > #CRY_MAX_C : ProcedureReturn 0 - cryLC : EndIf
  If cryLD > #CRY_MAX_D : ProcedureReturn 0 - cryLD : EndIf
  If cryLE > #CRY_MAX_E : ProcedureReturn 0 - cryLE : EndIf
  If cryLF > #CRY_MAX_F : ProcedureReturn 0 - cryLF : EndIf

  CryCopy(@cryA[0], p, cryLA) : p = p + cryLA
  CryCopy(@cryB[0], p, cryLB) : p = p + cryLB
  CryCopy(@cryC[0], p, cryLC) : p = p + cryLC
  CryCopy(@cryD[0], p, cryLD) : p = p + cryLD
  CryCopy(@cryE[0], p, cryLE) : p = p + cryLE
  CryCopy(@cryF[0], p, cryLF)
  ProcedureReturn 1
EndProcedure

; ----------------------------------------------------------------------
;  The eleven runners. Each writes its answer into cryOut and returns
;  0 for a pass or a failure code; the failing detail goes into
;  cryFailAt so the caller can print one sentence in one place.
; ----------------------------------------------------------------------
Global cryFailAt.i

Procedure.i CryRunSha256()
  Define i.i
  Define d.i
  Sha256Of(@cryA[0], cryLA, @cryOut[0])
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  ; AND THE SAME MESSAGE ONE BYTE AT A TIME. A split point that changes
  ; the answer is a buffering defect the one-shot path cannot show.
  Sha256Begin()
  i = 0
  While i < cryLA
    Sha256Update(@cryA[0] + i, 1)
    i = i + 1
  Wend
  Sha256End(@cryTmp[0])
  d = CryDiff(@cryTmp[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_SPLIT
  EndIf
  ProcedureReturn 0
EndProcedure

Procedure.i CryRunSha1()
  Define i.i
  Define d.i
  ; param is the repeat count from RFC 3174's own driver table: the unit
  ; in slot a, fed that many times. A repeat of 1 is the ordinary case.
  Sha1Begin()
  i = 0
  While i < cryParam
    Sha1Update(@cryA[0], cryLA)
    i = i + 1
  Wend
  Sha1End(@cryOut[0])
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  If cryParam = 1
    Sha1Begin()
    i = 0
    While i < cryLA
      Sha1Update(@cryA[0] + i, 1)
      i = i + 1
    Wend
    Sha1End(@cryTmp[0])
    d = CryDiff(@cryTmp[0], @cryE[0], cryLE)
    If d <> 0
      cryFailAt = d
      ProcedureReturn #CRY_E_SPLIT
    EndIf
  EndIf
  ProcedureReturn 0
EndProcedure

Procedure.i CryRunHmac()
  Define i.i
  Define d.i
  Define r.i
  HmacKey(@cryA[0], cryLA)
  HmacBegin()
  HmacUpdate(@cryB[0], cryLB)
  r = HmacEnd(@cryOut[0], cryLE)
  If r <> cryLE
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  HmacBegin()
  i = 0
  While i < cryLB
    HmacUpdate(@cryB[0] + i, 1)
    i = i + 1
  Wend
  HmacEnd(@cryTmp[0], cryLE)
  d = CryDiff(@cryTmp[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_SPLIT
  EndIf
  ProcedureReturn 0
EndProcedure

Procedure.i CryRunHmacSha1()
  Define i.i
  Define d.i
  Define r.i
  HmacSha1Key(@cryA[0], cryLA)
  HmacSha1Begin()
  HmacSha1Update(@cryB[0], cryLB)
  r = HmacSha1End(@cryOut[0], cryLE)
  If r <> cryLE
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  HmacSha1Begin()
  i = 0
  While i < cryLB
    HmacSha1Update(@cryB[0] + i, 1)
    i = i + 1
  Wend
  HmacSha1End(@cryTmp[0], cryLE)
  d = CryDiff(@cryTmp[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_SPLIT
  EndIf
  ProcedureReturn 0
EndProcedure

Procedure.i CryRunHkdf()
  Define d.i
  Define r.i
  ; Extract first, and the PRK is checked on its own - RFC 5869 publishes
  ; it, and a wrong PRK with a right OKM is not possible while a right
  ; PRK with a wrong OKM is, so checking both localises a failure.
  HkdfExtract(@cryA[0], cryLA, @cryB[0], cryLB, @cryTmp[0])
  d = CryDiff(@cryTmp[0], @cryD[0], cryLD)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  r = HkdfExpand(@cryTmp[0], cryLD, @cryC[0], cryLC, @cryOut[0], cryLE)
  If r <= 0
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  ProcedureReturn 0
EndProcedure

Procedure.i CryRunPbkdf2()
  Define d.i
  Define r.i
  r = Pbkdf2Sha1(@cryA[0], cryLA, @cryB[0], cryLB, cryParam, @cryOut[0], cryLE)
  If r <= 0
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  ProcedureReturn 0
EndProcedure

Procedure.i CryRunDrbg()
  Define d.i
  Define r.i
  ; The NIST CAVP KAT's own call order: instantiate, reseed if the vector
  ; has reseed material, generate once and DISCARD, generate again and
  ; keep. The discard is not an accident of the vector - the CAVP KAT
  ; returns the SECOND generate, and a DRBG that ignored its own state
  ; update would pass on the first.
  ; #DRBG_WARN_SHORT_SEED IS NOT A REFUSAL AND MUST NOT BE READ AS ONE.
  ; It means "instantiated, but with fewer than #DRBG_SEED_STRENGTH
  ; bytes of seed" - the generator's random cases start at 16 bytes, so
  ; several of these vectors get it, and every one of them is a vector
  ; the DRBG is required to produce the published output for. Only
  ; #DRBG_ERR_* (-2 and below) means nothing was instantiated.
  r = DrbgInit(@cryA[0], cryLA)
  If r <> #DRBG_OK And r <> #DRBG_WARN_SHORT_SEED
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  If cryLB > 0
    r = DrbgReseed(@cryB[0], cryLB)
    If r <> #DRBG_OK And r <> #DRBG_WARN_SHORT_SEED
      cryFailAt = r
      ProcedureReturn #CRY_E_REFUSED
    EndIf
  EndIf
  r = DrbgGenerate(@cryTmp[0], cryLE)
  If r <= 0
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  r = DrbgGenerate(@cryOut[0], cryLE)
  If r <= 0
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  ProcedureReturn 0
EndProcedure

Procedure.i CryRunAes()
  Define d.i
  Define r.i
  r = AesSetKey(@cryA[0], cryLA)
  If r = 0
    cryFailAt = cryLA
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  AesEncryptBlock(@cryB[0], @cryOut[0])
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  ; AND BACK. aes.pi4 carries the inverse cipher because RFC 3394 key
  ; unwrap needs it; the CAVP files publish only the forward direction,
  ; so the round trip is what gates the decrypt half here.
  AesDecryptBlock(@cryE[0], @cryTmp[0])
  d = CryDiff(@cryTmp[0], @cryB[0], cryLB)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_ROUND
  EndIf
  ProcedureReturn 0
EndProcedure

Procedure.i CryRunAesCtr()
  Define d.i
  Define r.i
  r = AesCtrInit(@cryA[0], cryLA)
  If r = 0
    cryFailAt = cryLA
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  r = AesCtrRun(@cryB[0], @cryC[0], @cryOut[0], cryLC)
  If r < 0
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  ; CTR IS ITS OWN INVERSE, so running the ciphertext back through it
  ; must give the plaintext. That is free and it catches an in-place
  ; aliasing defect the forward direction cannot.
  r = AesCtrRun(@cryB[0], @cryOut[0], @cryTmp[0], cryLC)
  d = CryDiff(@cryTmp[0], @cryC[0], cryLC)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_ROUND
  EndIf
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  GCM - the one that matters most, and the only runner with a NEGATIVE
;  test in it. cryForge is set to 1 when the forged tag was correctly
;  refused, so the caller can say so on the line and count them.
; ----------------------------------------------------------------------
Global cryForge.i

Procedure.i CryRunGcm()
  Define d.i
  Define r.i
  Define v.i
  Define i.i

  cryForge = 0

  ; AesWipe first, so a refused key cannot be rescued by the key the
  ; PREVIOUS vector left installed - the same reason the desktop gate's
  ; harness wipes between records.
  AesWipe()

  r = GcmInit(@cryA[0], cryLA)
  If r = 0
    cryFailAt = cryLA
    ProcedureReturn #CRY_E_REFUSED
  EndIf

  GcmEncrypt(@cryB[0], cryLB, @cryC[0], cryLC, @cryD[0], cryLD, @cryOut[0], @cryTag[0])
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  d = CryDiff(@cryTag[0], @cryF[0], 16)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_TAG
  EndIf

  ; The honest decrypt. THE VERDICT IS A MASK AND IT IS TESTED AT FULL
  ; WIDTH - never "is it non-zero". See the header.
  v = GcmDecrypt(@cryB[0], cryLB, @cryC[0], cryLC, @cryE[0], cryLE, @cryTmp[0], @cryF[0])
  If v <> #CRY_GOOD_TAG
    cryFailAt = v
    ProcedureReturn #CRY_E_VERDICT
  EndIf
  d = CryDiff(@cryTmp[0], @cryD[0], cryLD)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_ROUND
  EndIf

  ; THE FORGERY. One bit of one tag byte, at the position the generator
  ; chose for this vector - it alternates between byte 0 and byte 15,
  ; because a tag compare that stops early is invisible while every
  ; forgery flips the same byte.
  i = 0
  While i < 16
    cryTagF[i] = cryF[i]
    i = i + 1
  Wend
  i = cryParam
  If i < 0 Or i > 15
    i = 0
  EndIf
  cryTagF[i] = cryTagF[i] ! 1
  v = GcmDecrypt(@cryB[0], cryLB, @cryC[0], cryLC, @cryE[0], cryLE, @cryTmp[0], @cryTagF[0])
  If v <> 0
    cryFailAt = v
    ProcedureReturn #CRY_E_FORGED
  EndIf
  cryForge = 1
  cryForgeries = cryForgeries + 1
  ProcedureReturn 0
EndProcedure

Procedure.i CryRunKeywrap()
  Define d.i
  Define r.i
  r = KwWrap(@cryA[0], cryLA, @cryB[0], cryLB, @cryOut[0])
  If r <> cryLE
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  r = KwUnwrap(@cryA[0], cryLA, @cryE[0], cryLE, @cryTmp[0])
  If r <> cryLB
    cryFailAt = r
    ProcedureReturn #CRY_E_REFUSED
  EndIf
  d = CryDiff(@cryTmp[0], @cryB[0], cryLB)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_ROUND
  EndIf
  ProcedureReturn 0
EndProcedure

; ======================================================================
;  PART TWO - THE PUBLIC-KEY RUNNERS
; ======================================================================
;  Seven more, and they differ from the eleven above in one way that is
;  worth stating once rather than in every procedure: FOUR OF THEM
;  ANSWER WITH A VERDICT AND NOT WITH BYTES. There is nothing to
;  byte-compare in "this signature is invalid"; there is only a number,
;  and the number has to be checked at full 64-bit width against an
;  exact value, never for non-zero. That is the part-one lesson arriving
;  in a second family: GcmDecrypt's `>> 31` returned $FFFFFFFF00000000
;  for a forged tag, which is not zero, and every caller that asked
;  "is it non-zero" accepted the forgery.
;
;  The three conventions in play here, all of them live in this image:
;    EcdsaVrfyRaw / EcdsaVrfyAsn1 / RsaVrfy / RsaPkcs1Vrfy / RsaPssVrfy
;    / EcP256Mul          a FLAG - test = 1
;    EcdsaVrfy            a flag PLUS -1 - a caller that tests non-zero
;                         accepts -1, which means it treats "I cannot
;                         compute this curve" as "valid"
;    X509ValidateChain    a CODE - test = #X509ERR_OK (32). 62 is also
;                         non-zero and it means NOT TRUSTED.
; ======================================================================

; ----------------------------------------------------------------------
;  bignum - the i15 core, through the public API only.
;
;  The modulus is DECODED HERE rather than carried in the table as
;  limbs: BnDecode computes the announced length and BnNinv15 computes
;  m0i, so the board derives both the way a caller does. A table that
;  carried them would be testing the generator's arithmetic instead of
;  the module's.
; ----------------------------------------------------------------------
Procedure.i CryRunBignum()
  Define m0i.i
  Define d.i
  Define r.i

  BnDecode(@cryBnM[0], @cryA[0], cryLA)
  ; BnNinv15 TAKES THE MODULUS'S LOW 15-BIT LIMB, NOT THE MODULUS.
  ;
  ; This line read `BnNinv15(@cryBnM[0])` and handed it an ADDRESS. The
  ; board found it: every REDUCE and BnDecodeReduce vector passed and
  ; every MONTMUL, MODPOW and MODPOW2 vector failed - 14 of 24 - which
  ; is exactly the set of operations that use m0i and exactly the set
  ; that does not. The address of a `.u` array is even, and BnNinv15
  ; ends `BnMux(x & 1, 0 - y, 0)`, so m0i came back 0 every time: not a
  ; wrong inverse, no inverse at all, deterministically.
  ;
  ; The library was never in doubt and the board said so in the same
  ; pass: rsa.pi4 (`BnNinv15(BnGw(@RsaM, 1))`) verified 24 of 24 at
  ; 2048, 3072 and 4096 bits, and ecdsa.pi4 (`BnGw(@EcdsaN, 1)`) 51 of
  ; 51 - both of them straight through BnModpow and BnMontmul. The
  ; defect was in this runner, which is why the desk gate could not see
  ; it: a64_bignum_check.py builds its own harness and calls this
  ; correctly, so the two disagree only here.
  m0i = BnNinv15(BnGw(@cryBnM[0], 1))

  If cryParam = 1
    ; MONTMUL. BnMontmul computes x*y/R mod m, so one operand is lifted
    ; into the Montgomery domain first and the product comes back in the
    ; ordinary one - which is what the shared table's expectation is.
    ; This is the shape the DERIVED full-limb modulus exists to stress:
    ; with R/m = 1 the final conditional subtraction fires on about a
    ; fifth of operands instead of once in sixteen thousand.
    BnDecodeReduce(@cryBnX[0], @cryB[0], cryLB, @cryBnM[0])
    BnDecodeReduce(@cryBnY[0], @cryC[0], cryLC, @cryBnM[0])
    BnToMonty(@cryBnX[0], @cryBnM[0])
    BnMontmul(@cryBnD[0], @cryBnX[0], @cryBnY[0], @cryBnM[0], m0i)
    BnEncode(@cryOut[0], cryLE, @cryBnD[0])
  ElseIf cryParam = 2
    BnDecodeReduce(@cryBnX[0], @cryB[0], cryLB, @cryBnM[0])
    BnModpow(@cryBnX[0], @cryC[0], cryLC, @cryBnM[0], m0i, @cryBnT1[0], @cryBnT2[0])
    BnEncode(@cryOut[0], cryLE, @cryBnX[0])
  ElseIf cryParam = 3
    BnDecode(@cryBnY[0], @cryB[0], cryLB)
    BnReduce(@cryBnX[0], @cryBnY[0], @cryBnM[0])
    BnEncode(@cryOut[0], cryLE, @cryBnX[0])
  ElseIf cryParam = 4
    BnDecodeReduce(@cryBnX[0], @cryB[0], cryLB, @cryBnM[0])
    BnEncode(@cryOut[0], cryLE, @cryBnX[0])
  ElseIf cryParam = 5
    BnDecodeReduce(@cryBnX[0], @cryB[0], cryLB, @cryBnM[0])
    r = BnModpow2(@cryBnX[0], @cryC[0], cryLC, @cryBnM[0], m0i, @cryBnT1[0], #CRY_BN_XWORDS)
    If r = 0
      cryFailAt = 0
      ProcedureReturn #CRY_E_REFUSED
    EndIf
    BnEncode(@cryOut[0], cryLE, @cryBnX[0])
  Else
    cryFailAt = cryParam
    ProcedureReturn #CRY_E_MODULE
  EndIf

  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  p256 - EcP256Mulgen, EcP256Mul, the same call used as ECDH, and the
;  five points that must be REFUSED.
;
;  EcP256Mul works IN PLACE on the caller's 65-byte point, so the input
;  is copied into cryOut first and the answer replaces it. The negatives
;  are the half this module exists for: an off-curve point, a wrong
;  uncompressed prefix, a coordinate that is not less than p, the
;  origin, and the derived X = p with Y = sqrt(b) - the one encoding on
;  this curve whose reduction IS on the curve, so the coordinate range
;  test is the only thing left that can refuse it.
; ----------------------------------------------------------------------
Procedure.i CryRunP256()
  Define r.i
  Define d.i
  Define i.i

  EcInit()

  If cryParam = 1
    r = EcP256Mulgen(@cryOut[0], @cryB[0], cryLB)
    If r <> cryLE
      cryFailAt = r
      ProcedureReturn #CRY_E_REFUSED
    EndIf
  Else
    i = 0
    While i < cryLA
      cryOut[i] = cryA[i]
      i = i + 1
    Wend
    r = EcP256Mul(@cryOut[0], cryLA, @cryB[0], cryLB)

    If cryParam = 4
      ; A NEGATIVE. Exactly 0, at full width, and nothing else.
      If r <> 0
        cryFailAt = r
        ProcedureReturn #CRY_E_ACCEPT
      EndIf
      ProcedureReturn 0
    EndIf

    If r <> 1
      cryFailAt = r
      ProcedureReturn #CRY_E_REJECT
    EndIf
    If cryParam = 3
      ; ECDH hands the caller the X coordinate only, which is bytes
      ; 1..32 of the point the multiply left behind.
      i = 0
      While i < cryLE
        cryOut[i] = cryOut[i + 1]
        i = i + 1
      Wend
    EndIf
  EndIf

  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  x25519 - RFC 7748, including the DERIVED case with the scalar's bit
;  254 cleared. Every published scalar already has that bit set, so the
;  clamp's `or` is a no-op on all of them; with the bit cleared a
;  correct library puts it back and returns the published answer
;  unchanged, and one that has lost the clamp runs a different ladder.
; ----------------------------------------------------------------------
Procedure.i CryRunX25519()
  Define d.i
  X25519Init()
  X25519(@cryOut[0], @cryA[0], @cryB[0])
  d = CryDiff(@cryOut[0], @cryE[0], cryLE)
  If d <> 0
    cryFailAt = d
    ProcedureReturn #CRY_E_BYTES
  EndIf
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  ecdsa - all three entry points, the verdict AND EcdsaLastErr.
;
;  EcdsaLastErr IS PART OF THE CONTRACT, not a debug aid. A malformed
;  encoding and a bad signature are the same return value, and only this
;  code separates "the encoding walk refused it" from "the arithmetic
;  stumbled over it afterwards".
;
;  EcdsaInit() is deliberately NOT called: every entry point
;  self-initialises, and this file's first ecdsa vector is therefore a
;  cold verify, which is the same job the desktop gate makes job 0 of
;  every shard.
; ----------------------------------------------------------------------
Procedure.i CryRunEcdsa()
  Define kind.i
  Define wantv.i
  Define wanterr.i
  Define curve.i
  Define v.i
  Define want.i

  kind    = cryParam & 255
  wantv   = (cryParam >> 8) & 255
  wanterr = (cryParam >> 16) & 255
  curve   = (cryParam >> 24) & 255

  If kind = 1
    v = EcdsaVrfyRaw(@cryB[0], cryLB, @cryA[0], cryLA, @cryC[0], cryLC)
  ElseIf kind = 2
    v = EcdsaVrfy(curve, @cryB[0], cryLB, @cryA[0], cryLA, @cryC[0], cryLC)
  ElseIf kind = 3
    v = EcdsaVrfyAsn1(@cryB[0], cryLB, @cryA[0], cryLA, @cryC[0], cryLC)
  Else
    cryFailAt = kind
    ProcedureReturn #CRY_E_MODULE
  EndIf

  want = 0
  If wantv = #CRY_V_ONE
    want = 1
  ElseIf wantv = #CRY_V_MINUS1
    want = 0 - 1
  EndIf

  If v <> want
    cryFailAt = v
    If wantv = #CRY_V_MINUS1
      ProcedureReturn #CRY_E_CANNOT
    ElseIf wantv = #CRY_V_ONE
      ProcedureReturn #CRY_E_REJECT
    EndIf
    ProcedureReturn #CRY_E_ACCEPT
  EndIf

  If EcdsaLastErr <> wanterr
    cryFailAt = EcdsaLastErr
    ProcedureReturn #CRY_E_LASTERR
  EndIf
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  rsa - PKCS#1 v1.5, PSS, the certificate seam, and the forgotten
;  setup step.
;
;  RsaSetPubKey COMES FIRST, BEFORE EVERY VERIFY, and it copies nothing:
;  both pointers must stay valid until the verify returns, which is why
;  the key is read out of the loaded buffers rather than out of the
;  image. Four arguments fewer than every other family, because this
;  backend passes eight and refuses a ninth.
;
;  The last record of the module installs a ZERO key and requires all
;  three entry points to refuse AND to leave the recovery buffer alone.
;  That is the claim rsa.pi4's header makes in prose - "forgetting is
;  safe rather than silent" - measured instead of asserted.
; ----------------------------------------------------------------------
Procedure.i CryRunRsa()
  Define kind.i
  Define expect.i
  Define saltlen.i
  Define v.i
  Define v2.i
  Define d.i
  Define i.i

  kind    = cryParam & 255
  expect  = (cryParam >> 8) & 255
  saltlen = (cryParam >> 16) & 255

  If kind = 4
    i = 0
    While i < 32
      cryOut[i] = $A5
      i = i + 1
    Wend
    RsaSetPubKey(0, 0, 0, 0)
    v = RsaVrfy(@cryC[0], cryLC, RsaOidSha256(), 32, @cryOut[0])
    v2 = RsaPkcs1Vrfy(@cryC[0], cryLC, RsaOidSha256(), 32, @cryHash[0])
    v2 = v2 + RsaPssVrfy(@cryC[0], cryLC, @cryHash[0], 32, saltlen)
    If v <> 0 Or v2 <> 0
      cryFailAt = v + v2
      ProcedureReturn #CRY_E_ACCEPT
    EndIf
    d = CryDiff(@cryOut[0], @cryE[0], 32)
    If d <> 0
      cryFailAt = d
      ProcedureReturn #CRY_E_SENT
    EndIf
    ProcedureReturn 0
  EndIf

  RsaSetPubKey(@cryA[0], cryLA, @cryB[0], cryLB)
  Sha256Of(@cryD[0], cryLD, @cryHash[0])

  If kind = 0
    v = RsaPkcs1Vrfy(@cryC[0], cryLC, RsaOidSha256(), 32, @cryHash[0])
  ElseIf kind = 1
    v = RsaPssVrfy(@cryC[0], cryLC, @cryHash[0], 32, saltlen)
  ElseIf kind = 2
    i = 0
    While i < 32
      cryOut[i] = 0
      i = i + 1
    Wend
    v = RsaVrfy(@cryC[0], cryLC, RsaOidSha256(), 32, @cryOut[0])
  Else
    cryFailAt = kind
    ProcedureReturn #CRY_E_MODULE
  EndIf

  If expect = 0
    If v <> 0
      cryFailAt = v
      ProcedureReturn #CRY_E_ACCEPT
    EndIf
    ProcedureReturn 0
  EndIf

  If v <> 1
    cryFailAt = v
    ProcedureReturn #CRY_E_REJECT
  EndIf
  If kind = 2 And cryLE > 0
    ; The seam RECOVERS the signed hash for the caller to compare, so
    ; this record has bytes as well as a verdict and both are checked.
    ; A seam that returns 1 and recovers the wrong hash is a validator
    ; that trusts the wrong certificate.
    d = CryDiff(@cryOut[0], @cryE[0], cryLE)
    If d <> 0
      cryFailAt = d
      ProcedureReturn #CRY_E_BYTES
    EndIf
  EndIf
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  t0vm - forum 517's RAM bounds guard and the 64-bit cell contract.
;
;  The steps are a table, not a written-out sequence, and the
;  expectations were computed from the guard's own contract by the
;  generator: an access of n bytes at addr is legal exactly when
;  0 <= addr <= #T0_RAM_SIZE - n. Widths 2 and 4 go through the VM's own
;  primitives (the data stack, then T0PrimMem) rather than through a
;  private path, because it is the primitives a T0 program reaches.
;
;  WHAT THIS DOES NOT COVER, said out loud: the desktop gate also runs
;  the SHARED PEM DECODER BYTECODE over three real certificates. This
;  family has no copy of that blob, so the interpreter is proven here by
;  the x509 module below, which drives the same VM over the x509
;  bytecode on every chain it validates.
; ----------------------------------------------------------------------
Procedure.i CryRunT0vm()
  Define n.i
  Define i.i
  Define p.i
  Define op.i
  Define w.i
  Define addr.i
  Define val.i
  Define res.i

  n = cryLA / 12
  i = 0
  While i < n
    p = @cryA[0] + i * 12
    op = PeekA(p) & 255
    w = PeekA(p + 1) & 255
    addr = CryLE32s(@cryA[0], i * 12 + 4)
    val = CryLE32(@cryA[0], i * 12 + 8)
    res = 0

    If op = 0
      t0_err = 0
      t0_ip = 0
      t0_dp = 0
    ElseIf op = 1
      t0_dp = 0
      T0Push(val)
      T0Push(addr)
      If w = 1
        T0PrimMem(#T0OP_SET8)
      ElseIf w = 2
        T0PrimMem(#T0OP_SET16)
      Else
        T0PrimMem(#T0OP_SET32)
      EndIf
    ElseIf op = 2
      t0_dp = 0
      T0Push(addr)
      If w = 1
        T0PrimMem(#T0OP_GET8)
      ElseIf w = 2
        T0PrimMem(#T0OP_GET16)
      Else
        T0PrimMem(#T0OP_GET32)
      EndIf
      res = T0Pop()
    ElseIf op = 3
      res = T0Norm(val)
    Else
      cryFailAt = op
      ProcedureReturn #CRY_E_MODULE
    EndIf

    If res <> CryLE64(@cryE[0], i * 16)
      cryFailAt = i
      ProcedureReturn #CRY_E_STEP
    EndIf
    If t0_err <> CryLE64(@cryE[0], i * 16 + 8)
      cryFailAt = i
      ProcedureReturn #CRY_E_STEP
    EndIf
    i = i + 1
  Wend

  t0_err = 0
  t0_ip = 0
  t0_dp = 0
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  x509 - a real chain verifies and a tampered one is refused BY NAME.
;
;  The slots, because this module needs more scalars than `param` holds:
;    a  every certificate's DER, in chain order, end-entity first
;    b  their lengths, one unsigned 16-bit little-endian each
;    c  a 16-byte header: unixTime (i64), serverLen (i32), anchor type,
;       isCA, curve, anchor count
;    d  the anchors, each u16 dnLen || dn || u16 aLen || a || u16 bLen
;       || b  (a is the modulus or the point, b the RSA exponent)
;    e  ONE BYTE, the expected #X509ERR_* code
;    f  the server name, empty when serverLen is negative
;    param  the certificate count
;
;  THE UNIX TIME IS A FULL 64-BIT FIELD and one of the cases is
;  4,070,908,800, which is past 2^31. A 32-bit field would have made
;  that case answer the wrong question - and it is an EXPIRED case, so
;  it would have looked like it passed.
; ----------------------------------------------------------------------
Procedure.i CryRunX509()
  Define n.i
  Define i.i
  Define off.i
  Define utime.i
  Define srvlen.i
  Define srvp.i
  Define atype.i
  Define isca.i
  Define curve.i
  Define nanch.i
  Define dnlen.i
  Define dnp.i
  Define alen.i
  Define ap.i
  Define blen.i
  Define bp.i
  Define code.i
  Define want.i

  n      = cryParam
  utime  = CryLE64(@cryC[0], 0)
  srvlen = CryLE32s(@cryC[0], 8)
  atype  = PeekA(@cryC[0] + 12) & 255
  isca   = PeekA(@cryC[0] + 13) & 255
  curve  = PeekA(@cryC[0] + 14) & 255
  nanch  = PeekA(@cryC[0] + 15) & 255

  If n > 8
    cryFailAt = n
    ProcedureReturn #CRY_E_SIZE
  EndIf

  X509ResetAnchors()
  off = 0
  i = 0
  While i < nanch
    dnlen = CryLE16(@cryD[0], off) : off = off + 2
    dnp   = @cryD[0] + off         : off = off + dnlen
    alen  = CryLE16(@cryD[0], off) : off = off + 2
    ap    = @cryD[0] + off         : off = off + alen
    blen  = CryLE16(@cryD[0], off) : off = off + 2
    bp    = @cryD[0] + off         : off = off + blen
    If atype = 2
      X509AddAnchorEC(isca, dnp, dnlen, curve, ap, alen)
    ElseIf atype = 1
      X509AddAnchorRSA(isca, dnp, dnlen, ap, alen, bp, blen)
    Else
      cryFailAt = atype
      ProcedureReturn #CRY_E_MODULE
    EndIf
    i = i + 1
  Wend

  off = 0
  i = 0
  While i < n
    cryX5Certs[i] = @cryA[0] + off
    cryX5Lens[i] = CryLE16(@cryB[0], i * 2)
    off = off + cryX5Lens[i]
    i = i + 1
  Wend

  srvp = 0
  If srvlen >= 0
    srvp = @cryF[0]
  EndIf

  code = X509ValidateChain(@cryX5Certs[0], @cryX5Lens[0], n, srvp, srvlen, utime)
  want = PeekA(@cryE[0]) & 255

  If code <> want
    cryFailAt = code
    ProcedureReturn #CRY_E_CODE
  EndIf
  If want = #X509ERR_OK And X509EePkeyType = 0
    cryFailAt = 0
    ProcedureReturn #CRY_E_NOKEY
  EndIf
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  CryDispatch() - run whichever module the loaded record names.
; ----------------------------------------------------------------------
Procedure.i CryDispatch()
  If cryMod = #CRY_MOD_SHA256
    ProcedureReturn CryRunSha256()
  ElseIf cryMod = #CRY_MOD_SHA1
    ProcedureReturn CryRunSha1()
  ElseIf cryMod = #CRY_MOD_HMAC
    ProcedureReturn CryRunHmac()
  ElseIf cryMod = #CRY_MOD_HMACSHA1
    ProcedureReturn CryRunHmacSha1()
  ElseIf cryMod = #CRY_MOD_HKDF
    ProcedureReturn CryRunHkdf()
  ElseIf cryMod = #CRY_MOD_PBKDF2
    ProcedureReturn CryRunPbkdf2()
  ElseIf cryMod = #CRY_MOD_DRBG
    ProcedureReturn CryRunDrbg()
  ElseIf cryMod = #CRY_MOD_AES
    ProcedureReturn CryRunAes()
  ElseIf cryMod = #CRY_MOD_AESCTR
    ProcedureReturn CryRunAesCtr()
  ElseIf cryMod = #CRY_MOD_GCM
    ProcedureReturn CryRunGcm()
  ElseIf cryMod = #CRY_MOD_KEYWRAP
    ProcedureReturn CryRunKeywrap()
  ElseIf cryMod = #CRY_MOD_BIGNUM
    ProcedureReturn CryRunBignum()
  ElseIf cryMod = #CRY_MOD_P256
    ProcedureReturn CryRunP256()
  ElseIf cryMod = #CRY_MOD_X25519
    ProcedureReturn CryRunX25519()
  ElseIf cryMod = #CRY_MOD_ECDSA
    ProcedureReturn CryRunEcdsa()
  ElseIf cryMod = #CRY_MOD_RSA
    ProcedureReturn CryRunRsa()
  ElseIf cryMod = #CRY_MOD_T0VM
    ProcedureReturn CryRunT0vm()
  ElseIf cryMod = #CRY_MOD_X509
    ProcedureReturn CryRunX509()
  EndIf
  cryFailAt = cryMod
  ProcedureReturn #CRY_E_MODULE
EndProcedure

; ----------------------------------------------------------------------
;  CryPutTicks(t) - the tick column, right-ish aligned.
;
;  A STOPPED COUNTER PRINTS A DASH RATHER THAN A ZERO, because a zero is
;  a measurement and a dash is not, and a table of zeroes read six
;  months later would be read as "instant" rather than as "unmeasured".
; ----------------------------------------------------------------------
Procedure CryPutTicks(t.i)
  Define w.i
  Define n.i
  If cryTicksOk = 0
    Print("        -")
    ProcedureReturn
  EndIf
  ; How many digits, so the column lines up without a formatter.
  n = 1
  w = t
  While w >= 10
    w = w / 10
    n = n + 1
  Wend
  w = 9 - n
  While w > 0
    Print(" ")
    w = w - 1
  Wend
  PrintDec(t)
EndProcedure

; ----------------------------------------------------------------------
;  CryOneVector(i) - load, run, time and report record i.
;  Returns 0 for a pass.
; ----------------------------------------------------------------------
Procedure.i CryOneVector(i.i)
  Define t0.i
  Define t1.i
  Define r.i

  cryChecks = cryChecks + 1
  r = CryLoad(i)
  If r <= 0
    cryMod = CryMeta(i, 0)
    cryVid = CryMeta(i, 1)
    CryModName(cryMod)
    Print(" ")
    PrintDec(cryVid)
    Print("  ")
    CryFail(#CRY_E_SIZE, 0 - r)
    ProcedureReturn #CRY_E_SIZE
  EndIf

  CryModName(cryMod)
  Print(" ")
  If cryVid < 10
    Print(" ")
  EndIf
  PrintDec(cryVid)
  Print("  ")

  t0 = Ticks()
  r = CryDispatch()
  t1 = Ticks()

  If r <> 0
    CryFail(r, cryFailAt)
    ProcedureReturn r
  EndIf

  cryPasses = cryPasses + 1
  Print("PASS")
  ; The annotation column. A NEGATIVE THAT PASSES IS A REFUSAL, and a
  ; transcript that prints it as a bare PASS reads as though the board
  ; accepted something. Every one of them says so on its own line, and
  ; they are counted apart in the totals for the same reason the forged
  ; GCM tags are.
  If cryMod = #CRY_MOD_GCM
    cryRefusals = cryRefusals + 1
    Print("  forged tag REFUSED")
  ElseIf cryMod = #CRY_MOD_P256 And cryParam = 4
    cryRefusals = cryRefusals + 1
    Print("  invalid point REFUSED")
  ElseIf cryMod = #CRY_MOD_ECDSA And ((cryParam >> 8) & 255) = #CRY_V_ZERO
    cryRefusals = cryRefusals + 1
    Print("  signature REFUSED ")
  ElseIf cryMod = #CRY_MOD_ECDSA And ((cryParam >> 8) & 255) = #CRY_V_MINUS1
    Print("  answered -1, not 0")
  ElseIf cryMod = #CRY_MOD_RSA And (cryParam & 255) = 4
    Print("  refused, wrote none")
  ElseIf cryMod = #CRY_MOD_RSA And ((cryParam >> 8) & 255) = 0
    cryRefusals = cryRefusals + 1
    Print("  signature REFUSED ")
  ElseIf cryMod = #CRY_MOD_X509 And (PeekA(@cryE[0]) & 255) <> #X509ERR_OK
    cryRefusals = cryRefusals + 1
    Print("  chain REFUSED, ")
    PrintDec(PeekA(@cryE[0]) & 255)
    Print("  ")
  ElseIf cryMod = #CRY_MOD_X25519 And cryParam = 1
    Print("  DERIVED clamp case ")
  Else
    Print("                    ")     ; the same width, so the column lines up
  EndIf
  CryPutTicks(t1 - t0)
  PrintNl()
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  CryTickCheck() - is CNTPCT_EL0 moving at all?
;
;  Asked ONCE per sweep and answered by looking, not by assuming. A
;  counter no loader programmed reads zero for ever, and every tick
;  column would then be a zero that looks like a measurement.
; ----------------------------------------------------------------------
Procedure CryTickCheck()
  Define a.i
  Define b.i
  Define n.i
  cryTicksOk = 0
  a = Ticks()
  n = 0
  While n < 2000
    n = n + 1
  Wend
  b = Ticks()
  If b > a
    cryTicksOk = 1
  EndIf
EndProcedure

; ----------------------------------------------------------------------
;  CryptoSelfTestAll(only) - the sweep.
;
;  `only` is a module id, or 0 for every module. Returns the number of
;  FAILURES, so a caller - including the desktop gate, which enters this
;  procedure by its symbol with no monitor around it - gets the verdict
;  as a number and does not have to parse the transcript for it.
; ----------------------------------------------------------------------
Procedure.i CryptoSelfTestAll(only.i)
  Define i.i
  Define m.i

  cryChecks = 0
  cryPasses = 0
  cryFails = 0
  cryForgeries = 0
  cryRefusals = 0
  CryTickCheck()

  i = 0
  While i < #CRY_VEC_COUNT
    m = CryMeta(i, 0)
    If only = 0 Or only = m
      If OutBreak() <> 0
        PrintN("   stopped part way, so THERE IS NO VERDICT. A self-test that ran")
        PrintN("   part of its vectors and printed a total looks exactly like one")
        PrintN("   that ran all of them.")
        ProcedureReturn 0 - 1
      EndIf
      CryOneVector(i)
    EndIf
    i = i + 1
  Wend

  ; EVERY KEY IS WIPED ON THE WAY OUT. Nothing here is a real credential
  ; - every one came out of a published document - but a monitor that
  ; left a key schedule installed after a self-test would leave the NEXT
  ; caller encrypting under it, and aes.pi4's own header says the caller
  ; decides when a key stops being needed.
  AesWipe()
  GcmWipe()
  KwWipe()
  Pbkdf2Wipe()
  ; ...and the public-key side. RsaSetPubKey copies nothing, so what it
  ; leaves installed is a pair of pointers INTO THE BUFFERS THIS SWEEP IS
  ; about to reuse. A later caller that forgot its own RsaSetPubKey would
  ; then verify against whatever landed there, which is a worse failure
  ; than refusing: it is a wrong ANSWER rather than no answer. Zeroed, so
  ; the length refusal fires instead.
  RsaSetPubKey(0, 0, 0, 0)
  X509ResetAnchors()

  ProcedureReturn cryFails
EndProcedure

; ----------------------------------------------------------------------
;  The throughput run. THE ONE NUMBER THE MODEL CANNOT PRODUCE.
;
;  A tick is 1/CNTFRQ_EL0 seconds - 18.5 ns on this part. Bytes per
;  second is bytes * hz / ticks, and the multiply is done first: 65536 *
;  54000000 is about 3.5e12, which is nothing to a 64-bit .i, while
;  dividing first would throw the answer away.
;
;  THE BUFFER IS FILLED, NOT LEFT AS ZEROES. An all-zero plaintext is a
;  fine input for AES and a bad habit to print a number for; and a
;  bitsliced cipher's cost does not depend on its data, which is the
;  property the constant-time gate exists to prove, so the fill costs
;  nothing but honesty.
;
;  IT DOES NOT PRINT THE ARM CLOCK, AND THAT IS DELIBERATE. Bytes per
;  second is a complete answer on its own; cycles per byte would need
;  ClockMeasuredHz(), which is a MAILBOX transaction, and one mailbox
;  read would end this command's "touches nothing but the console"
;  property - the property that lets it run on a board with nothing
;  attached and lets the desk gate refuse all unmodelled MMIO. Type
;  `clock` beside it; the bench driver captures both into the same
;  transcript for exactly this reason.
; ----------------------------------------------------------------------
Procedure CrySpeedLine(n.i, ticks.i, hz.i)
  Define bps.i
  Print("  ")
  PrintDec(n)
  Print(" bytes in ")
  PrintDec(ticks)
  Print(" ticks")
  If cryTicksOk = 0 Or ticks <= 0 Or hz <= 0
    PrintN("   - no rate: the counter is not moving, so there is")
    PrintN("     nothing to divide by. The byte count above is still real.")
    ProcedureReturn
  EndIf
  Print(" (")
  PrintDec(ticks * 1000000 / hz)
  Print(" us), ")
  bps = n * hz / ticks
  ; THE UNIT CHANGES BELOW A KILOBYTE A SECOND, AND IT HAS TO.
  ;
  ; `bps / 1024` is an integer divide, so anything slower than 1024
  ; bytes a second prints `0 KB/s` - a working module reporting a rate
  ; of zero, which is exactly the silently-wrong number this project
  ; forbids. It went unnoticed while this run measured three fast
  ; modules and the board found it the first time it measured eleven:
  ; **RFC 3394 key wrap over 64 KB with the caches off is 95.5 seconds,
  ; 686 bytes a second**, because six passes over the semiblocks is
  ; about 49,000 single AES blocks against uncached DRAM. That is a
  ; real and interesting number and it was being printed as 0.
  ;
  ; The alternative - a fixed unit with a fraction - needs float
  ; formatting in a monitor that deliberately has none in this path.
  If bps < 1024
    PrintDec(bps)
    PrintN(" bytes/s")
  Else
    PrintDec(bps / 1024)
    PrintN(" KB/s")
  EndIf
EndProcedure

; ----------------------------------------------------------------------
;  CryPbkdf2Line() - the one throughput row that is not bytes a second,
;  because for this module bytes a second is a lie.
;
;  PBKDF2 EXISTS TO BE SLOW. Its output is 32 bytes and its cost is its
;  iteration count, so a rate in KB/s prints 0 for a function that is
;  working perfectly - a number that reads as a broken measurement and
;  is not one. What is reported instead is the wall time of the
;  derivation and the PRF rate underneath it, which is the figure that
;  actually answers "how long does this board take to join a network".
;
;  32 bytes at 20 bytes a block is CEIL(32/20) = two blocks, and each
;  block costs `iters` HMAC-SHA-1 calls (RFC 2898 section 5.2), so the
;  PRF count is 2 * iters. It is computed rather than written out
;  because the iteration count is not fixed - see the note on scaling
;  in CryptoSpeedRun.
; ----------------------------------------------------------------------
Procedure CryPbkdf2Line(iters.i, ticks.i, hz.i)
  Print("  32 bytes in ")
  PrintDec(ticks)
  Print(" ticks")
  If cryTicksOk = 0 Or ticks <= 0 Or hz <= 0
    PrintN("   - no rate: the counter is not moving, so there is")
    PrintN("     nothing to divide by. The derivation itself still happened.")
    ProcedureReturn
  EndIf
  Print(" (")
  PrintDec(ticks * 1000 / hz)
  Print(" ms), ")
  PrintDec(2 * iters * hz / ticks)
  PrintN(" HMAC-SHA-1 calls a second")
EndProcedure

; ----------------------------------------------------------------------
;  CryPickVector(m, p16, la) - load the FIRST record of module m whose
;  low 16 param bits are p16 and, when la is non-zero, whose slot a is
;  exactly la bytes. Returns 1 when a record was loaded.
;
;  The part-two throughput rows time a REAL VECTOR out of the table
;  rather than a synthetic input, so a rate on this board is a rate for
;  an operation the board has just been seen to get right on the line
;  above. The alternative - a made-up key and a made-up point - would
;  time a computation nothing had checked.
; ----------------------------------------------------------------------
Procedure.i CryPickVector(m.i, p16.i, la.i)
  Define i.i
  i = 0
  While i < #CRY_VEC_COUNT
    If CryMeta(i, 0) = m And (CryMeta(i, 8) & $FFFF) = p16
      If la = 0 Or CryMeta(i, 2) = la
        If CryLoad(i) > 0
          ProcedureReturn 1
        EndIf
      EndIf
    EndIf
    i = i + 1
  Wend
  ProcedureReturn 0
EndProcedure

; ----------------------------------------------------------------------
;  CryOpsLine(ops, ticks, hz) - the public-key throughput unit.
;
;  BYTES A SECOND IS MEANINGLESS FOR A SIGNATURE. What a caller wants to
;  know is how many verifications a second a TLS handshake can afford
;  and how long one costs, so the row is operations a second and
;  microseconds each - and when the part is slower than one operation a
;  second, which it is for a P-256 multiply with the caches off, the
;  rate would round to zero. That is the exact defect the board found in
;  this file's other rate line, so this one prints the per-operation
;  time first and never lets the rate be the only number.
; ----------------------------------------------------------------------
Procedure CryOpsLine(ops.i, ticks.i, hz.i)
  Define us.i
  Print("  ")
  PrintDec(ops)
  Print(" in ")
  PrintDec(ticks)
  Print(" ticks")
  If cryTicksOk = 0 Or ticks <= 0 Or hz <= 0 Or ops <= 0
    PrintN("   - no rate: the counter is not moving, so there is")
    PrintN("     nothing to divide by. The operation count above is still real.")
    ProcedureReturn
  EndIf
  us = ticks * 1000000 / hz / ops
  Print(" - ")
  PrintDec(us)
  Print(" us each, ")
  If us >= 1000000
    PrintDec(us / 1000000)
    PrintN(" s per operation")
  ElseIf us > 0
    PrintDec(1000000 / us)
    PrintN(" per second")
  Else
    PrintN("faster than this counter can time one")
  EndIf
EndProcedure

; ----------------------------------------------------------------------
;  CryptoSpeedRun2() - the public-key half's throughput.
;
;  ONE LINE PER MODULE, and every one of them runs the SAME runner the
;  vector sweep ran, on a record the sweep has already answered. So the
;  cost measured is the whole operation a caller pays for - the RSA row
;  includes hashing the message, the X.509 row includes installing the
;  anchor and parsing both certificates - rather than the inner loop
;  with its setup taken out, which is the number that flatters.
;
;  THE ITERATION COUNTS ARE SMALL, AND FOUR OF THEM ARE ONE. This is not
;  laziness, it is arithmetic. With the D-cache and MMU off this part
;  retires about two million instructions a second - every fetch is a
;  separate uncached DRAM transaction - and the desk model counts a
;  single P-256 scalar multiply at 276 million instructions. That is
;  over two minutes for ONE, and an ECDSA verify is two of them. A
;  deterministic computation does not get more accurate by being
;  repeated, and the counter ticks at 54 MHz, so one operation is
;  measured to a part in a hundred million. Repeating it would spend an
;  hour of a SHARED board on nothing.
;
;  The cheap modules keep a small repeat count because their single
;  operation is short enough that the loop and the byte comparison would
;  otherwise be a visible fraction of it.
; ----------------------------------------------------------------------
Procedure CryptoSpeedRun2()
  Define hz.i
  Define t0.i
  Define t1.i
  Define i.i
  Define r.i

  CryTickCheck()
  hz = TickHz()

  PrintN("Public-key throughput on this part, one line per module.")
  PrintN("  Each row re-runs a vector the sweep above has already answered, so")
  PrintN("  the cost includes everything a caller pays: the key install, the")
  PrintN("  message hash, the certificate parse. Operations a second, and")
  PrintN("  microseconds each, because bytes a second means nothing here.")
  UartDrain()

  PrintN("bignum   BnModpow, 2048-bit modulus")
  If CryPickVector(#CRY_MOD_BIGNUM, 2, 256) = 0
    PrintN("  !! no 2048-bit BnModpow record is in this image's table, so no rate")
    PrintN("     was measured. The table is generated; regenerate it with")
    PrintN("     tools/gen_pi4_crypto_selftest.py rather than editing this line.")
  Else
    t0 = Ticks()
    i = 0
    While i < 4
      r = CryRunBignum()
      i = i + 1
    Wend
    t1 = Ticks()
    If r <> 0
      PrintN("  !! the timed run FAILED where the sweep passed, so no rate is")
      PrintN("     printed. That is a difference between two runs of one image and")
      PrintN("     it matters more than the rate would.")
    Else
      CryOpsLine(4, t1 - t0, hz)
    EndIf
  EndIf
  UartDrain()

  PrintN("p256     EcP256Mulgen, a full scalar multiply")
  If CryPickVector(#CRY_MOD_P256, 1, 0) = 0
    PrintN("  !! no EcP256Mulgen record is in this image's table, so no rate.")
  Else
    t0 = Ticks()
    i = 0
    While i < 1
      r = CryRunP256()
      i = i + 1
    Wend
    t1 = Ticks()
    If r <> 0
      PrintN("  !! the timed run FAILED where the sweep passed, so no rate.")
    Else
      CryOpsLine(1, t1 - t0, hz)
    EndIf
  EndIf
  UartDrain()

  PrintN("x25519   one X25519, RFC 7748")
  If CryPickVector(#CRY_MOD_X25519, 0, 0) = 0
    PrintN("  !! no X25519 record is in this image's table, so no rate.")
  Else
    t0 = Ticks()
    i = 0
    While i < 1
      r = CryRunX25519()
      i = i + 1
    Wend
    t1 = Ticks()
    If r <> 0
      PrintN("  !! the timed run FAILED where the sweep passed, so no rate.")
    Else
      CryOpsLine(1, t1 - t0, hz)
    EndIf
  EndIf
  UartDrain()

  PrintN("ecdsa    EcdsaVrfyRaw, P-256, a signature that verifies")
  If CryPickVector(#CRY_MOD_ECDSA, 1 | (#CRY_V_ONE << 8), 0) = 0
    PrintN("  !! no positive raw ECDSA record is in this image's table, so no rate.")
  Else
    t0 = Ticks()
    i = 0
    While i < 1
      r = CryRunEcdsa()
      i = i + 1
    Wend
    t1 = Ticks()
    If r <> 0
      PrintN("  !! the timed run FAILED where the sweep passed, so no rate.")
    Else
      CryOpsLine(1, t1 - t0, hz)
    EndIf
  EndIf
  UartDrain()

  PrintN("rsa      RsaPkcs1Vrfy, 2048-bit modulus, hash included")
  If CryPickVector(#CRY_MOD_RSA, 0 | (1 << 8), 256) = 0
    PrintN("  !! no positive 2048-bit PKCS#1 record is in this image's table, so")
    PrintN("     no rate was measured.")
  Else
    t0 = Ticks()
    i = 0
    While i < 4
      r = CryRunRsa()
      i = i + 1
    Wend
    t1 = Ticks()
    If r <> 0
      PrintN("  !! the timed run FAILED where the sweep passed, so no rate.")
    Else
      CryOpsLine(4, t1 - t0, hz)
    EndIf
  EndIf
  UartDrain()

  PrintN("x509     X509ValidateChain, a two-certificate EC chain")
  If CryPickVector(#CRY_MOD_X509, 2, 0) = 0
    PrintN("  !! no two-certificate chain is in this image's table, so no rate.")
  ElseIf (PeekA(@cryE[0]) & 255) <> #X509ERR_OK
    Print("  !! the first two-certificate record expects code ")
    PrintDec(PeekA(@cryE[0]) & 255)
    PrintN(", not 32,")
    PrintN("     so timing it would be timing a REFUSAL and calling it a")
    PrintN("     validation. No rate was measured. The order of the cases in")
    PrintN("     tools/a64/a64_x509_check.py's mode C has changed; fix the pick,")
    PrintN("     do not relax this check.")
  Else
    t0 = Ticks()
    i = 0
    While i < 1
      r = CryRunX509()
      i = i + 1
    Wend
    t1 = Ticks()
    If r <> 0
      PrintN("  !! the timed run FAILED where the sweep passed, so no rate.")
    Else
      CryOpsLine(1, t1 - t0, hz)
    EndIf
  EndIf
  UartDrain()

  RsaSetPubKey(0, 0, 0, 0)
  X509ResetAnchors()
  PrintN("")
  PrintN("throughput: 6 public-key modules measured on this part.")
EndProcedure

Procedure CryptoSpeedRun(n.i)
  Define i.i
  Define t0.i
  Define t1.i
  Define hz.i
  Define seed.i
  Define r.i
  Define hk.i
  Define kwn.i
  Define pit.i

  If n <= 0 Or n > #CRY_SPEED_MAX
    n = #CRY_SPEED_MAX
  EndIf
  CryTickCheck()
  hz = TickHz()

  seed = 305419896                 ; $12345678, an arbitrary fill
  i = 0
  While i < n
    seed = (seed * 1103515245 + 12345) & $7FFFFFFF
    crySpeedA[i] = (seed >> 16) & 255
    i = i + 1
  Wend
  i = 0
  While i < 32
    seed = (seed * 1103515245 + 12345) & $7FFFFFFF
    crySpeedKey[i] = (seed >> 16) & 255
    If i < 16
      crySpeedIv[i] = (seed >> 8) & 255
    EndIf
    i = i + 1
  Wend

  PrintN("Throughput on this part, over a buffer of")
  Print("  ")
  PrintDec(n)
  Print(" bytes, CNTPCT_EL0 at ")
  PrintDec(hz)
  PrintN(" Hz.")
  PrintN("  These are the numbers the desktop model cannot produce - it has no")
  PrintN("  clock, no caches and no memory system.")
  PrintN("  ONE LINE PER MODULE, all eleven. Nine of them run over the whole")
  PrintN("  buffer. hkdf and pbkdf2 CANNOT BE ASKED FOR THAT MUCH and each says")
  PrintN("  underneath its rate what it ran instead and what imposes the ceiling.")
  UartDrain()

  PrintN("sha256")
  t0 = Ticks()
  Sha256Of(@crySpeedA[0], n, @cryOut[0])
  t1 = Ticks()
  CrySpeedLine(n, t1 - t0, hz)
  UartDrain()

  PrintN("sha1")
  t0 = Ticks()
  Sha1Of(@crySpeedA[0], n, @cryOut[0])
  t1 = Ticks()
  CrySpeedLine(n, t1 - t0, hz)
  UartDrain()

  PrintN("hmac     HMAC-SHA-256 under a 32-byte key")
  t0 = Ticks()
  HmacOf(@crySpeedKey[0], 32, @crySpeedA[0], n, @cryOut[0])
  t1 = Ticks()
  CrySpeedLine(n, t1 - t0, hz)
  UartDrain()

  PrintN("hmacsha1 HMAC-SHA-1 under a 32-byte key")
  t0 = Ticks()
  HmacSha1Of(@crySpeedKey[0], 32, @crySpeedA[0], n, @cryOut[0])
  t1 = Ticks()
  CrySpeedLine(n, t1 - t0, hz)
  UartDrain()

  ; HKDF IS THE FIRST OF THE TWO THAT CANNOT BE GIVEN 64 KB, and the
  ; ceiling is the document's, not this buffer's: RFC 5869 counts the
  ; expand rounds in one octet, so the most HKDF-Expand can ever produce
  ; is 255 hash lengths - 8160 bytes for SHA-256. The module returns
  ; SHORT rather than running the counter past 255, so the rate is
  ; computed over what it actually wrote, never over what was asked for.
  hk = 8160
  If hk > n
    hk = n
  EndIf
  PrintN("hkdf     HKDF-SHA-256, extract then expand, output bytes")
  HkdfExtract(@crySpeedIv[0], 16, @crySpeedKey[0], 32, @cryTmp[0])
  t0 = Ticks()
  r = HkdfExpand(@cryTmp[0], 32, @crySpeedIv[0], 16, @crySpeedB[0], hk)
  t1 = Ticks()
  If r <= 0
    PrintN("  !! HkdfExpand produced nothing at code 3 (REFUSED), which cannot")
    PrintN("     happen for a legal output length. No rate was measured. Check the")
    PrintN("     outlen bound at the top of HkdfExpand.")
  Else
    CrySpeedLine(r, t1 - t0, hz)
    PrintN("     Not the whole buffer: RFC 5869 caps HKDF-Expand at 255 hash")
    PrintN("     lengths, so 8160 bytes is every byte this function can ever")
    PrintN("     produce from one PRK. The rate above is over what it returned.")
  EndIf
  UartDrain()

  ; PBKDF2 IS THE SECOND, and for the opposite reason: the ceiling is
  ; this file's own and the measurement would be meaningless anyway. A
  ; password KDF's cost is its ITERATION COUNT, not its output length -
  ; a 64 KB derivation at one iteration would print a fast, flattering
  ; number for a function whose whole purpose is to be slow. What is
  ; timed instead is the shape the supplicant actually asks for: 32
  ; bytes at 4096 iterations, which is two 20-byte blocks and therefore
  ; 8192 HMAC-SHA-1 calls.
  ;
  ; THE ITERATION COUNT SCALES WITH THE SIZE ARGUMENT, and it has to.
  ; Every other row is sized by `crypto speed <kb>`; this one has no
  ; bytes to size, so it takes the same argument as work instead -
  ; n / 16, which lands exactly on the supplicant's 4096 at the 64 KB
  ; default and gives a small number for a small request. That matters
  ; off the board: the desk gate runs this procedure inside an
  ; instruction-level model at `--speed 1024`, where 4096 iterations is
  ; half a billion modelled instructions and about an hour, for a
  ; section whose only job is to prove the arithmetic is well formed.
  ; The count is PRINTED, so no reader ever has to infer which one ran.
  pit = n / 16
  If pit < 1
    pit = 1
  EndIf
  If pit > 4096
    pit = 4096
  EndIf
  Print("pbkdf2   PBKDF2-HMAC-SHA-1, 32 bytes at ")
  PrintDec(pit)
  PrintN(" iterations")
  t0 = Ticks()
  r = Pbkdf2Sha1(@crySpeedKey[0], 32, @crySpeedIv[0], 16, pit, @cryOut[0], 32)
  t1 = Ticks()
  If r <> 32
    PrintN("  !! Pbkdf2Sha1 refused a 32-byte derivation at code 3 (REFUSED), which")
    PrintN("     cannot happen for a legal length. No rate was measured. Check the")
    PrintN("     dklen bound against #PBKDF2_MAXDK in the module.")
  Else
    CryPbkdf2Line(pit, t1 - t0, hz)
    PrintN("     Not the whole buffer and not bytes a second, deliberately: this")
    PrintN("     module caps the derived length at 64 bytes, and the cost of a")
    PrintN("     password KDF is its ITERATIONS. This is the shape the supplicant")
    PrintN("     asks for, so it is the number that answers how long a join takes.")
  EndIf
  UartDrain()

  PrintN("drbg     HMAC-DRBG-SHA-256 generate")
  r = DrbgInit(@crySpeedKey[0], 32)
  If r <> #DRBG_OK And r <> #DRBG_WARN_SHORT_SEED
    Print("  !! DrbgInit refused a 32-byte seed at code 3 (REFUSED), returning ")
    PrintDec(r)
    PrintN(".")
    PrintN("     No rate was measured. A 32-byte seed is the full seed strength this")
    PrintN("     module asks for, so check DrbgSeedUsable and the stuck-value detector.")
  Else
    t0 = Ticks()
    r = DrbgGenerate(@crySpeedB[0], n)
    t1 = Ticks()
    If r <> n
      Print("  !! DrbgGenerate returned ")
      PrintDec(r)
      Print(" where ")
      PrintDec(n)
      PrintN(" bytes were asked for, so no")
      PrintN("     rate was measured. Check the instantiate state - an unseeded")
      PrintN("     generator answers with a negative code and writes nothing.")
    Else
      CrySpeedLine(n, t1 - t0, hz)
    EndIf
  EndIf
  UartDrain()

  ; THE RAW BLOCK CIPHER, ONE CALL PER 16 BYTES. This is the only row
  ; that pays the per-call cost on every block, and that is the point of
  ; having it beside aes-ctr: the difference between the two lines is
  ; what the two-lane CTR seam buys. n is always a multiple of 1024 here
  ; because the console multiplies kilobytes, so the loop cannot leave a
  ; partial block behind.
  PrintN("aes      AES-128 raw blocks, one call per 16 bytes")
  AesWipe()
  r = AesSetKey(@crySpeedKey[0], 16)
  If r = 0
    PrintN("  !! AesSetKey refused a 16-byte key at code 3 (REFUSED), which cannot")
    PrintN("     happen for a legal length. No rate was measured. Check the key")
    PrintN("     length table at the top of AesSetKey.")
  Else
    t0 = Ticks()
    i = 0
    While i < n
      AesEncryptBlock(@crySpeedA[0] + i, @crySpeedB[0] + i)
      i = i + 16
    Wend
    t1 = Ticks()
    CrySpeedLine(n, t1 - t0, hz)
  EndIf
  UartDrain()

  PrintN("aes-ctr  AES-128")
  AesWipe()
  r = AesCtrInit(@crySpeedKey[0], 16)
  If r = 0
    PrintN("  !! AesCtrInit refused a 16-byte key at code 3 (REFUSED), which cannot")
    PrintN("     happen for a legal length. No rate was measured. Check AesSetKey.")
  Else
    t0 = Ticks()
    AesCtrRun(@crySpeedIv[0], @crySpeedA[0], @crySpeedB[0], n)
    t1 = Ticks()
    CrySpeedLine(n, t1 - t0, hz)
  EndIf
  UartDrain()

  PrintN("gcm      AES-128-GCM, encrypt with a 12-byte IV and no AAD")
  AesWipe()
  r = GcmInit(@crySpeedKey[0], 16)
  If r = 0
    PrintN("  !! GcmInit refused a 16-byte key at code 3 (REFUSED), which cannot")
    PrintN("     happen for a legal length. No rate was measured. Check AesCtrInit.")
  Else
    t0 = Ticks()
    GcmEncrypt(@crySpeedIv[0], 12, @crySpeedIv[0], 0, @crySpeedA[0], n, @crySpeedB[0], @cryTag[0])
    t1 = Ticks()
    CrySpeedLine(n, t1 - t0, hz)
  EndIf
  UartDrain()

  ; RFC 3394 WRAPS INTO plainlen + 8 BYTES, so the input is eight short
  ; of the buffer and the output fills it exactly. Six passes over the
  ; semiblocks means six AES calls per eight bytes of key data, which is
  ; why this row is far slower than the aes one above it and is not a
  ; defect.
  kwn = n - 8
  kwn = kwn - (kwn % 8)
  PrintN("keywrap  RFC 3394 wrap under a 256-bit KEK")
  AesWipe()
  If kwn < 16
    Print("  !! the buffer is too small to wrap anything at code 1 (SIZE): ")
    PrintDec(kwn)
    PrintN(" bytes")
    PrintN("     of key data, where RFC 3394 needs at least two semiblocks in and")
    PrintN("     eight more bytes out. No rate was measured. The console cannot ask")
    PrintN("     for this - it multiplies whole kilobytes - so a caller reached")
    PrintN("     CryptoSpeedRun with a size of its own; check that call.")
  Else
    t0 = Ticks()
    r = KwWrap(@crySpeedKey[0], 32, @crySpeedA[0], kwn, @crySpeedB[0])
    t1 = Ticks()
    If r <> kwn + 8
      Print("  !! KwWrap returned ")
      PrintDec(r)
      Print(" where ")
      PrintDec(kwn + 8)
      PrintN(" was required, so no rate")
      PrintN("     was measured. A zero means it refused the length or the KEK; the")
      PrintN("     length here is a multiple of eight by construction, so check the")
      PrintN("     KEK length table in AesSetKey first.")
    Else
      CrySpeedLine(kwn, t1 - t0, hz)
    EndIf
  EndIf
  UartDrain()

  AesWipe()
  GcmWipe()
  KwWipe()
  Pbkdf2Wipe()
  PrintN("")
  PrintN("throughput: 11 symmetric modules measured on this part.")
  PrintN("")
  CryptoSpeedRun2()
EndProcedure

; ----------------------------------------------------------------------
;  CryHeader() / CryTotals() - the frame around a sweep.
; ----------------------------------------------------------------------
Procedure CryHeader()
  PrintN("crypto - known-answer self-test, on this board, on the vectors the")
  PrintN("         desktop gates use. module / id / verdict / CNTPCT_EL0 ticks.")
  If cryTicksOk = 0
    PrintN("         THE TICK COLUMN IS A DASH: CNTPCT_EL0 is not advancing, so")
    PrintN("         nothing here is timed. The verdicts are unaffected.")
  EndIf
  PrintN("")
EndProcedure

Procedure CryTotals()
  PrintN("")
  Print("crypto: ")
  PrintDec(cryPasses)
  Print(" of ")
  PrintDec(cryChecks)
  Print(" vectors PASS")
  If cryForgeries > 0
    Print(", ")
    PrintDec(cryForgeries)
    Print(" forged GCM tags REFUSED")
  EndIf
  If cryRefusals > 0
    Print(", ")
    PrintDec(cryRefusals)
    Print(" negatives REFUSED in all")
  EndIf
  PrintNl()
  If cryFails = 0
    PrintN("  Every answer is byte-for-byte the published one. The vectors came")
    PrintN("  from the documents, not from running this board and writing down")
    PrintN("  what it said.")
  Else
    Print("  ")
    PrintDec(cryFails)
    PrintN(" FAILED. Read the sentences above: each names its code and the")
    PrintN("  first thing to check. If the desktop gate for the same module is")
    PrintN("  green, the disagreement is between the model and the part and THAT")
    PrintN("  is the result - report both outputs, do not adjust the vector.")
  EndIf
EndProcedure

; ----------------------------------------------------------------------
;  CmdCrypto - the console entry.
;
;    crypto                 every vector, then the throughput
;    crypto vectors         the vectors only
;    crypto speed [kb]      the throughput only, over kb kilobytes
;    crypto <module>        one module's vectors
;    crypto list            what is in the table and where it came from
; ----------------------------------------------------------------------
Procedure CryUsage()
  PrintN("crypto [vectors | speed [kb] | list | <module>]")
  PrintN("  the known-answer self-test for every crypto module, run here on the")
  PrintN("  board on the same vectors the desktop gates use. With no argument it")
  PrintN("  runs every vector and then the throughput lines.")
  PrintN("  modules: sha256 sha1 hmac hmacsha1 hkdf pbkdf2 drbg aes aes-ctr gcm")
  PrintN("           keywrap bignum p256 x25519 ecdsa rsa t0vm x509")
  PrintN("  Any keystroke stops a sweep, and a stopped one prints no verdict.")
EndProcedure

Procedure CryList()
  PrintN("crypto - the vector table compiled into this image:")
  Print("  sha256   ") : PrintDec(#CRY_MOD_SHA256)   : PrintN("  gen_sha256_vectors, the block-boundary lengths")
  Print("  sha1     ") : PrintDec(#CRY_MOD_SHA1)     : PrintN("  RFC 3174 section 7.3 and NIST CAVP SHA1ShortMsg")
  Print("  hmac     ") : PrintDec(#CRY_MOD_HMAC)     : PrintN("  RFC 4231 cases 1-7, case 5 truncated to 128 bits")
  Print("  hmacsha1 ") : PrintDec(#CRY_MOD_HMACSHA1) : PrintN("  RFC 2202 section 3")
  Print("  hkdf     ") : PrintDec(#CRY_MOD_HKDF)     : PrintN("  RFC 5869 appendix A, PRK and OKM both checked")
  Print("  pbkdf2   ") : PrintDec(#CRY_MOD_PBKDF2)   : PrintN("  RFC 6070, the vectors under 4096 iterations")
  Print("  drbg     ") : PrintDec(#CRY_MOD_DRBG)     : PrintN("  the NIST CAVP HMAC_DRBG SHA-256 anchor")
  Print("  aes      ") : PrintDec(#CRY_MOD_AES)      : PrintN("  FIPS-197 appendix C and NIST CAVP KAT_AES")
  Print("  aes-ctr  ") : PrintDec(#CRY_MOD_AESCTR)   : PrintN("  SP 800-38A CTR, one vector 259 blocks long")
  Print("  gcm      ") : PrintDec(#CRY_MOD_GCM)      : PrintN("  NIST/McGrew, every one with a forged tag too")
  Print("  keywrap  ") : PrintDec(#CRY_MOD_KEYWRAP)  : PrintN("  RFC 3394 section 4")
  Print("  bignum   ") : PrintDec(#CRY_MOD_BIGNUM)   : PrintN("  the shared i15 table, plus the DERIVED full-limb modulus")
  Print("  p256     ") : PrintDec(#CRY_MOD_P256)     : PrintN("  NIST P-256 KATs and five points that must be REFUSED")
  Print("  x25519   ") : PrintDec(#CRY_MOD_X25519)   : PrintN("  RFC 7748, incl. the scalar with bit 254 cleared")
  Print("  ecdsa    ") : PrintDec(#CRY_MOD_ECDSA)    : PrintN("  RFC 6979 and CAVP SigVer - 9 verify, 37 must not")
  Print("  rsa      ") : PrintDec(#CRY_MOD_RSA)      : PrintN("  PKCS#1 v1.5 and PSS at 2048/3072/4096, valid and forged")
  Print("  t0vm     ") : PrintDec(#CRY_MOD_T0VM)     : PrintN("  forum 517's RAM bounds guard and the 64-bit cell")
  Print("  x509     ") : PrintDec(#CRY_MOD_X509)     : PrintN("  real chains verify; tampered ones are refused BY NAME")
  Print("  ")
  PrintDec(#CRY_VEC_COUNT)
  PrintN(" vectors in total. None was typed: they are read out of the")
  PrintN("  documents and the generators by tools/gen_pi4_crypto_selftest.py.")
EndProcedure

Procedure CryRunAndReport(only.i)
  Define r.i
  CryTickCheck()
  CryHeader()
  r = CryptoSelfTestAll(only)
  If r >= 0
    CryTotals()
  EndIf
EndProcedure

Procedure CmdCrypto()
  Define kb.i

  SkipSpace()
  If gLine[gPos] = 0
    CryRunAndReport(0)
    PrintN("")
    CryptoSpeedRun(#CRY_SPEED_MAX)
    ProcedureReturn
  EndIf

  gWordAt = gPos
  SkipWord()
  gWordLen = gPos - gWordAt

  If WordIs("vectors") <> 0
    CryRunAndReport(0)
  ElseIf WordIs("list") <> 0
    CryList()
  ElseIf WordIs("help") <> 0
    CryUsage()
  ElseIf WordIs("speed") <> 0
    kb = ParseDec()
    If gParseOk = 0
      kb = #CRY_SPEED_MAX / 1024
    EndIf
    If kb < 1
      kb = 1
    EndIf
    If kb > #CRY_SPEED_MAX / 1024
      Print("!! ")
      PrintDec(kb)
      Print(" KB is more than the ")
      PrintDec(#CRY_SPEED_MAX / 1024)
      PrintN(" KB buffer this image reserved,")
      PrintN("   so the run was made over the whole buffer instead. The size is")
      PrintN("   #CRY_SPEED_MAX in Anvil/Core/crypto_cmd.pbi and it is .bss, not image.")
      kb = #CRY_SPEED_MAX / 1024
    EndIf
    CryptoSpeedRun(kb * 1024)
  ElseIf WordIs("sha256") <> 0
    CryRunAndReport(#CRY_MOD_SHA256)
  ElseIf WordIs("sha1") <> 0
    CryRunAndReport(#CRY_MOD_SHA1)
  ElseIf WordIs("hmacsha1") <> 0
    CryRunAndReport(#CRY_MOD_HMACSHA1)
  ElseIf WordIs("hmac") <> 0
    CryRunAndReport(#CRY_MOD_HMAC)
  ElseIf WordIs("hkdf") <> 0
    CryRunAndReport(#CRY_MOD_HKDF)
  ElseIf WordIs("pbkdf2") <> 0
    CryRunAndReport(#CRY_MOD_PBKDF2)
  ElseIf WordIs("drbg") <> 0
    CryRunAndReport(#CRY_MOD_DRBG)
  ElseIf WordIs("aes-ctr") <> 0 Or WordIs("ctr") <> 0
    CryRunAndReport(#CRY_MOD_AESCTR)
  ElseIf WordIs("aes") <> 0
    CryRunAndReport(#CRY_MOD_AES)
  ElseIf WordIs("gcm") <> 0
    CryRunAndReport(#CRY_MOD_GCM)
  ElseIf WordIs("keywrap") <> 0
    CryRunAndReport(#CRY_MOD_KEYWRAP)
  ElseIf WordIs("bignum") <> 0
    CryRunAndReport(#CRY_MOD_BIGNUM)
  ElseIf WordIs("p256") <> 0
    CryRunAndReport(#CRY_MOD_P256)
  ElseIf WordIs("x25519") <> 0
    CryRunAndReport(#CRY_MOD_X25519)
  ElseIf WordIs("ecdsa") <> 0
    CryRunAndReport(#CRY_MOD_ECDSA)
  ElseIf WordIs("rsa") <> 0
    CryRunAndReport(#CRY_MOD_RSA)
  ElseIf WordIs("t0vm") <> 0
    CryRunAndReport(#CRY_MOD_T0VM)
  ElseIf WordIs("x509") <> 0
    CryRunAndReport(#CRY_MOD_X509)
  Else
    PrintN("!! that is not a module this self-test knows, so nothing was run.")
    CryUsage()
  EndIf
EndProcedure
