
; ======================================================================

; ======================================================================
;  THE WIDTH-SUFFIX PARAGRAPH IS GENERATED, NOT TYPED.  Forum 585.
; ======================================================================
;  The summary paragraph below used to be four hand-written lines, and
;  they were wrong about the memory dump: they said the suffix "changes
;  what the count counts" and that "every command prints the byte count
;  it worked out", and the dump counts bytes whichever width you pick and
;  printed no total. The per-command entry two hundred lines above was
;  correct at the same time, so the reference contradicted itself with
;  the accurate wording in the specific entry and the wrong wording in
;  the summary.
;
;  That is what happens to a rule written twice in English. So it is
;  written ONCE, as the width table in Anvil/Core/memcmd.pbi, and these
;  three procedures WALK it. The commands read the same rows for their
;  defaults. There is nothing left for the two to disagree about, and
;  tools/a64/a64_anvil_check.py executes both and diffs them anyway,
;  because a table two readers agree about can still be wrong.
;
;  ADDING A COMMAND to the table makes it appear in this paragraph with
;  no edit here. That is the point of it.
; ======================================================================

; ----------------------------------------------------------------------
;  PutWtNames(which) - the command words as "a, b and c".
;
;  which = 0 those whose suffix does not scale the byte count, 1 those
;  whose suffix scales the count, -1 all of them. The Oxford comma is left out to
;  match the prose everywhere else in this help.
; ----------------------------------------------------------------------
Procedure PutWtNames(which.i)
  Define i.i
  Define n.i
  Define k.i
  n = 0
  i = 0
  While i < #WT_N
    If which < 0 Or WtScales(i) = which
      n = n + 1
    EndIf
    i = i + 1
  Wend
  k = 0
  i = 0
  While i < #WT_N
    If which < 0 Or WtScales(i) = which
      If k > 0
        If k = (n - 1)
          Print(" and ")
        Else
          Print(", ")
        EndIf
      EndIf
      UartWriteStr(WtName(i))
      k = k + 1
    EndIf
    i = i + 1
  Wend
EndProcedure

Procedure PutWidthRule()
  Define i.i
  Print("  The .b/.w/.l width suffix works on ")
  PutWtNames(-1)
  PrintN(".")
  PrintN("  It does one of two things and which one depends on the command.")
  Print("  On ")
  PutWtNames(0)
  PrintN(" the suffix selects true 8, 16 or 32-bit reads and their GROUPING:")
  PrintN("  the count stays in BYTES whichever width you pick. A .w or .l start")
  PrintN("  must be aligned to 2 or 4 bytes, and the byte count must be a whole")
  PrintN("  number of that width; otherwise nothing is read. Bare md reads bytes.")
  Print("  On ")
  PutWtNames(1)
  PrintN(" it changes what the count COUNTS:")
  PrintN("  the count is that many bytes, halfwords or words, and the memory")
  PrintN("  touched is the count times the width.")
  PrintN("  With no suffix at all:")
  i = 0
  While i < #WT_N
    Print("    ")
    UartWriteStr(WtName(i))
    If WtScales(i) = 0
      Print(" groups by ")
    Else
      Print(" counts ")
    EndIf
    PutUnit(WtDefSize(i))
    PrintNl()
    i = i + 1
  Wend
  PrintN("  Every one of them prints the byte count it worked out, including md,")
  PrintN("  which until recently printed none.")
EndProcedure

Procedure Help()
  PrintN("Every command is a whole word. The old single letters all still work")
  PrintN("and are shown in brackets after each one, because the host tools type")
  PrintN("them and because U-Boot's own loads and go land here too.")
  PrintN("Every command prints something, on every path, whether it worked or")
  PrintN("not. If one ever returns to the prompt in silence, that is a fault.")
  PrintNl()
  PrintN("GETTING CODE IN")
  PrintN("  receive <address> <length> <checksum>  [b]")
  PrintN("                  the fast way in. All three numbers are hexadecimal.")
  PrintN("                  The monitor answers rdy, the host sends that many")
  PrintN("                  raw bytes in chunks of 1024, and one + comes back")
  PrintN("                  per chunk. The last line is ok or crc. The checksum")
  PrintN("                  is the IEEE reflected CRC32, polynomial EDB88320.")
  PrintN("  srecord                               [l, loads]")
  PrintN("                  the slow way in, and the proven one. S3 records")
  PrintN("                  carry the data and an S7 record ends the stream. A")
  PrintN("                  record that never arrives cannot be detected, since")
  PrintN("                  each checksum covers only its own record, so this")
  PrintN("                  is the one to fall back to rather than the one to")
  PrintN("                  reach for. One bad record blocks run until an image")
  PrintN("                  loads cleanly.")
  PrintN("  load <name> [address]                 [f, fatload]")
  PrintN("                  read a file off the boot medium into memory. What")
  PrintN("                  that medium IS depends on the board - type f on")
  PrintN("                  its own and it says. The name is a short 8.3 name")
  PrintN("                  and case does not matter. Without an")
  Print("                  address it loads at ")
  PutAddr(HwStageAddr())
  PrintN(". The range is checked")
  PrintN("                  against the payload windows, and the length is the")
  PrintN("                  file's, not yours - which is why an address that")
  PrintN("                  looks fine can still be refused.")
  PrintN("  mount                                 [f]")
  PrintN("                  bring the boot medium up and report what it is,")
  PrintN("                  loading nothing. This is the command to type when")
  PrintN("                  load has failed, because it names the step that")
  PrintN("                  went wrong.")
  PrintN("  fatls                                 [ls]")
  PrintN("                  list the root directory of the boot medium: each")
  PrintN("                  file's 8.3 name and its size in bytes, a <DIR> marker")
  PrintN("                  for a subdirectory, and a summary line of how many")
  PrintN("                  files, bytes and directories there are. It lists the")
  PrintN("                  root only - the FAT reader reads no subdirectory - so")
  PrintN("                  a path argument is refused rather than half-answered.")
  PrintN("                  Names are the short 8.3 form and case does not matter.")
  PrintN("                  Any keystroke stops a long listing, which then says so.")
  PrintN("  save <name> <address> [length]")
  PrintN("                  write that many bytes out of memory onto the boot")
  PrintN("                  medium, replacing that file and resizing it to")
  PrintN("                  match. The length is hexadecimal; leave it out and")
  PrintN("                  the file keeps the size it already has. A file that")
  PrintN("                  is not on the medium yet is created, but only when a")
  PrintN("                  length is given, because a file that does not exist")
  PrintN("                  has no size of its own to keep. Writing is")
  PrintN("                  implemented for USB only. This is how Anvil")
  PrintN("                  replaces itself, which is the whole point of it.")
  PrintNl()
  PrintN("RUNNING IT")
  PrintN("  run [address]                         [g, go]")
  PrintN("                  jump to a payload and start it. Without an address")
  PrintN("                  it uses the entry point of the last thing loaded,")
  Print("                  or ")
  PutAddr(HwStageAddr())
  PrintN(" if nothing has been loaded. If the")
  PrintN("                  payload ever comes back, its x0 register is")
  PrintN("                  printed. A stock image never comes back.")
  PrintN("  booti [addr [initrd [fdt]]]")
  PrintN("                  boot an arm64 Linux Image. Checks the Image magic,")
  PrintN("                  keeps the firmware's device tree (or the fdt you give,")
  PrintN("                  after a dash for the skipped initrd: booti addr - fdt),")
  PrintN("                  sets x0 to it, drops from EL2 to EL1 and branches. It")
  PrintN("                  refuses loudly rather than jump into anything that is")
  PrintN("                  not a kernel. Does not return.")
  PrintN("  bootm [addr [initrd [fdt]]]")
  PrintN("                  boot a container. A legacy uImage holding a single")
  PrintN("                  uncompressed arm64 Linux kernel is booted; a FIT")
  PrintN("                  (.itb) is refused (no device-tree parser here); a bare")
  PrintN("                  Image is sent to booti. Anything else is refused by name.")
  PrintN("  boot <name>")
  PrintN("                  THE BOOTLOADER. Read a payload container off the")
  PrintN("                  boot medium, place its image at the address the")
  PrintN("                  payload was BUILT for, check its SHA-256, and only")
  PrintN("                  then enter it. No address is typed anywhere: the")
  PrintN("                  container carries the load address, the entry")
  PrintN("                  point, the zero-init extent and the hash, because")
  PrintN("                  the compiler knew all four and writing them down")
  PrintN("                  beats retyping them. The container is the .pmf file")
  PrintN("                  pmfc writes beside the flat image.")
  PrintN("                  It REFUSES, loudly and having done nothing, on a")
  PrintN("                  bad magic, a version it cannot read, a length that")
  PrintN("                  disagrees with the file, a load or zero-init range")
  PrintN("                  that runs over the monitor or outside the payload")
  PrintN("                  windows, an entry outside its own image, and above")
  PrintN("                  all on a hash that does not match. The hash check")
  PrintN("                  is mandatory and it is the last thing before the")
  PrintN("                  jump.")
  PrintN("  boot mem <address>")
  PrintN("                  the same, for a container already in memory - one")
  PrintN("                  that arrived over receive or over the air, with no")
  PrintN("                  medium involved at any point.")
  PrintN("  boot status")
  PrintN("                  what this board would do at its next start, and")
  PrintN("                  the four settings behind it. Bare boot is this.")
  PrintN("  boot ok")
  PrintN("                  clear the failure counter: the payload came up.")
  PrintN("                  Say it when the payload is actually working -")
  PrintN("                  saying it every boot regardless turns the")
  PrintN("                  reboot-loop guard off.")
  PrintN("  boot clear")
  PrintN("                  stop booting a file at start-up. The prompt only.")
  PrintN("  autoboot [address]                    [a]")
  PrintN("                  the QUICK path, and a different thing from boot.")
  PrintN("                  It takes a bare ADDRESS in DRAM, checks nothing")
  PrintN("                  about what is there, and lives in a memory cell")
  PrintN("                  that survives a reset but NOT a power cycle.")
  PrintN("                  autoboot <address> arms it, autoboot 0 clears it,")
  PrintN("                  and autoboot on its own says what it is set to. An")
  PrintN("                  armed monitor waits about two seconds for a key")
  PrintN("                  when it starts and then runs what it points at.")
  PrintN("                  It is taken BEFORE boot.file, because somebody")
  PrintN("                  typed it in this power cycle and boot.file is")
  PrintN("                  standing configuration.")
  PrintN("  deadman [seconds | off]               [d]")
  PrintN("                  a watchdog that covers the NEXT payload and")
  PrintN("                  nothing else. If the payload hangs, the board")
  PrintN("                  resets itself instead of sitting there. It is")
  PrintN("                  never running while you are at this prompt. The")
  PrintN("                  seconds are decimal. The counter behind it is 20")
  PrintN("                  bits at 65536 ticks a second, so a fraction under")
  PrintN("                  16 seconds is the ceiling; anything larger is cut")
  PrintN("                  down to 15 rather than 16, because a deadman that")
  PrintN("                  fires sooner than it promised is a trap.")
  PrintNl()
  PrintN("LOOKING AROUND")
  ; map IS FIRST IN THIS SECTION BECAUSE IT IS THE ANSWER TO THE FIRST
  ; QUESTION - 2026-09-08. Since this monitor stopped having a maximum
  ; size, "where may I put a thing" is not something a reader can look up
  ; in a file any more: it is a measurement this image takes of itself,
  ; so the command that prints it has to be the one they meet first.
  PrintN("  map")
  PrintN("                  the whole memory map, as this image measures it:")
  PrintN("                  what this monitor occupies and the byte count that")
  PrintN("                  came from, every region it refuses writes to, its")
  PrintN("                  stack top, the address to stage a file at, and both")
  PrintN("                  payload windows. NOTHING IN IT IS A CONSTANT. This")
  PrintN("                  program may be any size, so its extent is the size")
  PrintN("                  of the image the firmware loaded and the low window")
  PrintN("                  begins above it - both move when this program does.")
  PrintN("                  The upload tools ask for this rather than assuming.")
  PrintN("  memory <address> <count>              [m, dump, md]")
  PrintN("                  print a block of memory as hexadecimal, up to 4096")
  PrintN("                  bytes at a time, with 64 as the default. Both")
  PrintN("                  numbers are hex and the count is in bytes. The")
  PrintN("                  address is not WINDOW-checked - reading is the whole")
  PrintN("                  point of a debugger, and being able to point it at")
  PrintN("                  a device register block is most of its value - but")
  PrintN("                  the BOARD is asked about it first. See force below.")
  PrintN("                  md.b, md.w and md.l issue true 8, 16 or 32-bit reads")
  PrintN("                  and group each line in little-endian values. The count")
  PrintN("                  is still bytes whichever you pick. .w/.l require a")
  PrintN("                  2-/4-byte-aligned start and a byte count containing")
  PrintN("                  whole units; invalid ranges read nothing. A bare md")
  PrintN("                  reads bytes, as it always did.")
  PrintN("                  It ends by printing the byte total it dumped and the")
  PrintN("                  grouping it used, like the rest of this family.")
  PrintN("  write <address> <value>               [w, poke]")
  PrintN("                  write one 32-bit word and read it straight back.")
  PrintN("                  Both hex. The address must be a multiple of four,")
  PrintN("                  and an address inside the monitor is refused.")
  PrintN("  compare <first> <second> <count>      [cmp]")
  PrintN("                  compare two blocks and name the first byte that")
  PrintN("                  differs, and its address on both sides. Hex. A bare")
  PrintN("                  compare counts BYTES (U-Boot's cmp counts words);")
  PrintN("                  compare.b/.w/.l count bytes, halfwords or words.")
  PrintN("  copy <source> <destination> <count>   [cp]")
  PrintN("                  copy a block. Hex, overlapping ranges are safe, and")
  PrintN("                  the destination's caches are flushed so it can be")
  PrintN("                  run. A bare copy counts BYTES; copy.b/.w/.l count")
  PrintN("                  bytes, halfwords or words.")
  PrintN("  crc32 <address> <count>               [checksum]")
  PrintN("                  the CRC32 of a block. No size limit - a whole boot")
  PrintN("                  image is the point of it. This is how you check an")
  PrintN("                  image before or after save writes it: tools/anvil.py")
  PrintN("                  computes the same value on the host from the same")
  PrintN("                  polynomial, so the two agree independently or they")
  PrintN("                  do not. Any keystroke stops it and a stopped one")
  PrintN("                  prints no checksum at all.")
  PrintN("  sha1sum <address> <count>")
  PrintN("  sha256sum <address> <count>")
  PrintN("                  a cryptographic checksum of a block, lowercase hex, the")
  PrintN("                  same as the sha1sum / sha256sum tools on any machine -")
  PrintN("                  so a published image's checksum can be checked against")
  PrintN("                  what is actually in memory. Like crc32: no size limit,")
  PrintN("                  and a stopped one prints no digest.")
  PrintN("  crypto [vectors | speed [kb] | list | <module>]")
  PrintN("                  the known-answer self-test for every crypto module,")
  PrintN("                  run HERE, on the same vectors the desktop gates use -")
  PrintN("                  RFC 3174, 2202, 4231, 5869, 6070, 3394, FIPS-197, the")
  PrintN("                  NIST CAVP files and the NIST/McGrew GCM table. One line")
  PrintN("                  per vector with its CNTPCT_EL0 ticks; every GCM vector")
  PrintN("                  is decrypted again with one bit of its tag flipped and")
  PrintN("                  the forgery must be REFUSED. crypto speed adds one")
  PrintN("                  throughput line per module - all eleven, over a 64 KB")
  PrintN("                  buffer - which is the one number a desktop model cannot")
  PrintN("                  produce. Two of the eleven cannot be given 64 KB and each")
  PrintN("                  says under its own rate what it ran and what capped it.")
  PrintN("                  Not one vector is typed into the image; they are")
  PrintN("                  generated from the documents. Any keystroke stops it,")
  PrintN("                  and a stopped sweep prints no verdict.")
  PrintN("  fill <address> <value> [count]        [mw]")
  PrintN("                  set a range to one value. A bare fill writes 32-bit")
  PrintN("                  WORDS and count defaults to 1, which is what U-Boot's")
  PrintN("                  mw does; fill.b/.w/.l write and count bytes, halfwords")
  PrintN("                  or words. The byte count is always printed.")
  PrintN("  mm <address>                          modify memory, interactive")
  PrintN("  nm <address>                          the same, address held")
  PrintN("                  a sub-prompt shows one address and its value at a")
  PrintN("                  time. Type a hex value to write it, Enter to keep it,")
  PrintN("                  . or q or Ctrl-C to quit - the way out is on every")
  PrintN("                  line. mm steps to the next location, nm stays put.")
  PrintN("                  mm.b/.w/.l and nm.b/.w/.l set the width; bare is a")
  PrintN("                  word. Writes into the monitor are refused.")
  PrintN("  mtest <start> <end> [pattern [iters]] DESTRUCTIVE RAM test")
  PrintN("                  writes and reads back every word in start..end, so")
  PrintN("                  the range is OVERWRITTEN and NOT restored. No default")
  PrintN("                  range and it must lie inside a payload window - it")
  PrintN("                  refuses the monitor and everything else you do not")
  PrintN("                  own. Address, moving-inversion and walking one/zero")
  PrintN("                  tests; iters defaults to 1 (it does not loop forever)")
  PrintN("                  and any key stops it. A true DRAM test only with the")
  PrintN("                  D-cache off, which is the boot default.")
  PrintN("  base [address]")
  PrintN("                  a default address added to the address arguments of")
  PrintN("                  memory, write, fill, copy and compare, so repeated")
  PrintN("                  calls stop needing one. Starts at zero. It is NOT")
  PrintN("                  added by crc32, which matches U-Boot, and every")
  PrintN("                  command that does add it says so on the line.")
  PrintN("                  base 0 turns it off.")
  PrintN("  force <address>                       override one refused address")
  PrintN("                  EVERY command above that takes an address from you")
  PrintN("                  asks the board first whether that address is safe to")
  PrintN("                  touch, and refuses if it is not. This is what lets")
  PrintN("                  you go ahead anyway.")
  PrintN("                  Why it exists: on one of the boards Anvil runs on, a")
  PrintN("                  read of a block whose clock is off does not fail -")
  PrintN("                  the processor stops on it and the board has to be")
  PrintN("                  unplugged. A single memory command has done that")
  PrintN("                  three times. The board keeps a list of the blocks it")
  PrintN("                  knows about, and a refusal names the block and says")
  PrintN("                  whether the answer is measured or merely unknown.")
  PrintN("                  How it works: type force and the address, then")
  PrintN("                  repeat the refused command on the very NEXT line.")
  PrintN("                  It arms exactly that one address, for exactly one")
  PrintN("                  command line, and then expires whether it was used")
  PrintN("                  or not. force on its own says what is armed; force")
  PrintN("                  off disarms early.")
  PrintN("                  Why two lines and not a flag on the command: a flag")
  PrintN("                  is something a script can carry without anybody")
  PrintN("                  having decided, and deciding is the entire point.")
  PrintN("                  Writing the address twice, under two command words,")
  PrintN("                  cannot happen by accident.")
  PrintN("                  Type info to see what this board knows and where")
  PrintN("                  each answer came from.")
  PrintN("  Coming from U-Boot: md is memory, mw is fill, cmp is compare and cp")
  PrintN("  is copy, and all four of those U-Boot spellings are accepted here, so")
  PrintN("  a line copied out of a U-Boot session still runs. mm, nm and mtest")
  PrintN("  keep their U-Boot names.")
  PutWidthRule()
  PrintN("  loop is deliberately absent - it cannot return at all.")
  PrintN("  info                                  [i, board]")
  PrintN("  uptime                                [up]")
  PrintN("                  what board this is, how hot it is, and every clock")
  PrintN("                  rate the firmware will tell us about.")
  PrintN("  clock [rate]                          [c]")
  PrintN("                  show or set the processor clock. The rate is in")
  PrintN("                  hertz and it is DECIMAL - the one decimal argument")
  PrintN("                  in this monitor. It prints what the firmware")
  PrintN("                  applied and then what is actually measured,")
  PrintN("                  separately, because the firmware clamps a rate it")
  PrintN("                  dislikes and still reports success.")
  PrintN("  time [status]")
  PrintN("                  live wall time, zone, provenance and synchronization")
  PrintN("                  state. An unset clock says so; a restored disk value")
  PrintN("                  is identified as a floor, not trusted current time.")
  PrintN("  time set <unix-seconds-UTC>")
  PrintN("                  set trusted manual UTC time from decimal Unix seconds.")
  PrintN("  time zone <UTC | America/Chicago | fixed:+HH:MM | fixed:-HH:MM>")
  PrintN("                  choose display civil time. America/Chicago applies")
  PrintN("                  CST/CDT automatically; a fixed offset never does.")
  CompilerIf #CAP_NET = 1
  PrintN("  time sync       schedule a nonblocking SNTP refresh now.")
  PrintN("  time server <IPv4-or-hostname | default>")
  PrintN("                  choose SNTP explicitly, or restore DHCP option 42 then")
  PrintN("                  time.cloudflare.com fallback. A server never chooses")
  PrintN("                  the zone. Plain SNTP is not authenticated.")
  CompilerEndIf
  PrintN("                  Unknown zones/servers are refused. Time changes stay")
  PrintN("                  in memory until settings save. Default display is UTC.")
  PrintNl()
  PrintN("FROM U-BOOT, AND HARDWARE-FREE")
  PrintN("  echo [-n] <args>")
  PrintN("                  print the arguments, separated by single spaces, then")
  PrintN("                  a newline. -n as the first word drops the newline. No")
  PrintN("                  variable expansion - this monitor has no shell, so")
  PrintN("                  echo $x prints those three characters.")
  PrintN("  sleep <seconds>")
  PrintN("                  wait that many seconds and come back. Decimal seconds")
  PrintN("                  - a leading 0x or $ is hex, like clock. Any key ends")
  PrintN("                  the wait early, because a wait that could not be")
  PrintN("                  broken would be a hang. The ceiling is a day.")
  PrintN("  version [full]                        [ver]")
  PrintN("                  what this monitor is, WHICH build it is, and which")
  PrintN("                  target it was built for. The board name, the")
  PrintN("                  processor, the exception level and the target all")
  PrintN("                  come from the board, so this describes THIS computer")
  PrintN("                  and not some other one.")
  PrintN("                  It prints the build number with its date and time,")
  PrintN("                  and this image's own size and extent - those two")
  PrintN("                  together already tell two builds apart.")
  PrintN("                  version full adds a crc32 over the running image:")
  PrintN("                  the digest that says WHAT is in it rather than which")
  PrintN("                  build it is. It is a separate word because it reads")
  PrintN("                  every byte and is not instant, and bare version")
  PrintN("                  prints the exact crc32 command instead.")
  PrintN("                  Unlike U-Boot it does not print a compiler or")
  PrintN("                  linker version, because neither is stamped into the")
  PrintN("                  image and a guessed one is worse than none.")
  PrintN("  setexpr <name> <val1> [<op> <val2>]")
  PrintN("                  work out an expression and store it in the settings")
  PrintN("                  store as hex. op is one of + - * / % & | ^ << >>, both")
  PrintN("                  values hex. setexpr addr 400000 + 1000 puts 401000 in")
  PrintN("                  the setting called addr, ready for memory or run to use.")
  PrintN("                  The *addr, fmt and gsub forms are not here yet.")
  PrintNl()
  PrintN("THE SCREEN")
  PrintN("  screen [on [dsi | hdmi | number] | off | displays")
  PrintN("          | rotate [0|90|180|270]]              [s]")
  PrintN("                  the console on a screen. Everything the serial")
  PrintN("                  line gets, the screen gets; the wire stays the")
  PrintN("                  complete record and the screen is the")
  PrintN("                  convenience.")
  PrintN("                  THERE ARE TWO KINDS OF SCREEN ON THIS BOARD and")
  PrintN("                  they are not the same thing. An HDMI display is")
  PrintN("                  the firmware's: it must be connected BEFORE the")
  PrintN("                  board powers on, because the firmware only looks")
  PrintN("                  at boot. The Waveshare DSI panel is THIS")
  PrintN("                  monitor's - the firmware owns no DSI display and")
  PrintN("                  never brings DSI1 up, so this monitor lights the")
  PrintN("                  panel itself out of its own memory.")
  PrintN("                  AT BOOT, WITH NOTHING TYPED: a DSI panel that")
  PrintN("                  answers on the display connector wins, because")
  PrintN("                  somebody physically plugged it in; otherwise an")
  PrintN("                  HDMI display if the firmware found one;")
  PrintN("                  otherwise no screen, which is not a failure. The")
  PrintN("                  boot log says which.")
  PrintN("                  screen on its own says whether it is on, and")
  PrintN("                  turns it on if it is off. screen on dsi and")
  PrintN("                  screen on hdmi move it between the two.")
  PrintN("                  screen displays lists BOTH kinds truthfully -")
  PrintN("                  the firmware's census and the panel separately,")
  PrintN("                  because the panel is not one of the firmware's")
  PrintN("                  displays and reporting it as one would be an")
  PrintN("                  invention. This board has two HDMI sockets;")
  PrintN("                  screen on 1 brings the console up on the second")
  PrintN("                  display in that list. The number is a position")
  PrintN("                  in the list, NOT the number on the socket: with")
  PrintN("                  one cable, in either socket, it is number 0.")
  PrintN("                  Plain screen on lets the firmware choose among")
  PrintN("                  its own, which is what it has always done.")
  PrintN("  screen rotate [0|90|180|270]")
  PrintN("                  which way up the console sits ON THE DSI PANEL.")
  PrintN("                  The panel SCANS 800 across by 1280 down and no")
  PrintN("                  setting changes that, but it is mounted long")
  PrintN("                  edge across, so THE DEFAULT IS 90 - landscape,")
  PrintN("                  1280 by 800, 160 columns by 42 lines. IF THE")
  PrintN("                  PICTURE IS UPSIDE DOWN, type")
  PrintN("                  screen rotate 270 once: which of the two is the")
  PrintN("                  top depends on how the flat cable leaves the")
  PrintN("                  board, the setting is SAVED, and the panel comes")
  PrintN("                  up that way afterwards with nothing typed.")
  PrintN("                  Nobody rebuilds the monitor to turn a screen.")
  PrintN("                  THE COST, said every time you ask: this hardware")
  PrintN("                  has no 90 degree rotation - the video scaler can")
  PrintN("                  mirror but not turn - so 90 and 270 draw into a")
  PrintN("                  buffer of their own and transpose every repaint")
  PrintN("                  onto the panel, and a scroll becomes a full")
  PrintN("                  repaint. 0 and 180 move no pixel and keep the")
  PrintN("                  hardware scroll, and 0 is 100 columns by 72")
  PrintN("                  lines of THE SAME SIZE type, standing on its")
  PrintN("                  side - taller and narrower, not smaller. The")
  PrintN("                  letters are the same physical size at every")
  PrintN("                  rotation; see screen scale for why.")
  PrintN("                  Rotation is the panel's: HDMI is landscape as")
  PrintN("                  the firmware hands it over and is not turned.")
  PrintN("  screen scale [n|auto]")
  PrintN("                  how big the type is. IT IS NORMALLY COMPUTED:")
  PrintN("                  this monitor works out how many pixels there")
  PrintN("                  are to the inch on whatever screen it is")
  PrintN("                  drawing on - the diagonal in pixels over the")
  PrintN("                  diagonal in inches - and magnifies its 8 by 16")
  PrintN("                  font by the whole number nearest 0.110 inch to")
  PrintN("                  a line, which is what reads at a bench. Both of")
  PrintN("                  those are facts about the GLASS and neither")
  PrintN("                  changes when the picture is turned, which is")
  PrintN("                  why turning the console no longer changes the")
  PrintN("                  size of a letter. The DSI panel reports its own")
  PrintN("                  size over I2C - 10.1 inches, 149 pixels to the")
  PrintN("                  inch, magnification 1. NOTHING ON AN HDMI")
  PrintN("                  DISPLAY CAN SAY HOW BIG IT IS, so 24 inches is")
  PrintN("                  assumed and every report that uses it says so.")
  PrintN("                  screen scale <n> overrides all of that if it")
  PrintN("                  does not suit your eyes or your distance from")
  PrintN("                  the screen, and it is SAVED; screen scale auto")
  PrintN("                  forgets it and goes back to the calculation.")
  PrintN("                  The boot log and screen print the density, the")
  PrintN("                  magnification, the columns and rows, and the")
  PrintN("                  height of a line in inches.")
  PrintN("  screenshot                            [p]")
  PrintN("                  send a picture of the screen back over this wire.")
  PrintN("                  It is run-length encoded, because the raw picture")
  PrintN("                  would take twenty minutes at 115200 baud, and")
  PrintN("                  tools/pmfshot.py on the host turns it into a PNG.")
  PrintN("                  It takes several minutes. Only Ctrl-C stops it, so")
  PrintN("                  that a stray keypress cannot throw the capture")
  PrintN("                  away, and a stopped one is marked as stopped so")
  PrintN("                  the host never writes half a picture.")
  PrintNl()
  PrintN("OVER THE NETWORK")
  PrintN("  This board has a gigabit Ethernet socket and this is what it is for:")
  PrintN("  a 260 KB image takes twenty-four seconds down the serial line and well")
  PrintN("  under a second over the wire. It speaks TFTP, which is what every")
  PrintN("  board has been fetched over since 1981 and what U-Boot uses, so any")
  PrintN("  machine that can serve a file to a router can serve one to this.")
  PrintN("  get <name> [address]")
  PrintN("                  fetch a file from the TFTP server into memory. The")
  PrintN("                  name is the file as the server knows it; the address")
  Print("                  is hex and defaults to ")
  PutAddr(HwStageAddr())
  PrintN(", the same place load")
  PrintN("                  uses. The destination must be inside a payload window,")
  PrintN("                  and the transfer stops at that window's end rather")
  PrintN("                  than writing past it - a TFTP client does not know how")
  PrintN("                  long a file is until it ends, so the room is checked")
  PrintN("                  instead of the length.")
  PrintN("  put <name> <address> <length>")
  PrintN("                  send that many bytes of memory to the server as a")
  PrintN("                  file. Both numbers hex, the length in bytes. Most")
  PrintN("                  servers refuse to be written to until they are told to")
  PrintN("                  allow it, and the server's own refusal is printed here")
  PrintN("                  word for word when that happens.")
  PrintN("  net             the four addresses and the state of the wire. This is")
  PrintN("                  the command to type when get or put has failed,")
  PrintN("                  because it names the step that is missing.")
  PrintN("  net address <a.b.c.d>      the address this board answers to")
  PrintN("  net netmask <a.b.c.d>      also spelled net mask")
  PrintN("  net gateway <a.b.c.d>      also spelled net router. Use 0.0.0.0 when")
  PrintN("                             there is no router, which is the truth on a")
  PrintN("                             cable straight between two machines.")
  PrintN("  net server <a.b.c.d>       the machine serving the files")
  PrintN("  net dns <a.b.c.d>          the DNS resolver, for dns and ping by name")
  PrintN("  net up          bring the Ethernet up now and report every step. get")
  PrintN("                  and put do it themselves; this is the diagnostic.")
  PrintN("  net down        stop it. It is also stopped automatically before every")
  PrintN("                  run, because a payload must not share memory with a")
  PrintN("                  controller that is still writing into it.")
  PrintN("  net forget      take all four addresses back out")
  PrintN("  net stats       WHAT THE NETWORK CONTROLLER ITSELF COUNTED on the")
  PrintN("                  interface now in use - pause frames sent and received,")
  PrintN("                  framing errors, dropped frames, and how many times the")
  PrintN("                  link has been brought up or seen to drop. A counter")
  PrintN("                  that reads zero is not printed, so anything you see is")
  PrintN("                  a number worth reading. This is the command to type")
  PrintN("                  when the MACHINE AT THE OTHER END of a cable is")
  PrintN("                  misbehaving: net says what this monitor did, net stats")
  PrintN("                  says what the hardware saw. Also spelled net counters.")
  PrintN("  net recv <port> <addr> [max-length]")
  PrintN("                  RECEIVE ONE IMAGE OVER A TCP CONNECTION, into memory")
  PrintN("                  at that address, and print how many bytes arrived and")
  PrintN("                  the SHA-256 of what is now in that memory. This is the")
  PrintN("                  fast way in: the same image over the serial line at")
  PrintN("                  115200 is about two minutes. The port is decimal and")
  PrintN("                  the address is hexadecimal; leave the length out and")
  PrintN("                  the rest of that payload window is the ceiling.")
  PrintN("                  The listener is opened for ONE connection and closed")
  PrintN("                  again whatever happens, nothing is booted, and nothing")
  PrintN("                  is written to the medium - boot mem <addr> enters a")
  PrintN("                  container and save <name> <addr> <len> writes a file.")
  PrintN("                  A peer that sends more than the window holds is cut")
  PrintN("                  off AT the last allowed byte, never past it.")
  PrintN("  ping <host>     send ICMP echo requests and time the replies, one a")
  PrintN("                  second, until a key is pressed. The host is a dotted-")
  PrintN("                  quad, or a name if a DNS server is set. It prints each")
  PrintN("                  reply's measured round trip and a loss/min/avg/max")
  PrintN("                  summary at the end.")
  PrintN("  dns <hostname>  look a name up and print the address(es). Needs a DNS")
  PrintN("                  server - net dns, or dhcp. Refuses honestly with none.")
  PrintN("  dhcp            acquire an address by DHCP and report the IP, netmask,")
  PrintN("                  gateway, DNS server and lease. On success it sets the")
  PrintN("                  interface's runtime lease, so ping and dns work at once.")
  PrintN("                  DHCP option 42 is retained per lease for the")
  PrintN("                  nonblocking SNTP clock service when a server supplies it.")
  PrintN("                  It does not overwrite saved static addresses or set a")
  PrintN("                  TFTP server, so get and put still need net server.")
  PrintN("  The four addresses live in the settings store, under net.address,")
  PrintN("  net.netmask, net.gateway and net.server, so settings save keeps them")
  PrintN("  and settings load brings them back. Coming from U-Boot, those four are")
  PrintN("  its ipaddr, netmask, gatewayip and serverip.")
  PrintN("  tftpboot and tftpput are NOT accepted as aliases, deliberately.")
  PrintN("  U-Boot takes the address first and the name second and this monitor")
  PrintN("  takes the name first, to match its own load and save. An alias whose")
  PrintN("  arguments mean something else is worse than no alias: a line pasted")
  PrintN("  out of a U-Boot session would run, and fetch a file called 0x400000.")
  PrintNl()
  PrintN("SETTINGS THAT SURVIVE A POWER CYCLE")
  PrintN("  This is what U-Boot's printenv, setenv and saveenv were for, and those")
  PrintN("  three names now work here too, over this same store:")
  PrintN("    printenv [name...]         settings show, or the named settings")
  PrintN("    setenv <name> <value>      settings set. With no value it does NOT")
  PrintN("                               delete (U-Boot does) - use settings")
  PrintN("                               remove, so a keystroke cannot quietly")
  PrintN("                               destroy a setting.")
  PrintN("    saveenv                    settings save")
  PrintN("    env print / set / save / load / delete <name>")
  PrintN("                               the same, spelled U-Boot's env <sub> way")
  PrintN("    env exists <name>          say whether one is set")
  PrintN("    env grep <text>            list the ones whose name or value has it")
  PrintNl()
  PrintN("  THE PERSISTED BOOT TARGET lives in this same store, as four names:")
  PrintN("    boot.file       the container to boot at start-up, e.g. APP.PMF.")
  PrintN("                    Unset, this board goes straight to its prompt and")
  PrintN("                    runs nothing by itself - and waits for nothing,")
  PrintN("                    because a countdown that can only end one way")
  PrintN("                    teaches people to ignore countdowns.")
  PrintN("    boot.delay      seconds to count down first. Default 2. Any key")
  PrintN("                    during it drops to this prompt, and the failure")
  PrintN("                    counter is not touched - nothing was attempted.")
  PrintN("    boot.fails      attempts since anything last confirmed a good")
  PrintN("                    boot. THE REBOOT-LOOP GUARD. It is written to the")
  PrintN("                    medium BEFORE each attempt, not after, because a")
  PrintN("                    payload that hangs never gets to an after.")
  PrintN("    boot.maxfails   how many attempts before this monitor stops")
  PrintN("                    trying and says why. Default 3.")
  PrintN("  A payload marks itself good by getting boot.fails back to 0. The")
  PrintN("  operator types boot ok; a payload that RETURNS can have the operator")
  PrintN("  do it; a payload that keeps the board writes the setting through this")
  PrintN("  same store before it takes over - set boot.fails to 0 and save. The")
  PrintN("  guard exists because a bootloader that enters a payload automatically")
  PrintN("  has invented a way to lose a board: a payload that hangs is re-entered")
  PrintN("  every start, and there is then never a prompt long enough to fix it.")
  PrintN("    setenv boot.file APP.PMF")
  PrintN("    saveenv")
  PrintN("  is the whole of arming it.")
  PrintN("  A password is still masked by printenv, the same as settings show,")
  PrintN("  because this output reaches the HDMI console and the next screenshot;")
  PrintN("  settings reveal prints one in full. Up to")
  PrintN("  thirty-two names and values, kept in memory and written to a plain")
  PrintN("  text file called SETTINGS.TXT in the root of the boot medium. That")
  PrintN("  file opens in any text editor on any computer, which is the recovery")
  PrintN("  story: a board that will not boot because of something in its")
  PrintN("  settings is fixed by pulling the stick and deleting a line.")
  PrintN("  settings                              [settings show]")
  PrintN("                  list everything. Anything whose name contains")
  PrintN("                  password, passphrase or secret is HIDDEN, because")
  PrintN("                  this output also goes to the HDMI console and into")
  PrintN("                  the next screenshot. The true length is shown.")
  PrintN("  settings set <name> <value>")
  PrintN("                  the value is the whole rest of the line, so it may")
  PrintN("                  contain spaces. The input line is 144 characters,")
  PrintN("                  which is the longest legal one of these - a")
  PrintN("                  31-character name and a 95-character value - so")
  PrintN("                  nothing has to be set by editing the file any more.")
  PrintN("  settings remove <name>")
  PrintN("  settings reveal <name>")
  PrintN("                  print one in full, hidden or not. The deliberate")
  PrintN("                  keystroke that puts a password on the screen.")
  PrintN("  settings save   write SETTINGS.TXT to the boot medium. USB only, and")
  PrintN("                  the only command here that can write anything. The")
  PrintN("                  whole file is rewritten, so hand-typed comments in it")
  PrintN("                  are lost.")
  PrintN("  settings load   read it back. Nothing loads it for you: bringing the")
  PrintN("                  medium up is slow and noisy and the prompt comes")
  PrintN("                  first.")
  PrintN("  settings discard")
  PrintN("                  a load that hit a bad line stops there and blocks the")
  PrintN("                  next save, because saving would delete the lines it")
  PrintN("                  never read. This says throw them away.")
  PrintN("  wifi            list every network slot, passphrases hidden. wifi")
  PrintN("                  show is the same command spelled out. FOUR networks")
  PrintN("                  can be stored and THE SLOT NUMBER IS THE ORDER THEY")
  PrintN("                  WOULD BE TRIED IN - slot 1 first. Put the one you")
  PrintN("                  most want joined in slot 1.")
  PrintN("  wifi ssid <slot> <name>")
  PrintN("                  the name is the rest of the line, so it may contain")
  PrintN("                  spaces. One to thirty-two characters.")
  PrintN("  wifi phrase <slot> <phrase>")
  PrintN("                  the passphrase for that slot, the rest of the line,")
  PrintN("                  8 to 63 characters, and STORED IN PLAIN TEXT - the")
  PrintN("                  command says so at length every time. Give this")
  PrintN("                  board a guest network. It is a DIFFERENT WORD from")
  PrintN("                  wifi password because that one takes the whole rest")
  PrintN("                  of the line, so a slot number in front of it could")
  PrintN("                  not be told from the start of a passphrase.")
  PrintN("  wifi find <name>")
  PrintN("                  which slot holds that name. The comparison is EXACT:")
  PrintN("                  case counts and a 2.4ghz suffix is part of the name,")
  PrintN("                  because two real networks here differ by no more.")
  PrintN("  wifi forget <slot>")
  PrintN("                  clear one slot, name and passphrase together. The")
  PrintN("                  others do not move up - the numbers are a preference")
  PrintN("                  order and renumbering them would change it.")
  PrintN("  wifi keys       the settings names the slots live under, to hand to")
  PrintN("                  settings reveal.")
  PrintN("  The single network this monitor used to keep is still there and is")
  PrintN("  still READ - LAST, after every numbered slot - so a stick written by")
  PrintN("  an older build keeps working and no saved passphrase went missing:")
  PrintN("  wifi network <name>       the name is the rest of the line")
  PrintN("  wifi password <phrase>    also spelled wifi passphrase")
  PrintN("  wifi forget     take that pair back out. It does NOT touch the slots.")
  PrintN("  wifi scan       bring the radio up and list the stored networks that")
  PrintN("                  are on the air now (needs BRCMFW.BIN, BRCMNV.TXT and")
  PrintN("                  BRCMCLM.BLB on the stick).")
  PrintNl()
  PrintN("THE BOARD")
  PrintN("  gpio [status] [all | <pin>]")
  PrintN("                  report the general-purpose I/O pins: each pin's")
  PrintN("                  function, its level read back from the actual pad, and")
  PrintN("                  its pull. With no argument it shows the user-header")
  PrintN("                  pins; gpio all shows every line the board has; gpio")
  PrintN("                  with a pin number shows one. status is the default and")
  PrintN("                  may be written out (gpio status, gpio status all, gpio")
  PrintN("                  status 21). Reading any pin is always allowed.")
  PrintN("  gpio set <pin>")
  PrintN("  gpio clear <pin>")
  PrintN("                  drive a pin high or low. This makes the pin an output,")
  PrintN("                  and says so. The line printed back is the ACTUAL pad")
  PrintN("                  read after the write, not what was asked for.")
  PrintN("  gpio toggle <pin>")
  PrintN("                  invert an output pin. A pin that is not already an")
  PrintN("                  output has nothing to invert and is refused - use set")
  PrintN("                  or clear to start driving one.")
  PrintN("  gpio output <pin>")
  PrintN("  gpio input <pin>")
  PrintN("                  set the pin's direction, without driving a level.")
  PrintN("                  PINS ARE DECIMAL, like clock and unlike the memory")
  PrintN("                  commands - a GPIO number is written in decimal on the")
  PrintN("                  header and in the datasheet. A leading 0x or $ still")
  PrintN("                  forces hex.")
  PrintN("                  A WRITE to a pin the board itself is using is refused")
  PrintN("                  with a sentence naming the function, not a silent no-op:")
  PrintN("                  on this board that is the serial console (GPIO 14/15)")
  PrintN("                  and the Wi-Fi/Bluetooth radio's bus (GPIO 34-39). The")
  PrintN("                  micro-SD card is on a dedicated socket, not a GPIO, so")
  PrintN("                  it needs no such guard.")
  PrintN("                  A board with no GPIO says so and does nothing, because")
  PrintN("                  Anvil is one monitor across many boards and not every")
  PrintN("                  board has pins to report.")
  PrintN("  fan [status]")
  PrintN("  fan pin <gpio> | none")
  PrintN("  fan auto | off | on | <percent>")
  PrintN("  fan curve <lowF> <highF>")
  PrintN("  fan hyst <degreesF>")
  PrintN("  fan hz <n>")
  PrintN("                  the fan, the part's own temperature, and the curve")
  PrintN("                  between them. EVERY TEMPERATURE HERE IS FAHRENHEIT,")
  PrintN("                  typed and printed. fan on its own prints the reading in")
  PrintN("                  whole degrees F, with the celsius and the raw")
  PrintN("                  millidegrees in brackets so the number can be checked")
  PrintN("                  against a datasheet or another tool; which of the")
  PrintN("                  board's two thermometers answered; the mode, the duty,")
  PrintN("                  the pin, and the pins the board will drive - a star")
  PrintN("                  marks the")
  PrintN("                  ones with a real modulator behind them, which are")
  PrintN("                  steady at any frequency and are what a four-wire fan")
  PrintN("                  wants; the rest are toggled by software from this")
  PrintN("                  prompt's own idle loop, which is fine for a two-wire")
  PrintN("                  fan on a transistor and is COARSE - it stops")
  PrintN("                  modulating while a long command runs and parks the pin")
  PrintN("                  at the level the board considers safe.")
  PrintN("                  NO PIN IS DRIVEN UNTIL ONE IS NAMED. The board does")
  PrintN("                  not know where a fan is wired, so fan pin <gpio> is")
  PrintN("                  the first thing to type and it is remembered.")
  PrintN("                  auto lets the curve decide: off below the low")
  PrintN("                  temperature, ramping to full at the high one, with a")
  PrintN("                  few degrees of hysteresis so it does not hunt, a brief")
  PrintN("                  full-speed kick to get a stationary fan turning, and")
  PrintN("                  FULL SPEED whenever no temperature can be read at all.")
  PrintN("                  It starts at off below 113 F, full at 158 F, with 5 F")
  PrintN("                  of hysteresis - which is where this part idles quiet")
  PrintN("                  and where it still has headroom before the firmware")
  PrintN("                  starts slowing it down at 185 F.")
  PrintN("                  off and on override it; a bare percentage holds a duty.")
  PrintN("                  Degrees, percentages, pins and hertz are all DECIMAL.")
  PrintN("                  A CURVE SAVED BY A BUILD FROM BEFORE 2026-09-07 IS IN")
  PrintN("                  CELSIUS. It is converted on the way in and the boot log")
  PrintN("                  says so; type settings save to write the converted")
  PrintN("                  numbers back.")
  PrintN("                  Settings are remembered in the table but NOT written to")
  PrintN("                  the file until settings save, like every other setting.")
  PrintN("                  A board with no modulator, or no thermometer, says so")
  PrintN("                  and does nothing.")
  PrintN("  i2c probe")
  PrintN("  i2c read  <addr> <reg> [count]")
  PrintN("  i2c write <addr> <reg> <byte...>")
  PrintN("  i2c speed [hz]")
  PrintN("                  talk to devices on the header I2C bus (SDA/SCL on")
  PrintN("                  GPIO 2 and 3). probe lists every 7-bit address that")
  PrintN("                  answers; read points a device at a register and reads")
  PrintN("                  count bytes (default 1); write sends a register then")
  PrintN("                  one or more data bytes. Addresses, registers, bytes")
  PrintN("                  and count are HEX; the speed is DECIMAL, like clock.")
  PrintN("                  A register read puts a STOP between the pointer write")
  PrintN("                  and the read, not a repeated start, so a device that")
  PrintN("                  needs a repeated start will not read right. On a NACK")
  PrintN("                  or a wedged bus it says which one happened and that it")
  PrintN("                  did nothing. A board with no I2C says so and does")
  PrintN("                  nothing. The clock rate shown is derived from the")
  PrintN("                  divider source MEASURED on the pin, not the nominal.")
  CompilerIf #CAP_TOUCH = 1
  PrintN("  touch [points | panel power|prepare|light <n>|reset |")
  PrintN("         bus display|header | axes <s> <x> <y>]")
  PrintN("                  the DSI panel's touch controller and its power MCU.")
  PrintN("                  NOT the bus above: this one is BSC0 on GPIO 44 and 45")
  PrintN("                  at ALT1, the display and camera connectors, and it is")
  PrintN("                  the default here because that is where the panel is")
  PrintN("                  plugged in. No jumper wires. It puts the header bus")
  PrintN("                  back when it finishes so i2c never names the wrong")
  PrintN("                  pair of wires. touch on its own says what answered and")
  PrintN("                  what it is, and prints the pads before and after the")
  PrintN("                  mux - both lines low on THIS bus is a cable answer,")
  PrintN("                  because its pull-ups are on the panel board. panel")
  PrintN("                  power is the MCU's own probe write; panel prepare is")
  PrintN("                  the panel's rails and reset; panel light takes a")
  PrintN("                  DECIMAL 0 to 255 and is NOT inverted on this")
  PrintN("                  generation; panel reset pulses the touch chip's reset,")
  PrintN("                  which is a pin on that MCU and on no Pi GPIO - so the")
  PrintN("                  touch chip cannot answer until panel power has run.")
  PrintN("                  points reports live coordinates until a key is pressed.")
  PrintN("                  axes sets the mapping from the controller's frame to")
  PrintN("                  the screen's, three 0-or-1 numbers, because the default")
  PrintN("                  is read out of a device tree and has never been checked")
  PrintN("                  against a finger.")
  CompilerEndIf
  PrintN("  mmc [info | read <blk> <addr> [count] | write <blk> <addr> [count]]")
  PrintN("                  raw block access to the SD card, with no filesystem -")
  PrintN("                  this is the card underneath mount/load, seen as 512-byte")
  PrintN("                  blocks. mmc on its own, or mmc info, prints the card's")
  PrintN("                  class, block size, block count and capacity. mmc read")
  PrintN("                  copies count blocks (default 1) from the card at block")
  PrintN("                  <blk> into RAM at <addr>; mmc write copies them the other")
  PrintN("                  way, from RAM onto the card. ALL THREE NUMBERS ARE HEX -")
  PrintN("                  <blk> a block index, <addr> a RAM byte address, <count> a")
  PrintN("                  number of blocks. The RAM address must be 4-byte aligned")
  PrintN("                  and a range that touches the monitor is refused, both for")
  PrintN("                  read and for write. mmc write is destructive and")
  PrintN("                  unconditional: it overwrites raw blocks, a filesystem")
  PrintN("                  included, with no undo and no are-you-sure. A board with")
  PrintN("                  no card controller says so and does nothing; a board that")
  PrintN("                  can read but not write refuses mmc write and says why.")
  PrintN("  usb [info | tree | storage | read <blk> <addr> [count]]")
  PrintN("                  look at the USB bus. usb, or usb info, lists the host")
  PrintN("                  controller, the ports and every device that answered")
  PrintN("                  enumeration - its speed, its VID:PID and its class. usb")
  PrintN("                  tree draws the topology: controller, root ports, the")
  PrintN("                  internal hub and its ports. usb storage reports a")
  PrintN("                  memory stick's vendor, block size and capacity. usb")
  PrintN("                  read pulls raw 512-byte blocks off the stick straight")
  PrintN("                  into memory, without a filesystem: the block number,")
  PrintN("                  the destination and the count are ALL hexadecimal, and")
  PrintN("                  the destination is range-checked against the payload")
  PrintN("                  windows exactly like load. It shows what the stack")
  PrintN("                  already drives for mount and the cursor; it starts and")
  PrintN("                  resets nothing. A board with no USB host says so and")
  PrintN("                  does nothing.")
  PrintN("  baud [rate]")
  PrintN("                  change how fast this serial line runs. The clock")
  PrintN("                  feeding the serial port on this board is 48 MHz,")
  PrintN("                  so 1500000 and 3000000 divide into it exactly -")
  PrintN("                  thirteen and twenty-six times the default. Reopen")
  PrintN("                  the port at the new rate and press Enter. If")
  PrintN("                  nothing answers within eight seconds the board")
  PrintN("                  puts 115200 back by itself, so a rate your adapter")
  PrintN("                  cannot manage costs a pause and not a power cycle.")
  PrintN("  reset                                 [r, reboot]")
  PrintN("                  reset the board immediately. The firmware reloads")
  PrintN("                  this monitor from the stick. There is no are-you-sure")
  PrintN("                  question, on purpose: the cost of being wrong is")
  PrintN("                  a five second reboot into a working loader.")
  PrintN("  help                                  [h, ?, commands]")
  PrintN("                  print this. A question mark on its own does the")
  PrintN("                  same thing.")
  PrintNl()
  PrintN("WHERE A PAYLOAD MAY GO")
  PrintN("These are the two windows of memory a payload may be loaded into:")
  PutWindows()
  ; NOT "the gap is U-Boot" - the firmware boots this monitor directly and
  ; U-Boot is not loaded at all. What is actually in the gap is this
  ; monitor's own image and stack, the parked cores' release mailboxes,
  ; and a stretch with no DRAM behind it. Same advice, true reasons.
  PrintN("  The gap between them holds this monitor, the three parked processor")
  PrintN("  cores, and a stretch where there is no DRAM at all. A payload may not")
  PrintN("  straddle that gap, and one that tries is refused rather than half")
  PrintN("  written.")
  ; EVERY REGION IS PRINTED, NOT JUST THE IMAGE, AND NONE OF IT IS
  ; SPELT INTO PROSE. This paragraph used to name two constants and
  ; describe "the two-megabyte window", which stopped being true on
  ; 2026-09-08: the monitor is a kernel and its extent is whatever the
  ; image is, so the numbers are a measurement the running program takes
  ; of itself. PutMonitorMap() is where that measurement is laid out,
  ; and the banner and `map` print the same one.
  PrintN("WHAT THIS MONITOR OWNS")
  PutMonitorMap()
  PrintN("  Every command that writes memory refuses to write into any of it,")
  PrintN("  and the refusal names the region.")
  ; THE BUILD ADDRESS IS NOT THE PLACEMENT, AND SAYING SO HERE SAVES A
  ; REBUILD - 2026-09-08. This used to read "build payloads with
  ; --load-addr <the staging address>", which is advice a reader has to
  ; take again every time this monitor crosses a megabyte. They do not:
  ; A64 output is position-independent, so the same source built for two
  ; different addresses is byte for byte the same file (proved
  ; whole-image by a64_nosizecap_check case 9). What has to be right is
  ; WHERE IT IS PUT, and that is the staging line above.
  PrintN("  Load a payload at the staging address on that line, whatever it was")
  PrintN("  built for: an image is the same bytes at any --load-addr, so one")
  PrintN("  made last month wants staging here rather than rebuilding. Leave")
  PrintN("  512 KiB above the base clear - that is where its own uninitialised")
  PrintN("  data goes, and nothing here checks it for you.")
  Print("  The other window starts at 0x")
  PutAddr(HwPayLo(1))
  PrintN(".")
  PrintN("  Add --entry-returns if you want the payload to come back to this")
  PrintN("  prompt and have its x0 register printed. A stock image never comes")
  PrintN("  back at all.")
EndProcedure

; ----------------------------------------------------------------------
;  Banner - the FIRST thing an operator ever reads, and until forum 575
;  it described one particular computer whatever it was running on.
;
;  Three claims used to be literal prose here: the board's name, that the
;  console is a PL011 at #UART_BASE, and "at exception level 2". On the
;  second board every one of them was false - it is not a Pi 4, it has no
;  PL011 (the constant has no meaningful value there and printed
;  00000000), and it runs at EL1. That board answered by carrying its own
;  banner, which is a fork of the monitor's own product text and would
;  have to be written again for every board after it.
;
;  Now the core asks. PutIdLine() and PutProcessorLine() live in
;  Anvil/Core/flow_cmd.pbi so that this banner and `version` name the
;  board through the same two procedures and cannot describe two
;  different computers; HwIdSayConsole() is the board's own paragraph,
;  the same shape as HwAddrReport() and HwStorageReport(). Nothing below
;  this line names a chip.
; ----------------------------------------------------------------------
Procedure Banner()
  Define e.i
  PrintNl()
  PutIdLine()
  UartWriteStr(AnvilBuildLabel(#ANVIL_BUILD, #ANVIL_BUILD_DATE, #ANVIL_BUILD_TIME))
  PrintNl()
  HwIdSayConsole()
  PutProcessorLine()
  ; THE BANNER NAMES THE RUNNING IMAGE, NOT A RESERVED WINDOW - and
  ; until 2026-09-08 it could not. It printed "monitor 00200000", a
  ; constant, and board.pi4 recorded in as many words that the line
  ; "names the PROTECTED WINDOW, not the running image" because the
  ; running base was not knowable. It is now: the image carries
  ; __image_start__ / __image_end__ and HwMonLo()/HwMonHi() read them.
  Print("This monitor occupies ")
  PutAddr(HwMonLo())
  Print(" to ")
  PutAddr(HwMonHi())
  Print(" - ")
  PrintDec(HwMonBytes())
  PrintN(" bytes, from the image -")
  Print("with its stack growing down from ")
  PutAddr(HwMonStack())
  PrintN(". Type map for the whole of it.")
  PrintN("A payload may be loaded into either of these:")
  PutWindows()
  Print("The tick counter every timeout here is measured on runs at ")
  PrintDec(TickHz())
  PrintN(" Hz.")
  PrintN("Type info to see what board this is, or help for the list of commands.")

  ; ---- THE SCREEN, IF THERE IS ONE --------------------------------
  ; Tried once, at startup, without being asked. Anvil holding the
  ; machine and leaving the monitor dark is the wrong default: the
  ; screen is the one output a person can see without a second computer
  ; and a USB-serial cable.
  ;
  ; The screen is NOT turned on here any more. It is turned on in Main,
  ; AFTER BootBringUp, so the Wi-Fi bring-up runs while the HDMI
  ; framebuffer is still off and the VideoCore mailbox is uncontended -
  ; the EMMC-clock query the radio needs fails when the framebuffer is
  ; up (the MBOX1 wedge). Proper order: banner, devices, screen, prompt.
  e = AutoEntry()
  If e <> 0
    Print("autoboot armed at ")
    PutAddr(e)
    PrintNl()
  EndIf
EndProcedure

; ======================================================================
;  Main - NEVER RETURNS. See the stack note in the header.
; ======================================================================

; ----------------------------------------------------------------------
;  BootBringUp - a mini-kernel brings its devices up AT BOOT, in order,
;  rather than the first time a command happens to reach for one.
;
;  The order: 'yes bring up usb at boot then do the keyed join', and 'this is
;  the basis for a mini kernel'.
;
;  THE ORDER MATTERS AND IS THE POINT:
;    1. USB - one controller bring-up, the mouse, the keyboard and the
;       boot stick all attached together (UsbEnumerate).
;    2. the stick mounted and SETTINGS.TXT read, so the stored Wi-Fi
;       networks and everything else are in memory from the prompt - and
;       the 'Mounted the USB stick' line lands HERE, at boot, where it
;       makes sense, instead of appearing the first time someone scans
;       for Wi-Fi.
;    3. the Wi-Fi join (added next), which runs here BECAUSE the HDMI
;       framebuffer is not up yet: the mailbox is uncontended, so the
;       EMMC-clock query the radio needs does not have to fight it.
;
;  Nothing here is fatal. A board with no stick still reaches the prompt;
;  it just says so. The screen is still off at this point, so this is all
;  on the serial line until 'screen on'.
; ----------------------------------------------------------------------
