#!/usr/bin/env python3
"""gen_anvil_pic.py - the real anvil photo, scaled on the host, into a
Data.b table Anvil blits straight to the framebuffer.

    python tools/gen_anvil_pic.py [source.png]

This replaces the 32x19 one-bit silhouette (gen_anvil_logo.py) with the
actual picture. WHY ON THE HOST AND NOT ON THE BOARD: the board could
scale it with V3D, but V3dInit poisons the firmware property mailbox
until a reset and the resident monitor needs that mailbox (info's
temperature and clock rates), so the scaling is done here, once, at build
time, and the board only blits fixed pixels.

WHY RGB PRE-COMPOSITED ON THE BAND COLOUR. The banner background is
DisplayRGB(0,0,40) - navy. The anvil is grey metal on transparency; its
anti-aliased edges must fade into that navy, not into black, or the logo
sits in a dark box. So the alpha is composited against the exact band
colour here and the result stored as plain R,G,B, blitted through
DisplayRGB() so the display's own pixel order (BGR vs RGB) still applies.
"""
import os
import sys
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO, "RaspberryPi4", "Monitor", "anvil_logo.png")
OUT = os.path.join(REPO, "RaspberryPi4", "Monitor", "anvil_logo.pi4")

# Must match gScreenBg in anvil.pi4: DisplayRGB(0, 0, 40).
BAND = (0, 0, 40)

# Fits the 120 px banner with the "A N V I L" label under it: 12 top
# margin + H + 6 + 16 label must clear the rule at 114.
TARGET_W = 76


def main():
    im = Image.open(SRC).convert("RGBA")
    im = im.crop(im.split()[3].getbbox())            # trim to the opaque anvil
    w = TARGET_W
    h = round(w * im.height / im.width)
    im = im.resize((w, h), Image.LANCZOS)

    bg = Image.new("RGBA", (w, h), BAND + (255,))
    rgb = Image.alpha_composite(bg, im).convert("RGB")
    px = rgb.load()

    body = []
    for y in range(h):
        row = []
        for x in range(w):
            r, g, b = px[x, y]
            row.append("$%02X,$%02X,$%02X" % (r, g, b))
        body.append("  Data.b " + ",".join(row))

    lines = []
    a = lines.append
    a("; ======================================================================")
    a(";  THE ANVIL PICTURE - %d x %d, R,G,B per pixel, row-major." % (w, h))
    a(";")
    a(";  GENERATED by tools/gen_anvil_pic.py from anvil_logo.png. Do not")
    a(";  hand-edit. Blitted once, at boot, by DrawAnvilPic in anvil.pi4;")
    a(";  read with PeekA(?anvilPix + ...), never Read/Restore (Read strides")
    a(";  two bytes whatever the width - Bugs/Open bugs.md).")
    a(";")
    a(";  Pre-composited on the banner colour DisplayRGB(0,0,40) so the")
    a(";  anti-aliased edges fade into the band, not into a black box.")
    a("; ======================================================================")
    a("#ANVIL_PIC_W = %d" % w)
    a("#ANVIL_PIC_H = %d" % h)
    a("")
    a("DataSection")
    a("anvilPix:")
    lines.extend(body)
    a("EndDataSection")
    a("")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("%s: %d x %d, %d bytes of pixel data" % (OUT, w, h, w * h * 3))


if __name__ == "__main__":
    main()
