#!/usr/bin/env python3
"""gen_anvil_logo.py - the anvil silhouette, as art, into 32-bit row masks.

    python tools/gen_anvil_logo.py            regenerate the masks
    python tools/gen_anvil_logo.py preview.png  ... and render a preview

WHY ART AND NOT RECTANGLES. A silhouette is a shape, and a shape is far
easier to get right by looking at it than by reasoning about a list of
fill calls. Edit ART below, regenerate, look at the preview. The hex in
the generated output is never hand-edited.

THE PREVIEW EARNED ITS KEEP IMMEDIATELY. The first version of this anvil
looked fine as characters in a terminal and rendered on the board as an
hourglass: the face and the base were the same width, so the waist read
as a pinch in a symmetric object rather than as the underside of a
slab. An anvil is not symmetric - the face is the widest part, the horn
is a point on one side of it, and the base is narrower than the face.
Checking that on the host takes a second; checking it on the board takes
a reload, a screenshot and four minutes.
"""
import binascii
import io
import os
import struct
import sys
import zlib

# THE PROFILE, as a left and right column per row, because that is what
# actually controls the shape. Hand-drawn rows kept getting the RIGHT
# edge wrong: leaving it fixed while the left edge marched inward makes
# a wedge, not a waist. A waist narrows from BOTH sides.
#
#              row range      left  right
BODY = [
    ((0, 5),   6, 29),      # the face - the widest part of an anvil
    ((6, 6),   8, 27),      # underside of the face, starting to draw in
    ((7, 7),  11, 24),
    ((8, 12), 14, 20),      # the waist
    ((13, 13), 12, 22),     # flaring out to the foot
    ((14, 14), 9, 25),
    ((15, 18), 6, 27),      # the base, narrower than the face
]

# The horn: a taper to a single point on the LEFT, overlaid on the face.
# Row, and how far left of the face it reaches.
HORN = [(1, 4), (2, 2), (3, 0), (4, 0), (5, 3)]

W = 32
H = 19


def build():
    grid = [["."] * W for _ in range(H)]
    for (r0, r1), l, r in BODY:
        for y in range(r0, r1 + 1):
            for x in range(l, r + 1):
                grid[y][x] = "#"
    for y, left in HORN:
        for x in range(left, 7):
            grid[y][x] = "#"
    return ["".join(row) for row in grid]


ART = chr(10).join(build())


def rows_of(art):
    rows = [r for r in art.split("\n") if r.strip()]
    w = max(len(r) for r in rows)
    return [r.ljust(w, ".") for r in rows], w


def emit(rows, w, h, path):
    out = []
    a = out.append
    a("; ----------------------------------------------------------------------")
    a(";  THE ANVIL, %d x %d cells, one bit per cell." % (w, h))
    a(";")
    a(";  GENERATED by tools/gen_anvil_logo.py from ASCII art. Edit the art")
    a(";  there and regenerate; do not hand-edit the hex. The art is repeated")
    a(";  beside each row so the shape is readable here too.")
    a(";")
    a(";  One 32-bit mask per row, most significant bit at the LEFT, so the")
    a(";  hex reads in the same direction as the picture.")
    a(";")
    a(";  The face is the widest part, the horn is a point on its left, and")
    a(";  the base is narrower than the face. That asymmetry is the whole")
    a(";  difference between an anvil and an hourglass - the first attempt")
    a(";  had the face and base equal and rendered as the latter.")
    a("; ----------------------------------------------------------------------")
    a("#LOGO_W = %d" % w)
    a("#LOGO_H = %d" % h)
    a("")
    a("Global Dim gLogo.i[%d]" % h)
    a("")
    a("Procedure LogoInit()")
    for i, r in enumerate(rows):
        v = 0
        for c, ch in enumerate(r):
            if ch == "#":
                v |= 1 << (31 - c)
        a("  gLogo[%2d] = $%08X   ; %s" % (i, v, r))
    a("EndProcedure")
    io.open(path, "w", encoding="utf-8", newline="\r\n").write("\n".join(out) + "\n")


def png(width, height, rgb_rows, path):
    def chunk(tag, data):
        c = tag + data
        return (struct.pack(">I", len(data)) + c +
                struct.pack(">I", binascii.crc32(c) & 0xFFFFFFFF))
    raw = bytearray()
    for row in rgb_rows:
        raw.append(0)
        raw.extend(row)
    with open(path, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n" +
                chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)) +
                chunk(b"IDAT", zlib.compress(bytes(raw), 9)) +
                chunk(b"IEND", b""))


def preview(rows, w, h, path, scale=6):
    metal = (200, 208, 220)
    bg = (0, 0, 40)
    out = []
    for r in rows:
        line = bytearray()
        for ch in r:
            line.extend(bytes(metal if ch == "#" else bg) * scale)
        for _ in range(scale):
            out.append(bytes(line))
    png(w * scale, h * scale, out, path)


def main():
    rows, w = rows_of(ART)
    h = len(rows)
    assert w <= 32, "the mask is 32 bits wide, art is %d" % w
    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "_work", "logo_gen.pi4")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    emit(rows, w, h, out)
    print("%d x %d -> %s" % (w, h, out))
    for r in rows:
        print("   " + r)
    if len(sys.argv) > 1:
        preview(rows, w, h, sys.argv[1])
        print("preview -> %s" % sys.argv[1])
    return 0


if __name__ == "__main__":
    sys.exit(main())
