#!/usr/bin/env python
# ----------------------------------------------------------------------
# gen_bignum_vectors.py - emit the i15 big-integer self-test vectors.
#
# The M7 vector gate needs known-answer cases for the bignum
# module, generated by a trustworthy oracle rather than by running the
# code under test. Python 3.14's arbitrary-precision integers ARE that
# oracle: every expected value below is pow()/%/<< on native big ints,
# and the limb math for add/sub is reproduced exactly in base 2^15.
#
# It writes an identical bignumVectors.<ext> into each family's
# Diagnostics folder (the vectors are portable; the self-test that reads
# them is built per family). The self-test walks each DataSection with
# Restore/Read and checks the library's output byte-for-byte.
#
# Usage:  python tools/gen_bignum_vectors.py
# ----------------------------------------------------------------------
import os, random

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

OUT = [
    ("RP2350/Examples/Diagnostics/bignumVectors.pico2",  "RP2350"),
    ("RP2040/Examples/Diagnostics/bignumVectors.pico",   "RP2040"),
    ("RA4M1AndRelated/Examples/Diagnostics/bignumVectors.unor4", "Uno R4"),
]

rng = random.Random(0x1517_2026)   # fixed seed: deterministic vectors

# P-256 field prime, the one modulus the whole TLS profile actually uses.
P256 = (2**256 - 2**224 + 2**192 + 2**96 - 1)

def odd(bits):
    n = rng.getrandbits(bits) | (1 << (bits - 1)) | 1
    return n

# Modulus table (all odd; montmul/modpow require odd moduli).
MODS = [
    P256,                 # idx 0 : 256-bit prime (P-256 field)
    odd(256),             # idx 1 : 256-bit odd
    odd(2048),            # idx 2 : 2048-bit odd
    odd(3072),            # idx 3 : 3072-bit odd
]

def i15_words(menc_bits):
    return (menc_bits + 15) // 16 if False else None  # placeholder, unused

def be(n, nbytes):
    return n.to_bytes(nbytes, "big")

def bytelen(n):
    return max(1, (n.bit_length() + 7) // 8)

def mod_bytes(n):
    # full word-aligned byte length so BnEncode of any x < n round-trips
    words = (n.bit_length() + 14) // 15
    return (words * 15 + 7) // 8

# ---- build cases -----------------------------------------------------

roundtrip = []      # (raw_bytes,)
for L in (1, 2, 3, 7, 15, 16, 17, 31, 32, 33, 64, 128, 256):
    roundtrip.append(bytes(rng.getrandbits(8) for _ in range(L)))
# edge: leading zero bytes, all-zero, all-0xFF
roundtrip.append(bytes([0, 0, 0, 5, 200, 7]))
roundtrip.append(bytes([0] * 8))
roundtrip.append(bytes([0xFF] * 20))

iszero = []         # (raw_bytes, expected)
iszero.append((bytes([0] * 16), 1))
iszero.append((bytes([0]), 1))
iszero.append((bytes([0, 0, 1]), 0))
iszero.append((bytes([1]), 0))
iszero.append((bytes(rng.getrandbits(8) for _ in range(40)), 0))
iszero.append((bytes([0] * 33), 1))

bitlen = []         # (raw_bytes, expected_bits)
for L in (1, 2, 5, 16, 17, 32, 100):
    b = bytes(rng.getrandbits(8) for _ in range(L))
    bitlen.append((b, int.from_bytes(b, "big").bit_length()))
bitlen.append((bytes([0, 0, 0]), 0))
bitlen.append((bytes([1]), 1))
bitlen.append((bytes([0x80]), 8))
bitlen.append((bytes([0x01, 0x00]), 9))
bitlen.append((be((1 << 255), 32), 256))

rshift = []         # (raw_bytes, count, result_bytes)
for (L, c) in ((16, 1), (16, 7), (32, 3), (32, 14), (7, 0), (64, 5), (33, 11)):
    b = bytes(rng.getrandbits(8) for _ in range(L))
    v = int.from_bytes(b, "big")
    rshift.append((b, c, be(v >> c, L)))

# add/sub on a fixed W-limb width; announced length = W full 15-bit limbs
def addsub_case(W, force):
    nb = (15 * W + 7) // 8
    top = (1 << (15 * W)) - 1
    if force == "carry":
        a = rng.randint(top // 2, top)
        b = top - rng.randint(0, top // 4)
    elif force == "borrow":
        a = rng.randint(0, top // 2)
        b = rng.randint(top // 2, top)
    else:
        a = rng.randint(0, top)
        b = rng.randint(0, top)
    return W, nb, a, b, top

add = []            # (W, nb, a_bytes, b_bytes, sum_bytes, carry)
sub = []            # (W, nb, a_bytes, b_bytes, diff_bytes, borrow)
for (W, f) in ((18, ""), (18, "carry"), (18, ""), (137, ""), (137, "carry"), (137, "")):
    W, nb, a, b, top = addsub_case(W, f)
    s = a + b
    carry = 1 if s > top else 0
    add.append((W, nb, be(a, nb), be(b, nb), be(s & top, nb), carry))
for (W, f) in ((18, ""), (18, "borrow"), (18, ""), (137, ""), (137, "borrow"), (137, "")):
    W, nb, a, b, top = addsub_case(W, f)
    d = (a - b) & top
    borrow = 1 if a < b else 0
    sub.append((W, nb, be(a, nb), be(b, nb), be(d, nb), borrow))

reduce = []         # (modidx, a_bytes, mbytes, result_bytes)
def add_reduce(mi, a):
    n = MODS[mi]
    mb = mod_bytes(n)
    al = bytelen(a)
    reduce.append((mi, be(a, al), mb, be(a % n, mb)))
add_reduce(0, rng.getrandbits(512))          # a about twice the modulus width
add_reduce(0, MODS[0])                        # a == m  -> 0
add_reduce(0, MODS[0] + 1)                    # a == m+1 -> 1
add_reduce(0, MODS[0] - 1)                    # a == m-1 -> m-1
add_reduce(1, rng.getrandbits(300))
add_reduce(2, rng.getrandbits(4096))
add_reduce(3, rng.getrandbits(6144))
add_reduce(2, MODS[2] - 1)
add_reduce(3, MODS[3] + 12345)

montmul = []        # (modidx, a_bytes, b_bytes, mbytes, result_bytes)
def add_mmul(mi, a, b):
    n = MODS[mi]
    mb = mod_bytes(n)
    a %= n; b %= n
    montmul.append((mi, be(a, bytelen(a) if a else 1), be(b, bytelen(b) if b else 1),
                    mb, be((a * b) % n, mb)))
for _ in range(4):
    add_mmul(0, rng.getrandbits(256), rng.getrandbits(256))
add_mmul(0, 0, rng.getrandbits(256))          # zero operand
add_mmul(0, 1, rng.getrandbits(256))          # one operand
add_mmul(0, MODS[0] - 1, MODS[0] - 1)         # (m-1)^2
for _ in range(3):
    add_mmul(1, rng.getrandbits(256), rng.getrandbits(256))
for _ in range(3):
    add_mmul(2, rng.getrandbits(2048), rng.getrandbits(2048))
for _ in range(2):
    add_mmul(3, rng.getrandbits(3072), rng.getrandbits(3072))

modpow = []         # (modidx, base_bytes, e_bytes, mbytes, result_bytes)
def add_pow(mi, base, e):
    n = MODS[mi]
    mb = mod_bytes(n)
    base %= n
    el = bytelen(e)
    modpow.append((mi, be(base, bytelen(base) if base else 1), be(e, el),
                   mb, be(pow(base, e, n), mb)))
# 256-bit modulus, full 256-bit exponents (ECDH/ECDSA scalar shape)
for _ in range(4):
    add_pow(0, rng.getrandbits(256), rng.getrandbits(256))
add_pow(0, 0, rng.getrandbits(256))           # base 0
add_pow(0, 1, rng.getrandbits(256))           # base 1
add_pow(0, MODS[0] - 1, 2)                     # (m-1)^2 = 1
add_pow(1, rng.getrandbits(256), rng.getrandbits(200))
# RSA-verify shape: big modulus, tiny public exponent 65537
for _ in range(3):
    add_pow(2, rng.getrandbits(2048), 65537)
add_pow(2, rng.getrandbits(2048), 3)
for _ in range(2):
    add_pow(3, rng.getrandbits(3072), 65537)

modpow2 = []        # same shape, exercised via the windowed routine
def add_pow2(mi, base, e):
    n = MODS[mi]
    mb = mod_bytes(n)
    base %= n
    el = bytelen(e)
    modpow2.append((mi, be(base, bytelen(base) if base else 1), be(e, el),
                    mb, be(pow(base, e, n), mb)))
for _ in range(3):
    add_pow2(0, rng.getrandbits(256), rng.getrandbits(256))
add_pow2(1, rng.getrandbits(256), rng.getrandbits(128))
add_pow2(2, rng.getrandbits(2048), 65537)
add_pow2(3, rng.getrandbits(3072), 17)

# ---- emit ------------------------------------------------------------

def data_bytes(bs):
    lines = []
    for i in range(0, len(bs), 16):
        chunk = bs[i:i + 16]
        lines.append("  Data.b " + ",".join(str(x) for x in chunk))
    if not lines:
        lines.append("  Data.b 0")   # never emitted (all buffers non-empty)
    return "\n".join(lines)

# Integers are emitted as little-endian byte quads (Data.b) and read back
# with four Read.b, so nothing ever needs a 4-byte-aligned Data.l run -
# a Cortex-M0+ hard-faults on an unaligned load, and interleaving lengths
# with odd-length byte runs would otherwise misalign every Data.l.
def data_u32(v):
    v &= 0xFFFFFFFF
    return "  Data.b %d,%d,%d,%d" % (v & 255, (v >> 8) & 255, (v >> 16) & 255, (v >> 24) & 255)

def emit(path):
    L = []
    W = L.append
    W("; ======================================================================")
    W("; bignumVectors - GENERATED by tools/gen_bignum_vectors.py. DO NOT EDIT.")
    W(";")
    W("; Known-answer vectors for the i15 big-integer core, every expected")
    W("; value produced by python 3.14 arbitrary-precision integers. Walked by")
    W("; bignumSelfTest with Restore/Read. Bytes are big-endian; lengths and")
    W("; counts are Data.l read longhand.")
    W("; ======================================================================")
    W("#BN_MOD_COUNT     = %d" % len(MODS))
    W("#BN_RT_COUNT      = %d" % len(roundtrip))
    W("#BN_ISZERO_COUNT  = %d" % len(iszero))
    W("#BN_BITLEN_COUNT  = %d" % len(bitlen))
    W("#BN_RSHIFT_COUNT  = %d" % len(rshift))
    W("#BN_ADD_COUNT     = %d" % len(add))
    W("#BN_SUB_COUNT     = %d" % len(sub))
    W("#BN_REDUCE_COUNT  = %d" % len(reduce))
    W("#BN_MMUL_COUNT    = %d" % len(montmul))
    W("#BN_MODPOW_COUNT  = %d" % len(modpow))
    W("#BN_MODPOW2_COUNT = %d" % len(modpow2))
    W("")
    W("DataSection")

    # modulus table: for each, Data.l bytelen then the bytes (big-endian)
    W("  BnModTable:")
    for n in MODS:
        bl = bytelen(n)
        W(data_u32(bl))
        W(data_bytes(be(n, bl)))

    W("  BnRoundTrip:")
    for (b,) in [(x,) for x in roundtrip]:
        W(data_u32(len(b)))
        W(data_bytes(b))

    W("  BnIsZeroCases:")
    for (b, ex) in iszero:
        W(data_u32(len(b)))
        W(data_bytes(b))
        W(data_u32(ex))

    W("  BnBitlenCases:")
    for (b, ex) in bitlen:
        W(data_u32(len(b)))
        W(data_bytes(b))
        W(data_u32(ex))

    W("  BnRshiftCases:")
    for (b, c, r) in rshift:
        W(data_u32(len(b)))
        W(data_bytes(b))
        W(data_u32(c))
        W(data_bytes(r))

    W("  BnAddCases:")
    for (Wc, nb, a, b, s, carry) in add:
        W(data_u32(Wc))
        W(data_u32(nb))
        W(data_bytes(a))
        W(data_bytes(b))
        W(data_bytes(s))
        W(data_u32(carry))

    W("  BnSubCases:")
    for (Wc, nb, a, b, d, borrow) in sub:
        W(data_u32(Wc))
        W(data_u32(nb))
        W(data_bytes(a))
        W(data_bytes(b))
        W(data_bytes(d))
        W(data_u32(borrow))

    W("  BnReduceCases:")
    for (mi, a, mb, r) in reduce:
        W(data_u32(mi))
        W(data_u32(len(a)))
        W(data_bytes(a))
        W(data_u32(mb))
        W(data_bytes(r))

    W("  BnMontmulCases:")
    for (mi, a, b, mb, r) in montmul:
        W(data_u32(mi))
        W(data_u32(len(a)))
        W(data_bytes(a))
        W(data_u32(len(b)))
        W(data_bytes(b))
        W(data_u32(mb))
        W(data_bytes(r))

    W("  BnModpowCases:")
    for (mi, base, e, mb, r) in modpow:
        W(data_u32(mi))
        W(data_u32(len(base)))
        W(data_bytes(base))
        W(data_u32(len(e)))
        W(data_bytes(e))
        W(data_u32(mb))
        W(data_bytes(r))

    W("  BnModpow2Cases:")
    for (mi, base, e, mb, r) in modpow2:
        W(data_u32(mi))
        W(data_u32(len(base)))
        W(data_bytes(base))
        W(data_u32(len(e)))
        W(data_bytes(e))
        W(data_u32(mb))
        W(data_bytes(r))

    W("EndDataSection")
    W("")

    text = "\n".join(L)
    full = os.path.join(REPO, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    open(full, "w", newline="\n").write(text)
    return len(text)

total_checks = (len(roundtrip) + len(iszero) + len(bitlen) + len(rshift)
                + len(add) + len(sub) + len(reduce) + len(montmul)
                + len(modpow) + len(modpow2))

# THE EMIT LOOP IS GUARDED SO THIS FILE CAN BE IMPORTED (added 2026-09-04).
# tools/a64/a64_bignum_check.py reads the case tables above out of this
# module rather than carrying a second copy of them, exactly as the A64
# GCM gate reads gen_gcm_vectors.py: one table, four families, so "the
# Pi 4 passes the same vectors" is a fact about the source instead of two
# lists that were once eyeballed. A gate that had to import a file which
# rewrites three source files as a side effect would be a worse gate, so
# it no longer does.
if __name__ == "__main__":
    # Anvil carries no 32-bit family folders, so a family whose top-level
    # folder is absent from this tree is skipped instead of created.
    for path, fam in OUT:
        if not os.path.isdir(os.path.join(REPO, path.split("/")[0])):
            print("skipped %s: the %s folder is not in this tree" % (path, fam))
            continue
        n = emit(path)
        print("wrote %-52s (%d bytes)" % (path, n))
    print("per-family checks: %d   (x3 families = %d)"
          % (total_checks, total_checks * 3))
